### ISSUE TITLE
cosmetic error when recordings folder is empty

### ISSUE THREAD

**Issue by mcaptur** [kodi-pvr/pvr.vuplus#10]
Client: GetRecordings Error fetching lists for folder: '/hdd/movie/'

I get the above error when there are no recordings in folder even though folder exists

**Comment by Jalle19** [comment]
@slo617 do you know if this is still an issue? Especially with https://github.com/kodi-pvr/pvr.vuplus/pull/53 applied.

**Comment by slo617** [comment]
@Jalle19 #53 only sets the path for every record that has been found on the STB, but does not handle empty directories in any other way.
So yes, issue #10 still exist with #53 . Empty directories are not shown up under records.
This is a separate issue.

**Comment by phunkyfish** [comment]
@slo617 is this still an issue?
