### ISSUE TITLE
Used space instead of free space in GetDriveSpace

### ISSUE THREAD

**Issue by zehnerGIT** [kodi-pvr/pvr.vuplus#109]
If you you have a 1 TB hdd and 200 GB space are used, the client shows the text "200 GB of 1000 GB are available". I've checked it with Leia Beta 3 and 2 skins, both show the wrong text, so it should not be a skin issue.

I, for one, would not sum up the space if more than one hdd or stick is found, I would use only the biggest disk. The receiver also uses only one hdd for recordings, most of the time the other stick is only a swap-space or left from the last movie-night. Therefore the client shows more free space than effectively available. Not a problem if you have a lot of free space, but if you record way too much...

Thanks

**Comment by phunkyfish** [comment]
I have a PR in for this now. I've requested an opewebif change to also include the HDD mount path. Once that change is in I'll reduce it to only the drive used for recordings.
