### ISSUE TITLE
tsbuffer.ts never got deleted

### ISSUE THREAD

**Issue by M2k80** [kodi-pvr/pvr.vuplus#115]
my shield was just running out of space, then i found in pvr.vuplus folder a file called tsbuffer.ts with 6gb size. shouldnt this file be automaticly deleted if i close pvr or change the channel?
the last time, i used timeshift is some days ago.
how will this file be deleted automaticly?

**Comment by phunkyfish** [comment]
You’re right it should be removed when a stream stops. I’ll have a look at a fix this evening.
