### ISSUE TITLE
possibility of plugin duplication broken

### ISSUE THREAD

**Issue by tobias-d-oe** [kodi-pvr/pvr.vuplus#120]
Hi,
I have two enigma2 receivers. In the past it was easy to solve the problem by copying the pvr.vuplus folders and give it in the coresponding files an other name.
This feature seems to be broken now. If I activate the copied addon I cannot stream anymore from no vuplus plugin.
In the log I've found then these lines:

```
ERROR: CCurlFile::Open failed with code 0 for http://http//192.168.0.66:80/192.168.0.42:80/web/epgservice?sRef=1%3A0%3A1%3A384%3A21%3A85%3AC00000%3A0%3A0%3A0%3A:
ERROR: Open - failed to open source <http://http//192.168.0.66:80/192.168.0.42:80/web/epgservice?sRef=1%3A0%3A1%3A384%3A21%3A85%3AC00000%3A0%3A0%3A0%3A>

```

How you can see there will be inserted in the URL the IPs of both vuplus receivers.

Can this please be fixed?
Thanks in advance
Tobias

**Comment by tobias-d-oe** [comment]
I'm using OSMC and made a few tests for findng out when the problem the first time occures.
With version  17.8-340 [pvr.vuplus (07ec214, +9)] everything worked fine, with version 17.8.341 [pvr.vuplus(5d70dd2, +19)] problem occures the first time.

**Comment by ksooo** [comment]
> I have two enigma2 receivers. In the past it was easy to solve the problem by copying the pvr.vuplus folders and give it in the coresponding files an other name.

This was never and will never be supported. This si a dirty hack that can break at any time, sorry.

**Comment by tobias-d-oe** [comment]
Hello ksooo,
how to use than the plugin for more than one enigma2 receiver?

Thanks
