### ISSUE TITLE
hdd free space is wrong

### ISSUE THREAD

**Issue by M2k80** [kodi-pvr/pvr.vuplus#122]
for me it show 3.10TB available of 3.70TB, but should be GB not TB

**Comment by phunkyfish** [comment]
Can you post the output of:
 <your-ip>/web/deviceinfo ?

**Comment by M2k80** [comment]
<e2deviceinfo>
<e2oeversion>OE-Alliance 4.3</e2oeversion>
<e2enigmaversion>2018-10-19</e2enigmaversion>
<e2distroversion>openatv</e2distroversion>
<e2imageversion>6.3.0</e2imageversion>
<e2driverdate>20180319</e2driverdate>
<e2webifversion>OWIF 1.3.5</e2webifversion>
<e2fpversion>0</e2fpversion>
<e2devicename>Solo SE</e2devicename>
<e2frontends>
<e2frontend>
<e2name>Tuner A</e2name>
<e2model>Vuplus DVB-C NIM(SSH108) (DVB-C)</e2model>
</e2frontend>
</e2frontends>
<e2network>
<e2interface>
<e2name>eth0</e2name>
<e2mac>00:1d:ec:07:df:e8</e2mac>
<e2dhcp>True</e2dhcp>
<e2ip>192.168.2.21</e2ip>
<e2gateway>192.168.2.1</e2gateway>
<e2netmask>255.255.255.0</e2netmask>
</e2interface>
</e2network>
<e2hdds>
<e2hdd>
<e2model>Verbatim(Store n Go Drive)</e2model>
<e2capacity>3.7 GB</e2capacity>
<e2free>3.1 GB</e2free>
<e2mount>/media/hdd</e2mount>
</e2hdd>
</e2hdds>
</e2deviceinfo>

**Comment by M2k80** [comment]
https://pastebin.com/Dxh631Fr

**Comment by phunkyfish** [comment]
My own is the same. Strangely the API asks for bytes but appears to want KB.

Fix is simple will combine with next PR.

@ksooo the documentation for getdrivespace should be updated if this is true.

**Comment by phunkyfish** [comment]
Crazily my function was called getKb, so I must have gone to bytes with the previous fix instead of sticking with Kb. Go figure ;)

**Comment by phunkyfish** [comment]
Thanks, confirmed, same as my deviceinfo output.

**Comment by M2k80** [comment]
thank you for your fast response....
