### ISSUE TITLE
channel list for radio over OSD

### ISSUE THREAD

**Issue by M2k80** [kodi-pvr/pvr.vuplus#123]
if you play a radio channel its not possible to see the channel list like on tv, the button is missing.

same thing for the player-info and channel guide

could you add this maybe?

**Comment by ksooo** [comment]
Try latest Kodi nightly build. It's there now, accept player info. What is player-info, btw?

However, not an addon issue.

**Comment by M2k80** [comment]
ok, i see, player-info is from the skin estuary mod v2, i thought its on normal estuary too, but its not - my fault..
just tested default skin, and like you said, its there....i will talk to the skin dev.

thank you

**Comment by ksooo** [comment]
> i will talk to the skin dev.

the dev of which skin?

**Comment by M2k80** [comment]
i mean the skin dev for estuary mod v2.
i thought that this buttons that i was missing are part of the pvr plugin. thats why i reported it here.
but as you told me with latest nightly, these buttons are already there, i switched to the default estuary skin and they are there. so i will contact the dev for the estuary mod v2, to add these buttons there too.
do you know this mod? https://forum.kodi.tv/showthread.php?tid=306757
its a really nice version of estuary skin

**Comment by M2k80** [comment]
i know what you mean, but its running fine on nvdia shield, so it shouldnt get an i7 into its knees.

i like the estuary skin, its clear but the mod gives me some grafic features that i was missing for the default. for ex the player osd looks much nicer
![player](https://user-images.githubusercontent.com/6137556/47677261-f0802800-dbbe-11e8-9b25-143e19329f24.jpg)

**Comment by ksooo** [comment]
OMG, look at all these icons and buttons! Really not made for me. Who needs all this controls and icons?

**Comment by M2k80** [comment]
hahahaha
you´re funny.
i like the osd and its tranparence, the dvd cover and the the icons that give information about the movie.
all buttons right of the next to play next button, i dont need too, but i can live with them haha.

we all have different preferences :)

**Comment by ksooo** [comment]
sure...

**Comment by M2k80** [comment]
@ksooo can i ask you something offtopic? im just using the shield with the shield remote.
if i press up or down it opens the osd and i can change the channel when pressing ok (middle button)

is it possible to change the buttons left and right, that channel is directly changed, like channel next or back?
or is that part of the pvr.vuplus plugin?

**Comment by ksooo** [comment]
Yes that should be possible. Look at the forum, I'm sure there are several threads discussing how to remap keys. And no, this has nothing to do with the add-on.

**Comment by M2k80** [comment]
ok thank you for the info
