### ISSUE TITLE
update intervall breaks HD standby

### ISSUE THREAD

**Issue by Mik30** [kodi-pvr/pvr.vuplus#125]
please add an option to stop the update to wake up the hd...
or let the user set the interval to more than just 60 mins.

**Comment by Mik30** [comment]
From 0 (off) to 1 Day = 1440 Mins would be a good
range.
Perfect would be to be able to selectively disable the hd-access at all
to prevent unnecessary wake ups.


At 31.10.2018 09:28, you wrote:
What would be a good upper bound
for the update interval?
> On 31 Oct 2018, at 05:15, Mik30 <notifications@github.com>
wrote:
> 
> please add an option to stop the update to wake up the hd...
> or let the user set the interval to more than just 60 mins.
> 
> 
> You are receiving this because you are subscribed to this
thread.
> Reply to this email directly, view it on GitHub, or mute the
thread.
­
You are receiving this because you authored the thread.
Reply to this email directly,

view it on GitHub, or

mute the thread.

**Comment by phunkyfish** [comment]
I’m ok with one day but I’m not sure off is a good idea. That’s essentially saying never update any timer or recording information in Kodi. Defeats the purpose of the PVR in many ways.

I have mine set to 5 mins so I can watch recordings straight away once available.

Would you agree?

**Comment by Mik30** [comment]
I do not agree with any method that forces a regular wakeup
of the HD.
The reason is plain simple: The caused frequent Head-Parking will kill
the drive early.
Above that the Drive scanning is useless. Only the EPG and Recording
Timers need
to be fetched. The actual recording on the HD can be scanned once during
bootup.
After that an additional recording is known by expired recording timers,
which
can be added prelimenary to the list of recordings. Only if the user
actually
plays a recording the list should the list be updated by a real HD
access.
On the other hand it could be possible to add a trigger to manually force
an update.
Currently kodi wakes up the HD every 2 minutes. That will reduce the
lifespan of every HD very much.

At 31.10.2018 10:13, you wrote:
Iâm ok with one day but Iâm
not sure off is a good idea. Thatâs essentially saying never update any
timer or recording information in Kodi. Defeats the purpose of the PVR in
many ways.
I have mine set to 5 mins so I can watch recordings straight away once
available.
Would you agree?
> On 31 Oct 2018, at 09:09, Mik30 <notifications@github.com>
wrote:
> 
> 
> 
> From 0 (off) to 1 Day = 1440 Mins would be a good
> range.
> Perfect would be to be able to selectively disable the hd-access at
all
> to prevent unnecessary wake ups.
> 
> 
> At 31.10.2018 09:28, you wrote:
> What would be a good upper bound
> for the update interval?
> > On 31 Oct 2018, at 05:15, Mik30
<notifications@github.com>
> wrote:
> > 
> > please add an option to stop the update to wake up the
hd...
> > or let the user set the interval to more than just 60
mins.
> > 
> > Â
> > You are receiving this because you are subscribed to this
> thread.
> > Reply to this email directly, view it on GitHub, or mute
the
> thread.
> 
> You are receiving this because you authored the thread.
> Reply to this email directly,
> 
> view it on GitHub, or
> 
> mute the thread.
> 
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the
thread.
­
You are receiving this because you authored the thread.
Reply to this email directly,

view it on GitHub, or

mute the thread.

**Comment by phunkyfish** [comment]
But if you use autotimers there could be new recordings that were not there on startup.

You would never know these existed unless you restart.

How about an option to only check on certain times of the day, during a time window or something like that?

**Comment by Mik30** [comment]
It is sufficient to sync the interface data like EPG,
Programs, Bouquets and Timers but do NOT wakeup the hd!
HD data must only be scanned during expülcit HD access. That is done only
during playback and startup or on occasion through a manual trigger that
could be added.
You mention the Timers:
Executed Timers can be resolved by the Timer-Information itself. There
ist no need to wakeup the hd.
If the timer is executed just shove the entry to the recording list. But
do not wake up the hd!


At 01.11.2018 09:53, you wrote:
But if you use autotimers there
could be new recordings that were not there on startup.
You would never know these existed unless you restart.
How about an option to only check on certain times of the day, during a
time window or something like that?
> On 1 Nov 2018, at 04:54, Mik30 <notifications@github.com>
wrote:
> 
> 
> 
> I do not agree with any method that forces a regular wakeup
> of the HD.
> The reason is plain simple: The caused frequent Head-Parking will
kill
> the drive early.
> Above that the Drive scanning is useless. Only the EPG and
Recording
> Timers need
> to be fetched. The actual recording on the HD can be scanned once
during
> bootup.
> After that an additional recording is known by expired recording
timers,
> which
> can be added prelimenary to the list of recordings. Only if the
user
> actually
> plays a recording the list should the list be updated by a real
HD
> access.
> On the other hand it could be possible to add a trigger to manually
force
> an update.
> Currently kodi wakes up the HD every 2 minutes. That will reduce
the
> lifespan of every HD very much.
> 
> At 31.10.2018 10:13, you wrote:
> IÃ¢ÂÂm ok with one day but IÃ¢ÂÂm
> not sure off is a good idea. ThatÃ¢ÂÂs essentially saying never
update any
> timer or recording information in Kodi. Defeats the purpose of the
PVR in
> many ways.
> I have mine set to 5 mins so I can watch recordings straight away
once
> available.
> Would you agree?
> > On 31 Oct 2018, at 09:09, Mik30
<notifications@github.com>
> wrote:
> > 
> > 
> > 
> > From 0 (off) to 1 Day = 1440 Mins would be a good
> > range.
> > Perfect would be to be able to selectively disable the
hd-access at
> all
> > to prevent unnecessary wake ups.
> > 
> > 
> > At 31.10.2018 09:28, you wrote:
> > What would be a good upper bound
> > for the update interval?
> > > On 31 Oct 2018, at 05:15, Mik30
> <notifications@github.com>
> > wrote:
> > > 
> > > please add an option to stop the update to wake up
the
> hd...
> > > or let the user set the interval to more than just 60
> mins.
> > > 
> > > ÃÂ
> > > You are receiving this because you are subscribed to
this
> > thread.
> > > Reply to this email directly, view it on GitHub, or
mute
> the
> > thread.
> > 
> > You are receiving this because you authored the thread.
> > Reply to this email directly,
> > 
> > view it on GitHub, or
> > 
> > mute the thread.
> > Â
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub, or mute
the
> thread.
> 
> You are receiving this because you authored the thread.
> Reply to this email directly,
> 
> view it on GitHub, or
> 
> mute the thread.
> 
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the
thread.
­
You are receiving this because you authored the thread.
Reply to this email directly,

view it on GitHub, or

mute the thread.

**Comment by phunkyfish** [comment]
This is dictated by the API made available by OpenWebIf. I can’t just assume the recoding is there, an API call is made to retrieve all recordings. If the HD is being woken up then a better solution would be for the STB to cache the list of recordings. 

There may be images that do this already, afraid I don’t know.

Which image do you use?

**Comment by Mik30** [comment]
what is the problem in assuming the recording was done according to the
timer?
If the user plays a recording one should anywway do a check first and
abort if the recording are not there.
I use milhouse libreelec for rpi2.

At 01.11.2018 12:31, you wrote:
This is dictated by the API made
available by OpenWebIf. I canât just assume the recoding is there, an
API call is made to retrieve all recordings. If the HD is being woken up
then a better solution would be for the STB to cache the list of
recordings. 
There may be images that do this already, afraid I donât know.
Which image do you use?
> On 1 Nov 2018, at 10:12, Mik30 <notifications@github.com>
wrote:
> 
> 
> 
> It is sufficient to sync the interface data like EPG,
> Programs, Bouquets and Timers but do NOT wakeup the hd!
> HD data must only be scanned during expÃ¼lcit HD access. That is
done only
> during playback and startup or on occasion through a manual trigger
that
> could be added.
> You mention the Timers:
> Executed Timers can be resolved by the Timer-Information itself.
There
> ist no need to wakeup the hd.
> If the timer is executed just shove the entry to the recording list.
But
> do not wake up the hd!
> 
> 
> At 01.11.2018 09:53, you wrote:
> But if you use autotimers there
> could be new recordings that were not there on startup.
> You would never know these existed unless you restart.
> How about an option to only check on certain times of the day,
during a
> time window or something like that?
> > On 1 Nov 2018, at 04:54, Mik30
<notifications@github.com>
> wrote:
> > 
> > 
> > 
> > I do not agree with any method that forces a regular
wakeup
> > of the HD.
> > The reason is plain simple: The caused frequent Head-Parking
will
> kill
> > the drive early.
> > Above that the Drive scanning is useless. Only the EPG and
> Recording
> > Timers need
> > to be fetched. The actual recording on the HD can be scanned
once
> during
> > bootup.
> > After that an additional recording is known by expired
recording
> timers,
> > which
> > can be added prelimenary to the list of recordings. Only if
the
> user
> > actually
> > plays a recording the list should the list be updated by a
real
> HD
> > access.
> > On the other hand it could be possible to add a trigger to
manually
> force
> > an update.
> > Currently kodi wakes up the HD every 2 minutes. That will
reduce
> the
> > lifespan of every HD very much.
> > 
> > At 31.10.2018 10:13, you wrote:
> > IÃÂ¢ÃÂÃÂm ok with one day but IÃÂ¢ÃÂÃÂm
> > not sure off is a good idea. ThatÃÂ¢ÃÂÃÂs essentially
saying never
> update any
> > timer or recording information in Kodi. Defeats the purpose of
the
> PVR in
> > many ways.
> > I have mine set to 5 mins so I can watch recordings straight
away
> once
> > available.
> > Would you agree?
> > > On 31 Oct 2018, at 09:09, Mik30
> <notifications@github.com>
> > wrote:
> > > 
> > > 
> > > 
> > > From 0 (off) to 1 Day = 1440 Mins would be a good
> > > range.
> > > Perfect would be to be able to selectively disable
the
> hd-access at
> > all
> > > to prevent unnecessary wake ups.
> > > 
> > > 
> > > At 31.10.2018 09:28, you wrote:
> > > What would be a good upper bound
> > > for the update interval?
> > > > On 31 Oct 2018, at 05:15, Mik30
> > <notifications@github.com>
> > > wrote:
> > > > 
> > > > please add an option to stop the update to wake
up
> the
> > hd...
> > > > or let the user set the interval to more than just
60
> > mins.
> > > > 
> > > > ÃÂÃÂ
> > > > You are receiving this because you are subscribed
to
> this
> > > thread.
> > > > Reply to this email directly, view it on GitHub,
or
> mute
> > the
> > > thread.
> > > 
> > > You are receiving this because you authored the
thread.
> > > Reply to this email directly,
> > > 
> > > view it on GitHub, or
> > > 
> > > mute the thread.
> > > ÃÂ
> > > You are receiving this because you commented.
> > > Reply to this email directly, view it on GitHub, or
mute
> the
> > thread.
> > 
> > You are receiving this because you authored the thread.
> > Reply to this email directly,
> > 
> > view it on GitHub, or
> > 
> > mute the thread.
> > Â
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub, or mute
the
> thread.
> 
> You are receiving this because you authored the thread.
> Reply to this email directly,
> 
> view it on GitHub, or
> 
> mute the thread.
> 
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the
thread.
­
You are receiving this because you authored the thread.
Reply to this email directly,

view it on GitHub, or

mute the thread.

**Comment by phunkyfish** [comment]
But where is the recording? Depending on the rules used on the STB you may not know it’s location before calling the API.

There are numerous plugins that do things with locations. The solution above has to work for all users and not a subset.

**Comment by slo617** [comment]
> I’m ok with one day but I’m not sure off is a good idea.

I guess any interval that can be configured is fine.
Even "off" makes sense for users who want to use NFS or SMB to play recordings for instance.

**Comment by Mik30** [comment]
Do whatever you want but do NOT wakeup the HD without
permission.
I repeat myself: frequent HD parking kills the drive.
Nobody cares about a pending recording list if the that depends on
killing the HD.
Just add a manual trigger and everybody is fine with that.

At 01.11.2018 16:03, you wrote:
But where is the recording?
Depending on the rules used on the STB you may not know itâs location
before calling the API.
There are numerous plugins that do things with locations. The solution
above has to work for all users and not a subset.
> On 1 Nov 2018, at 10:12, Mik30 <notifications@github.com>
wrote:
> 
> 
> 
> It is sufficient to sync the interface data like EPG,
> Programs, Bouquets and Timers but do NOT wakeup the hd!
> HD data must only be scanned during expÃ¼lcit HD access. That is
done only
> during playback and startup or on occasion through a manual trigger
that
> could be added.
> You mention the Timers:
> Executed Timers can be resolved by the Timer-Information itself.
There
> ist no need to wakeup the hd.
> If the timer is executed just shove the entry to the recording list.
But
> do not wake up the hd!
> 
> 
> At 01.11.2018 09:53, you wrote:
> But if you use autotimers there
> could be new recordings that were not there on startup.
> You would never know these existed unless you restart.
> How about an option to only check on certain times of the day,
during a
> time window or something like that?
> > On 1 Nov 2018, at 04:54, Mik30
<notifications@github.com>
> wrote:
> > 
> > 
> > 
> > I do not agree with any method that forces a regular
wakeup
> > of the HD.
> > The reason is plain simple: The caused frequent Head-Parking
will
> kill
> > the drive early.
> > Above that the Drive scanning is useless. Only the EPG and
> Recording
> > Timers need
> > to be fetched. The actual recording on the HD can be scanned
once
> during
> > bootup.
> > After that an additional recording is known by expired
recording
> timers,
> > which
> > can be added prelimenary to the list of recordings. Only if
the
> user
> > actually
> > plays a recording the list should the list be updated by a
real
> HD
> > access.
> > On the other hand it could be possible to add a trigger to
manually
> force
> > an update.
> > Currently kodi wakes up the HD every 2 minutes. That will
reduce
> the
> > lifespan of every HD very much.
> > 
> > At 31.10.2018 10:13, you wrote:
> > IÃÂ¢ÃÂÃÂm ok with one day but IÃÂ¢ÃÂÃÂm
> > not sure off is a good idea. ThatÃÂ¢ÃÂÃÂs essentially
saying never
> update any
> > timer or recording information in Kodi. Defeats the purpose of
the
> PVR in
> > many ways.
> > I have mine set to 5 mins so I can watch recordings straight
away
> once
> > available.
> > Would you agree?
> > > On 31 Oct 2018, at 09:09, Mik30
> <notifications@github.com>
> > wrote:
> > > 
> > > 
> > > 
> > > From 0 (off) to 1 Day = 1440 Mins would be a good
> > > range.
> > > Perfect would be to be able to selectively disable
the
> hd-access at
> > all
> > > to prevent unnecessary wake ups.
> > > 
> > > 
> > > At 31.10.2018 09:28, you wrote:
> > > What would be a good upper bound
> > > for the update interval?
> > > > On 31 Oct 2018, at 05:15, Mik30
> > <notifications@github.com>
> > > wrote:
> > > > 
> > > > please add an option to stop the update to wake
up
> the
> > hd...
> > > > or let the user set the interval to more than just
60
> > mins.
> > > > 
> > > > ÃÂÃÂ
> > > > You are receiving this because you are subscribed
to
> this
> > > thread.
> > > > Reply to this email directly, view it on GitHub,
or
> mute
> > the
> > > thread.
> > > 
> > > You are receiving this because you authored the
thread.
> > > Reply to this email directly,
> > > 
> > > view it on GitHub, or
> > > 
> > > mute the thread.
> > > ÃÂ
> > > You are receiving this because you commented.
> > > Reply to this email directly, view it on GitHub, or
mute
> the
> > thread.
> > 
> > You are receiving this because you authored the thread.
> > Reply to this email directly,
> > 
> > view it on GitHub, or
> > 
> > mute the thread.
> > Â
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub, or mute
the
> thread.
> 
> You are receiving this because you authored the thread.
> Reply to this email directly,
> 
> view it on GitHub, or
> 
> mute the thread.
> 
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the
thread.
­
You are receiving this because you authored the thread.
Reply to this email directly,

view it on GitHub, or

mute the thread.

**Comment by phunkyfish** [comment]
I wonder if there is a way to check if the HD is parked?

Then we would have a good solution to all cases.

Let me look into it.

**Comment by phunkyfish** [comment]
I can’t see if the HD is parked but I can tell the current power state of the STB.

0: Toggle StandBy
1: DeepStandBy
2: Reboot
3: Restart Enigma
4: Wakeup
5: Standby

So could do something like no recording updates if in standby/deep standby or something to that effect.

Would that be a sensible substitute or not at all?

**Comment by M2k80** [comment]
easiest solution....never park the hdd :)

**Comment by phunkyfish** [comment]
Are you saying you want the option to never update anything after a reboot?

No timer updates, no autotimer or recording updates. The only thing that would update would be EPG?

So if your Kodi runs for 2 months the only updates you would see would be EPG and nothing else.

**Comment by M2k80** [comment]
i dont use recordings, but if i would use it and want it allways on newest state, i would disable on my hdd the power down feature and let the hdd allways awake, or i wouldnt set the reciver to standby and leave it allways powered on.
in this case the reciver is used as a server and for this case you want all up to date, so if users dont want wake up the hdd every 2 mins, they should use it as a server and disable the power features from the hdd and let it allways on. only my opinion

**Comment by phunkyfish** [comment]
That viewpoint makes sense to me. 

However I think @Mik30 has a special use case. I don’t mind solving for it but I need more information on exactly what he’s trying to avoid. Not waking the HDD is not a requirement as I can’t test it or prove it.

If all he wants is to disable recordings and leave just timers updating that is a requirement. It’s doesn’t make a whole lot of sense to me as overall the STB is a server.

A real solution to this would be to request a change to OpenWebIf or enigma2 to cache the Recordings data on the STB so no HD access is required to change it. 

The addon shouldn’t need to solve for this but I can add a simple change if we can define a simple requirement @Mik30

**Comment by M2k80** [comment]
maybe the actualisation for example recordings will only done, when you try to show recordings?
i click on recordings and then the list will be updated and then showed?
same for timers, click on timers, then the list will be updated and showed?
instead of updating all the time?
i dont know if some thing is a possible solution.

**Comment by Mik30** [comment]
That comes close to what I suggested. Reduce the HD scan to actual HD access: i.e. Playback, Boot and recordings. The Timerlist shows, when recordings happen. So it is just false to say that a Client like Kodi is unable to know if the hd is awake. It is awake on Boot, Play and during a Timer Event. 

Am 4. November 2018 23:40:42 MEZ schrieb M2k80 <notifications@github.com>:

**Comment by phunkyfish** [comment]
It’s all event based, so in many ways it works in a similar way (just not on click of a menu). But it’s the update timer that catches changes not made my this particular Kodi. Such as changes on the STB or made by other Kodi’s.

The point is though it’s supposed to be interactive. I.e. if a timer appears from somewhere else it should inform you on your Kodi and be added to up next.

**Comment by phunkyfish** [comment]
But this is not how the addon works I’m afraid. The addon doesn’t decide to update when an item is clicked, it updates based on time to make sure it’s current with all changes outside if it’s control.

On my system for instance the HDD is not used for playback at all, there is no need for it as timeshift happens in Kodi. 

So if you can please define what is the behaviour your are trying to avoid be it just recording updates or whatever and we can try to come up with a solution.

**Comment by phunkyfish** [comment]
Would this solution work:

- leave the update interval as is
- add an update mode setting
- Mode can be “Timers and Recordings” or “Only Timers”

So recordings would only be loaded on boot and when a timer event happens if you choose Only Timers as the mode. This would not update recording if they change on the STB such as deletions etc. Until the next timer event.

**Comment by phunkyfish** [comment]
@Mik30 does the above work for your use case?

**Comment by Mik30** [comment]
The current intervall range (2-60 mins) is inapropriate: it
is definetly too short.
The described modus operandi with different trigger sources seems
plausible.

At 05.11.2018 11:00, you wrote:
Would this solution work:

leave the update interval as is
add an update mode setting
Mode can be âTimers and Recordingsâ or âOnly Timersâ

So recordings would only be loaded on boot and when a timer event happens
if you choose Only Timers as the mode. This would not update recording if
they change on the STB such as deletions etc. Until the next timer
event.
­
You are receiving this because you were mentioned.
Reply to this email directly,

view it on GitHub, or

mute the thread.

**Comment by phunkyfish** [comment]
What should the interval be?

**Comment by Mik30** [comment]
The range should at least allow up to 1 Day (1440
Mins).
At 07.11.2018 08:11, you wrote:
What should the interval
be?

**Comment by phunkyfish** [comment]
Ok so we go with this:

- change the range of the update interval up to 1440 mins
- add an update mode setting
- Mode can be “Timers and Recordings” or “Only Timers”

Once the current PR goes through I’ll work on this. Hopefully will make it there in time for Leia launch.

**Comment by phunkyfish** [comment]
It's in here, so whenever this PR get's approved: #132 

I also found another bug around active timers so that got fixed too. When timers only is selected the only time a recording update will happen is when there is any timer event (this is not linked to the update schedule, it will happen straight away).

**Comment by Mik30** [comment]
I just tested enigma2.pvr addon v3.28.7.1 on an official
libreelec 9.1.502:
Setting "Update mode" to "timers only" and the
interval to 1440 min. lets the plugin wakeup the HDD and scan the
drive.
That is NOT what it is supposed to do. On "timers only" it is
forbidden to access the hdd.

**Comment by phunkyfish** [comment]
How often does it wake the HDD?

**Comment by phunkyfish** [comment]
After 1440 mins? Also what version of the addon did you have before this where you did not have this issue.

**Comment by Mik30** [comment]
Yes, when the intervall ends, it does the refresh but it
ignores the setting "Update mode" to "timers
only".
It uses the other "Update mode".

At 08.11.2019 09:45, you wrote:
After 1440 mins?
­
You are receiving this because you were mentioned.
Reply to this email directly,

view it on GitHub, or

unsubscribe.

**Comment by phunkyfish** [comment]
Can you capture a debug log of this happening? That code has not changed in quite a while.

What was the previous addon version you used?

**Comment by Mik30** [comment]
Well, I did a fresh install of everything explicitly for
this test.
I guess it has something to do with this setting:
    <setting
id="channelandgroupupdatehour"
default="true">4</setting>
Because I also tried these settings and they did not
result in a minutewise hdd access:
    <setting
id="updateint">1</setting>
    <setting
id="updatemode">1</setting>
Nevertheless at four o'clock the hdd access
occours.
Therefore it must have something to do with the first setting mentioned
above.


At 08.11.2019 13:37, you wrote:
Can you capture a debug log of
this happening? That code has not changed in quite a while.
What was the previous addon version you used?
­
You are receiving this because you were mentioned.
Reply to this email directly,

view it on GitHub, or

unsubscribe.

**Comment by phunkyfish** [comment]
Ok, so just disable the channels and group update mode.

It should only update channels and groups if there is a change. Regardless in normal log mode if this is happening you will get a log statement. So look for that at 4am. Should start with `CheckForChannelAndGroupChanges`.

The real question is why it’s detecting changes unless you get new channels or groups everyday?
