### ISSUE TITLE
Stand by command after exit.

### ISSUE THREAD

**Issue by majko96** [kodi-pvr/pvr.vuplus#128]
In the Enigma2 plugin there is an option to send Deep Standby command to the Enigma2 box on shutdown of Kodi.
There is no option to send a normal standby command. 

When looking at the OpenWebif interface I see that on closing Kodi the Enigma2 box still has an active stream. 
Is there a way to send a normal standby command to the Enigma2 box on exiting Kodi?

**Comment by majko96** [comment]
here is something what i found on the web:


#!/usr/bin/python
# Code to put the dreambox in standby mode using the Web Interface.
# For this to work, please ensure you have enabled the webinterface 
# on your box, and and no authentication specified.

import urllib2

def WebIf(command):

    try:
        sock=urllib2.urlopen('http://IP adress enigma2 box/web/' + command)
        data=sock.read()
    except urllib2.URLError:
        pass
    except urllib2.HTTPError:
        pass
    except urllib2.httplib.BadStatusLine:
        pass
    else:
        sock.close()
        return(data)

WebIf('powerstate?newstate=0')

**Comment by majko96** [comment]
at first must be sent command for wakeup and then command for standby, and after that E2 stopped streaming, please can you add  this thing into plugin settings? :)

**Comment by phunkyfish** [comment]
So an option to use normal standby instead of deep standby?

Or are you just trying to close the stream? If the stream is not closing that could be a bug.

**Comment by majko96** [comment]
Am just trying to close the stream only. Hmm,,,but my box/vu+ zero/ OpenPli 6.2,,, is   during streaming in standby,, so if I send command to Standby nothing happend i must send wakeup standby and than stanby...and after this streaming is stopped.
Not streaming in enigma2 client....only streaming from my vu is stopped.
Client works very well :) this is only mini problem :)

Stream of Enigma2 client can be normall stopped, but i need stopped it on the vu+ because oscam,,ecm,, :)

**Comment by phunkyfish** [comment]
And does it stop streaming if you send to deep standby?

**Comment by majko96** [comment]
Yes, it stop streaming,,, it stop everything ...but from deep standby it can be wakeup only with ir remote.

**Comment by majko96** [comment]
I can try other OS on my e2 box ...tomorrow i try openVix

**Comment by majko96** [comment]
If I play a stream and than stop it,,,vu+ zero still streaming :)

**Comment by phunkyfish** [comment]
How do you check this? I run OpenVix and I could check mine. To see if it’s the same.

**Comment by majko96** [comment]
I see it on my oscam server, because if E2 box is still streamnig it need ecm from oscam.
And in openwebif it shows that still is playing any channel

**Comment by phunkyfish** [comment]
Do you mean Box Info in OpenWebIf?

Is that where you see the streams?

If so then on Vix I don’t see it happen.

**Comment by majko96** [comment]
I see it in the top left corner under the openwebif sign,,,,there is a info about playing/streaming TV channel,,, only on desktop version page openwebif ,,,

**Comment by phunkyfish** [comment]
So do I. But on Vix if I click the green slider for standby it disappears and then if I switch it on again it comes back.

So you want this behaviour when the addon exits right? What do you do when Kodi is not shutdown?

**Comment by majko96** [comment]
Uuuf my language skill are at the end, tomorrow I try it on openvix

**Comment by majko96** [comment]
Sorry bro :)

**Comment by phunkyfish** [comment]
No worries.

**Comment by majko96** [comment]
So now I try OpenVix but no difference. After stop streaming on Kodi, Vu+ still streaming.
so i need when the addon exits send commands wakeup standby and then standby. i think that you understand me.... :)

**Comment by phunkyfish** [comment]
Got you. Let me look into how to do this.

**Comment by majko96** [comment]
When something new, let me know.

**Comment by M2k80** [comment]
Box isnt steaming, the box stay on the last open channel, in standby or normal power state, that is normal. In standby mode only hdmi is disabled. Thats oscam and other services are still running when box is in standby. You cant change this.
If you dont want to see ecm usage in oscam, change to a free channel before you close kodi

**Comment by M2k80** [comment]
If you have a single tuner box, and would still running, you wouldnt able to change the channel after you turned on the box, because the transponder is locked

**Comment by majko96** [comment]
But when you send command for wakeup standby and than standby box stops reading ecm from oscam.

**Comment by phunkyfish** [comment]
Just to clarify, if on exit the box gets a wake up command, followed by standby that solves your issue?

**Comment by phunkyfish** [comment]
You should be able to test this by executing these two URLs:

- http://<you-ip>/web/powerstate?newstate=4
- http://<you-ip>/web/powerstate?newstate=5

The first is wake up and the second is standby

**Comment by majko96** [comment]
yes, yes....this is a functional solution!

**Comment by majko96** [comment]
if on exit the box gets a wake up command, followed by standby that solves my issue ;)

**Comment by phunkyfish** [comment]
Ok, cool

**Comment by majko96** [comment]
am ready for testing :)

**Comment by phunkyfish** [comment]
It might be a few days before this goes out. I have another PR to go through first ;)

**Comment by majko96** [comment]
that's OK :) thx so much

**Comment by M2k80** [comment]
Are you sure, wake up will not call cec and TV and avr will turn on?

**Comment by phunkyfish** [comment]
It might do but will not be the default option. The options for powerstate On exit will be, “Disabled”, “Deepstandby” and “Wakeup, then Standby”

**Comment by majko96** [comment]
hello :) how it is going?

**Comment by phunkyfish** [comment]
I’m still waiting for the current PR to be reviewed. Until that’s gone through I can’t progress this.

**Comment by phunkyfish** [comment]
It's in here, so whenever this PR get's approved: https://github.com/kodi-pvr/pvr.vuplus/pull/132
