### ISSUE TITLE
channel switching and [radio lag fixed]

### ISSUE THREAD

**Issue by M2k80** [kodi-pvr/pvr.vuplus#129]
do you have with latest build problems on channel switch or playing radio with lags?
which image do you use? i am on latest openatv.

i just try to find out, is it the openatv image or kodi

**Comment by phunkyfish** [comment]
No, I don’t. What’s the issue you are having?

I use OpenVix.

**Comment by M2k80** [comment]
just updated to latest kodi image, i am using a nvidia shield.
on channel switch i get now sometimes first a black screen and sound, after some seconds it show buffering, then the pictures comes. if i switch some more channels, screen stays black and kodi hang forever. i saw some of these errors in kodi log, debug not enabled.
maybe this is a result from latest changes of peak3d or this only happen because openatv stream dont work as execpted...i just try to find this out. tomorow i will first test another image on my reciver.
maybe ill try openvix too, or get back to vti image. if its kodi, i will do a complete debug and report the issue
ERROR: CMediaCodecVideoBuffer::ReleaseOutputBuffer error -10000 in render(0)
ERROR: CMediaCodecVideoBuffer::ReleaseOutputBuffer error -10000 in render(1)
ERROR: CMediaCodecVideoBuffer::ReleaseOutputBuffer error -10000 in render(0)

and if i play radio stream, it take some seconds to start and then much buffering.

**Comment by phunkyfish** [comment]
Ok, let me know.

Also which version of the Enigma2 plugin do you have?

And what was the last working version you used before this build?

**Comment by M2k80** [comment]
hmm sorry to say, was just 4 days not at home and just updated my build. now its 3.14.1.
but i cant say which version it was before.

but radio nonstop buffering is about 2 weeks

**Comment by M2k80** [comment]
hey, do you have any chat tool, or maybe steam acc?? it would make some things easier

**Comment by M2k80** [comment]
https://github.com/xbmc/xbmc/issues/14804

**Comment by phunkyfish** [comment]
Afraid not, we try to keep all communication on official channels so everyone knows what’s going on.

**Comment by phunkyfish** [comment]
On this I have noticed a lag in general in Kodi, I’m not sure this is related to the addon though as nothing had fundamentally changed recently.

**Comment by M2k80** [comment]
i will try later openvix image and test radio, i think it an image problem...but we will see

**Comment by M2k80** [comment]
any idea why the pvr plugin could create a socks error and no stream loads anymore until reboot of the device?

**Comment by phunkyfish** [comment]
Afraid not. It’s not something I’ve seen before.

**Comment by phunkyfish** [comment]
Do you have a error?

**Comment by M2k80** [comment]
no i dont.
so now i switched to openvix, and radio lag is gone, its defenitivly an openatv problem.

**Comment by phunkyfish** [comment]
Ok, cool, glad you are sorted. Feel free to close this issue

**Comment by M2k80** [comment]
the problem about channel switching with freeze frame and buffering is still there.

radio bug is fixed

**Comment by M2k80** [comment]
just wait for response from the devs on an other reported issue, that seems to be the same problem as mine.
https://github.com/xbmc/xbmc/issues/14828

**Comment by phunkyfish** [comment]
@M2k80 any luck finding a resolution on this?

**Comment by M2k80** [comment]
no not really, but i think we can close this one here, 
if i get some time, i will open a new issue on kodi git.
becouse for android there is only one guy that could fix it and i dont want to stress him at this time of the year. its not a big problem, maybe it fixes itself when other problems get fixed

happy new year :)

**Comment by phunkyfish** [comment]
Happy new year 😉
