### ISSUE TITLE
since 3.15.0 pvr manager cant start

### ISSUE THREAD

**Issue by M2k80** [kodi-pvr/pvr.vuplus#134]
just updated to latest plugin version, now pvr manager cant start anymore

**Comment by phunkyfish** [comment]
Do you have a debug log?

**Comment by M2k80** [comment]
just a short part
3:05:38.931 T:29716    INFO: AddOnLog: Enigma2 Client: pvr.vuplus - enigma2::utilities::WebUtils::GetHttpXML Got result. Length: 983
23:05:38.931 T:29716  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - enigma2::Admin::LoadDeviceInfo - DeviceInfo
23:05:38.931 T:29716  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - enigma2::Admin::LoadDeviceInfo - E2EnigmaVersion: 2018-11-14
23:05:38.931 T:29716  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - enigma2::Admin::LoadDeviceInfo - E2ImageVersion: 5.2.013
23:05:38.931 T:29716  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - enigma2::Admin::LoadDeviceInfo - E2WebIfVersion: OWIF 1.3.5
23:05:38.931 T:29716  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - enigma2::Admin::LoadDeviceInfo - E2DeviceName: Solo SE
23:05:38.932 T:29716    INFO: AddOnLog: Enigma2 Client: pvr.vuplus - enigma2::utilities::WebUtils::GetHttpXML Open webAPI with URL: 'http://192.168.2.21:80/autotimer/get'
23:05:38.932 T:29716   DEBUG: CFileCache::Open - opening <autotimer/get> using cache
23:05:38.932 T:29716   DEBUG: CurlFile::Open(0x189fcee2c80) http://192.168.2.21:80/autotimer/get
23:05:39.102 T:9244   DEBUG: Thread FileCache start, auto delete: false
23:05:39.103 T:9244    INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?)
23:05:39.103 T:9244   DEBUG: Thread FileCache 9244 terminating
23:05:39.103 T:29716    INFO: AddOnLog: Enigma2 Client: pvr.vuplus - enigma2::utilities::WebUtils::GetHttpXML Got result. Length: 9580
23:05:39.103 T:29716   DEBUG: AddOnLog: Enigma2 Client: pvr.vuplus - enigma2::Admin::LoadAutoTimerSettings Add Tag AutoTimer to Tags: 1, Add AutoTimer Name to tags: 1
23:05:39.103 T:29716    INFO: AddOnLog: Enigma2 Client: pvr.vuplus - enigma2::utilities::WebUtils::GetHttpXML Open webAPI with URL: 'http://192.168.2.21:80/web/settings'
23:05:39.103 T:29716   DEBUG: CFileCache::Open - opening <web/settings> using cache
23:05:39.104 T:29716   DEBUG: CurlFile::Open(0x189fcee7400) http://192.168.2.21:80/web/settings
23:05:39.154 T:29884   DEBUG: Thread FileCache start, auto delete: false
23:05:39.154 T:29884    INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?)
23:05:39.154 T:29884   DEBUG: Thread FileCache 29884 terminating
23:05:39.154 T:29716    INFO: AddOnLog: Enigma2 Client: pvr.vuplus - enigma2::utilities::WebUtils::GetHttpXML Got result. Length: 8583
23:05:39.154 T:29716   DEBUG: AddOnLog: Enigma2 Client: pvr.vuplus - enigma2::Admin::LoadRecordingMarginSettings Margin Before: 0, Margin After: 0
23:05:39.154 T:29716   DEBUG: CAddonCallbacksAddon - KodiAPI::AddOn::CAddonCallbacksAddon::GetAddonSetting - add-on 'Enigma2 Client' requests setting 'host'
23:05:39.156 T:29716   DEBUG: CAddonSettings[pvr.vuplus]: loading setting definitions
23:05:39.157 T:29716   DEBUG: CAddonSettings[pvr.vuplus]: loading setting values
23:05:39.157 T:29716   DEBUG: CSettingsManager: requested setting (extracteventinfo) was not found.
23:05:39.157 T:29716   DEBUG: CAddonSettings[pvr.vuplus]: failed to find definition for setting extracteventinfo. Creating a setting on-the-fly...
23:05:39.157 T:29716   DEBUG: CSettingsManager: requested setting (onegroup) was not found.
23:05:39.157 T:29716   DEBUG: CAddonSettings[pvr.vuplus]: failed to find definition for setting onegroup. Creating a setting on-the-fly...
23:05:39.157 T:29716   DEBUG: CSettingsManager: requested setting (onlyonegroup) was not found.
23:05:39.157 T:29716   DEBUG: CAddonSettings[pvr.vuplus]: failed to find definition for setting onlyonegroup. Creating a setting on-the-fly...
23:05:39.157 T:29716   DEBUG: CSettingsManager: requested setting (setpowerstate) was not found.
23:05:39.157 T:29716   DEBUG: CAddonSettings[pvr.vuplus]: failed to find definition for setting setpowerstate. Creating a setting on-the-fly...
23:05:39.157 T:29716   DEBUG: CAddonCallbacksAddon - KodiAPI::AddOn::CAddonCallbacksAddon::GetAddonSetting - add-on 'Enigma2 Client' requests setting 'webport'
23:05:39.158 T:29716   DEBUG: CAddonSettings[pvr.vuplus]: loading setting definitions
23:05:39.159 T:29716   DEBUG: CAddonSettings[pvr.vuplus]: loading setting values
23:05:39.159 T:29716   DEBUG: CSettingsManager: requested setting (extracteventinfo) was not found.
23:05:39.159 T:29716   DEBUG: CAddonSettings[pvr.vuplus]: failed to find definition for setting extracteventinfo. Creating a setting on-the-fly...
23:05:39.159 T:29716   DEBUG: CSettingsManager: requested setting (onegroup) was not found.
23:05:39.159 T:29716   DEBUG: CAddonSettings[pvr.vuplus]: failed to find definition for setting onegroup. Creating a setting on-the-fly...
23:05:39.159 T:29716   DEBUG: CSettingsManager: requested setting (onlyonegroup) was not found.
23:05:39.159 T:29716   DEBUG: CAddonSettings[pvr.vuplus]: failed to find definition for setting onlyonegroup. Creating a setting on-the-fly...
23:05:39.159 T:29716   DEBUG: CSettingsManager: requested setting (setpowerstate) was not found.
23:05:39.159 T:29716   DEBUG: CAddonSettings[pvr.vuplus]: failed to find definition for setting setpowerstate. Creating a setting on-the-fly...
23:05:39.159 T:29716   DEBUG: CAddonCallbacksAddon - KodiAPI::AddOn::CAddonCallbacksAddon::GetAddonSetting - add-on 'Enigma2 Client' requests setting 'use_secure'
23:05:39.160 T:29716   DEBUG: CAddonSettings[pvr.vuplus]: loading setting definitions
23:05:39.161 T:29716   DEBUG: CAddonSettings[pvr.vuplus]: loading setting values
23:05:39.161 T:29716   DEBUG: CSettingsManager: requested setting (extracteventinfo) was not found.
23:05:39.161 T:29716   DEBUG: CAddonSettings[pvr.vuplus]: failed to find definition for setting extracteventinfo. Creating a setting on-the-fly...
23:05:39.161 T:29716   DEBUG: CSettingsManager: requested setting (onegroup) was not found.
23:05:39.161 T:29716   DEBUG: CAddonSettings[pvr.vuplus]: failed to find definition for setting onegroup. Creating a setting on-the-fly...
23:05:39.161 T:29716   DEBUG: CSettingsManager: requested setting (onlyonegroup) was not found.
23:05:39.161 T:29716   DEBUG: CAddonSettings[pvr.vuplus]: failed to find definition for setting onlyonegroup. Creating a setting on-the-fly...
23:05:39.161 T:29716   DEBUG: CSettingsManager: requested setting (setpowerstate) was not found.
23:05:39.161 T:29716   DEBUG: CAddonSettings[pvr.vuplus]: failed to find definition for setting setpowerstate. Creating a setting on-the-fly...
23:05:39.161 T:29716   DEBUG: CAddonCallbacksAddon - KodiAPI::AddOn::CAddonCallbacksAddon::GetAddonSetting - add-on 'Enigma2 Client' requests setting 'user'
23:05:39.162 T:29716   DEBUG: CAddonSettings[pvr.vuplus]: loading setting definitions
23:05:39.163 T:29716   DEBUG: CAddonSettings[pvr.vuplus]: loading setting values
23:05:39.163 T:29716   DEBUG: CSettingsManager: requested setting (extracteventinfo) was not found.

**Comment by phunkyfish** [comment]
Thanks,

Can you try backing up your settings.xml and then deleting it. It’s trying to load extracteventinfo twice which is strange.

If that works a copy of your settings.xml would be great. Please delete any user/passwords in the file first.

Was that the end of the log, I thought it would have reached: PVR Manager not started

**Comment by phunkyfish** [comment]
Great thanks. I’d say it’s something simple.

**Comment by M2k80** [comment]
https://pastebin.com/fMZ9b0v5
its the new debug log with deleted settings,xml
the log looks now complete different.

but i think its full of pve debug spam... xD
and i want to say i dont have raytek or something else enabled, but the log is full of it

**Comment by M2k80** [comment]
here is the old settings.xml and the new created one
<settings version="2">
    <setting id="autoconfig" default="true">false</setting>
    <setting id="enableautotimers" default="true">true</setting>
    <setting id="enablegenrepeattimers" default="true">true</setting>
    <setting id="enabletimeshift" default="true">0</setting>
    <setting id="extracteventinfo" default="true">false</setting>
    <setting id="host">192.168.2.21</setting>
    <setting id="iconpath" default="true"></setting>
    <setting id="keepfolders" default="true">false</setting>
    <setting id="logmissinggenremapping" default="true">false</setting>
    <setting id="numgenrepeattimers" default="true">1</setting>
    <setting id="onegroup">Kabel TV</setting>
    <setting id="onlinepicons" default="true">true</setting>
    <setting id="onlycurrent" default="true">false</setting>
    <setting id="onlyonegroup" default="true">false</setting>
    <setting id="pass" default="true"></setting>
    <setting id="prependoutline" default="true">0</setting>
    <setting id="readtimeout" default="true">0</setting>
    <setting id="recordingpath" default="true"></setting>
    <setting id="setpowerstate" default="true">false</setting>
    <setting id="streamport" default="true">8001</setting>
    <setting id="streamreadchunksize" default="true">0</setting>
    <setting id="timerlistcleanup" default="true">false</setting>
    <setting id="timeshiftbufferpath" default="true"></setting>
    <setting id="updateint" default="true">2</setting>
    <setting id="use_secure" default="true">false</setting>
    <setting id="usepiconseuformat" default="true">false</setting>
    <setting id="user" default="true"></setting>
    <setting id="webport" default="true">80</setting>
    <setting id="zap">true</setting>
</settings>

and the new one
<settings version="2">
    <setting id="autoconfig" default="true">false</setting>
    <setting id="enableautotimers" default="true">true</setting>
    <setting id="enablegenrepeattimers" default="true">true</setting>
    <setting id="enabletimeshift" default="true">0</setting>
    <setting id="extractshowinfoenabled" default="true">false</setting>
    <setting id="extractshowinfofile" default="true">special://userdata/addon_data/pvr.vuplus/showInfo/English-ShowInfo.xml</setting>
    <setting id="genreidmapenabled" default="true">false</setting>
    <setting id="genreidmapfile" default="true">special://userdata/addon_data/pvr.vuplus/genres/genreIdMappings/Sky-UK.xml</setting>
    <setting id="host">192.168.2.21</setting>
    <setting id="iconpath" default="true"></setting>
    <setting id="keepfolders" default="true">false</setting>
    <setting id="logmissinggenremapping" default="true">false</setting>
    <setting id="numgenrepeattimers" default="true">1</setting>
    <setting id="oneradiogroup" default="true"></setting>
    <setting id="onetvgroup" default="true"></setting>
    <setting id="onlinepicons" default="true">true</setting>
    <setting id="onlycurrent" default="true">false</setting>
    <setting id="pass" default="true"></setting>
    <setting id="powerstatemode" default="true">0</setting>
    <setting id="prependoutline" default="true">0</setting>
    <setting id="radiofavouritesmode" default="true">0</setting>
    <setting id="radiogroupmode" default="true">2</setting>
    <setting id="readtimeout" default="true">0</setting>
    <setting id="recordingpath" default="true"></setting>
    <setting id="rytecgenretextmapenabled" default="true">false</setting>
    <setting id="rytecgenretextmapfile" default="true">special://userdata/addon_data/pvr.vuplus/genres/genreRytecTextMappings/Rytec-UK-Ireland.xml</setting>
    <setting id="streamport" default="true">8001</setting>
    <setting id="streamreadchunksize" default="true">0</setting>
    <setting id="timerlistcleanup" default="true">false</setting>
    <setting id="timeshiftbufferpath" default="true"></setting>
    <setting id="tvfavouritesmode" default="true">0</setting>
    <setting id="tvgroupmode" default="true">0</setting>
    <setting id="updateint" default="true">2</setting>
    <setting id="updatemode" default="true">0</setting>
    <setting id="use_login_stream" default="true">false</setting>
    <setting id="use_secure" default="true">false</setting>
    <setting id="use_secure_stream" default="true">false</setting>
    <setting id="usepiconseuformat" default="true">false</setting>
    <setting id="user" default="true"></setting>
    <setting id="webport" default="true">80</setting>
    <setting id="zap">true</setting>
</settings>

just a short question.
shouldnt the update of the plugin work without deleting the settings.xml?

**Comment by phunkyfish** [comment]
What's strange is it just crashes here:

23:31:32.852 T:16352    INFO: AddOnLog: Enigma2 Client: pvr.vuplus - enigma2::utilities::WebUtils::GetHttpXML Open webAPI with URL: 'http://192.168.2.21:80/web/getservices'
23:31:32.852 T:16352   DEBUG: CFileCache::Open - opening <web/getservices> using cache
23:31:32.853 T:16352   DEBUG: CurlFile::Open(0x207fce34e20) http://192.168.2.21:80/web/getservices
23:31:32.879 T:29060   DEBUG: Thread FileCache start, auto delete: false
23:31:32.879 T:29060    INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?)
23:31:32.879 T:29060   DEBUG: Thread FileCache 29060 terminating
23:31:32.879 T:16352    INFO: AddOnLog: Enigma2 Client: pvr.vuplus - enigma2::utilities::WebUtils::GetHttpXML Got result. Length: 847
23:31:32.879 T:16352   ERROR: CJobWorker::Process error processing job pvr-startup

Can you send me the attach the output of: http://192.168.1.201/web/getservices

**Comment by phunkyfish** [comment]
You don't have rytec enabled, the addon loads the default config files each boot.

**Comment by phunkyfish** [comment]
Which image are you using?

**Comment by phunkyfish** [comment]
BTW the releases are tagged so you should be able to pull the previous version to revert yourself locally.

**Comment by M2k80** [comment]
I am using latest openvix

**Comment by phunkyfish** [comment]
Ok, so am I. I will test with both of your settings files this evening after work. I test with both my current and a new settings file for each release so not sure what is happening yet.

**Comment by ksooo** [comment]
> 23:31:32.879 T:16352 ERROR: CJobWorker::Process error processing job pvr-startup

 This most probably means the addon crashes during processing of ADDON_Create. No addon => no pvr startup :-(

**Comment by phunkyfish** [comment]
Yes, my thought also.

**Comment by M2k80** [comment]
<e2servicelist>
<e2service>
<e2servicereference>
1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.ec_kabel_tv.tv" ORDER BY bouquet
</e2servicereference>
<e2servicename>Kabel TV</e2servicename>
</e2service>
<e2service>
<e2servicereference>
1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.ec_sky_kabel.tv" ORDER BY bouquet
</e2servicereference>
<e2servicename>Sky Kabel</e2servicename>
</e2service>
<e2service>
<e2servicereference>
1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.favourites.tv" ORDER BY bouquet
</e2servicereference>
<e2servicename>Sky HD Kabel</e2servicename>
</e2service>
<e2service>
<e2servicereference>
1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.ec_sport_kabel.tv" ORDER BY bouquet
</e2servicereference>
<e2servicename>Sport Kabel</e2servicename>
</e2service>
</e2servicelist>

**Comment by xquewx** [comment]
I had the same problem on Android TV (Shield) and needed to change settings to load favorites only. After that, startup was successful.

My /web/getservices:
``` xml
<e2servicelist>
	<e2service>
		<e2servicereference>
1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.favourites.tv" ORDER BY bouquet
		</e2servicereference>
		<e2servicename>Fav</e2servicename>
	</e2service>
	<e2service>
		<e2servicereference>
1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.vti_192_004.tv" ORDER BY bouquet
		</e2servicereference>
		<e2servicename>Sky HD</e2servicename>
	</e2service>
	<e2service>
		<e2servicereference>
1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.vti_192_005.tv" ORDER BY bouquet
		</e2servicereference>
		<e2servicename>Sky Sport HD</e2servicename>
	</e2service>
	<e2service>
		<e2servicereference>
1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.orf__tv_.tv" ORDER BY bouquet
		</e2servicereference>
		<e2servicename>ORF</e2servicename>
	</e2service>
</e2servicelist>
```

**Comment by phunkyfish** [comment]
Thanks for the data MK, I found the issue. Used a placeholder comparison function and never replaced with proper version. Preparing PR now

**Comment by Qlink84** [comment]
Same Problem here. Pvr Manager does not start. Tried every different combination of settings without success. Heres my log https://paste.kodi.tv/biyaxuquju

**Comment by M2k80** [comment]
a question for the rytek things, that are now loaded on every boot...
Is that really necessary? i am from germany and dont really care about sky uk or any other non german content. i just ask myself, is it really needed for all?

**Comment by phunkyfish** [comment]
@Qlink84 can you post the output of https://192.168.222.15:80/web/deviceinfo please? I want to confirm something.

**Comment by phunkyfish** [comment]
They were always loaded on every boot since the feature was written. It's a bit of work to change so I'll look at it after this fix is out.

**Comment by phunkyfish** [comment]
@Qlink84 you are supposed to be using SSL correct?

**Comment by Qlink84** [comment]
`<e2deviceinfo>
<e2oeversion>OE-Alliance 3.4</e2oeversion>
<e2enigmaversion>2017-03-02</e2enigmaversion>
<e2distroversion>openatv</e2distroversion>
<e2imageversion>5.3.0</e2imageversion>
<e2driverdate>20170123</e2driverdate>
<e2webifversion>OWIF 1.2.1</e2webifversion>
<e2fpversion>0</e2fpversion>
<e2manufacturer>Vu+</e2manufacturer>
<e2devicename>Solo4K</e2devicename>
<e2boxtype>vusolo4k</e2boxtype>
<e2machinebuild>vusolo4k</e2machinebuild>
<e2chipset>7376</e2chipset>
<e2totalmemory>2067516 kB</e2totalmemory>
<e2freememory>795104 kB</e2freememory>
<e2frontends>
<e2frontend>
<e2name>Tuner A</e2name>
<e2model>Vuplus DVB-S NIM(7376 FBC) (DVB-S2)</e2model>
</e2frontend>
<e2frontend>
<e2name>Tuner B</e2name>
<e2model>Vuplus DVB-S NIM(7376 FBC) (DVB-S2)</e2model>
</e2frontend>
<e2frontend>
<e2name>Tuner C</e2name>
<e2model>Vuplus DVB-S NIM(7376 FBC) (DVB-S2)</e2model>
</e2frontend>
<e2frontend>
<e2name>Tuner D</e2name>
<e2model>Vuplus DVB-S NIM(7376 FBC) (DVB-S2)</e2model>
</e2frontend>
<e2frontend>
<e2name>Tuner E</e2name>
<e2model>Vuplus DVB-S NIM(7376 FBC) (DVB-S2)</e2model>
</e2frontend>
<e2frontend>
<e2name>Tuner F</e2name>
<e2model>Vuplus DVB-S NIM(7376 FBC) (DVB-S2)</e2model>
</e2frontend>
<e2frontend>
<e2name>Tuner G</e2name>
<e2model>Vuplus DVB-S NIM(7376 FBC) (DVB-S2)</e2model>
</e2frontend>
<e2frontend>
<e2name>Tuner H</e2name>
<e2model>Vuplus DVB-S NIM(7376 FBC) (DVB-S2)</e2model>
</e2frontend>
</e2frontends>
<e2network>
<e2interface>
<e2name>eth0</e2name>
<e2mac>00:1d:ec:0b:f9:69</e2mac>
<e2dhcp>False</e2dhcp>
<e2ip>192.168.222.15</e2ip>
<e2gateway>192.168.222.254</e2gateway>
<e2netmask>255.255.255.0</e2netmask>
</e2interface>
</e2network>
<e2hdds>
<e2hdd>
<e2model>ATA(ST98823AS)</e2model>
<e2capacity>74.5 GB</e2capacity>
<e2free>59.6 GB</e2free>
</e2hdd>
</e2hdds>
</e2deviceinfo>`

**Comment by Qlink84** [comment]
no i'm using http

**Comment by phunkyfish** [comment]
Your log says https

**Comment by Qlink84** [comment]
because i played around with settings. it doesnt matter if i set https enable or disable. problem is the same

**Comment by M2k80** [comment]
@phunkyfish 
> They were always loaded on every boot since the feature was written. It's a bit of work to change so I'll look at it after this fix is out.

maybe you can add rytek parts for german tv too?

my thought is only, why should allways loaded things everytime when they are not used.
if you think its needed, like it is now, i am fine with it

**Comment by phunkyfish** [comment]
@Qlink84 But can you post a debug log where https is disabled please?

**Comment by Qlink84** [comment]
here's another log with https disabled: https://paste.kodi.tv/isegeminap.kodi

**Comment by phunkyfish** [comment]
Way ahead of me

**Comment by phunkyfish** [comment]
What I need is a debug log though, enabled debug logging in kodi settings, restart and then post the log, thanks!

**Comment by phunkyfish** [comment]
@M2k80 Rytec can be used for any language, as can the mappers. Users can also customise what is there, the easiest way to implement this was to provide defaults rather than trying providing options for disabled and enabled plus a filename. The setting screen is already pretty full.

**Comment by Qlink84** [comment]
here you are: https://paste.kodi.tv/adebefujis.kodi

**Comment by phunkyfish** [comment]
@Qlink84 In the addon settings on the channels tab can you change the the TV bouquet fetch mode to All bouquets and post another debug log?

**Comment by M2k80** [comment]
this log looks like mine with the old settings.xml - it seems settings.xml will not actualized after the update.

i think you dont need much more settings on the screen, only the option, choose language, maybe english, german, etc. and the plugin chooses automaticly the right content.
maybe a thing for sometime in the future

**Comment by phunkyfish** [comment]
Ok, I'll create the PR and I can check your log tomorrow and always update it if there is a further issue

**Comment by M2k80** [comment]
but for information, in my old settings was only changed the ip and zap before stream, like in the new one..all other settings are on default. you have both xml files

**Comment by M2k80** [comment]
for the future, it maybe help, if you would dont merge a mega big PR and instead making more smaller single PRs. i think we could easier find a resolution when we can switch between the versions.
and you could push faster features and bugfixes.
pls dont misunderstand me, its clearly your choice how the way is go, its just a thought. 
and your work here is great. thx

**Comment by phunkyfish** [comment]
There is a fair reason, this is the busiest time of the year in my job and I was trying to get all the Leia perf changes and fixes in before launch when I still had time. Usually I would make smaller changes but time didn't allow it!

The cause of the issue was even on my Todo list I just missed it before the commit and it just so happened that due the length of the group names on my STB it did not effect me. Perfect storm ;)

**Comment by M2k80** [comment]
in german, i would say "Hunters and collectors". a typical man´s thing. haha 

but good you found the problem so fast and its hopefully fixed.

good night

**Comment by phunkyfish** [comment]
For anyone interested, the issue was caused by group names less that 12 characters long the radio groups feature excludes separators so if all your group names are less that 12 characters long it load 0 groups and addon startup would fail.
