### ISSUE TITLE
Channel Group Member Order not preserved

### ISSUE THREAD

**Issue by dellas60** [kodi-pvr/pvr.vuplus#141]
With 3.15.1 channels order is not same with backend.

**Comment by phunkyfish** [comment]
How channels are stored has changed since 3.15.x. So you may need to clear all your channel and group data. You can do this by clearing data from the main pvr settings.

If that doesn’t work let me know.

**Comment by phunkyfish** [comment]
Actually I think this is a bug, my provider order not not differ between main bouquets and sub bouquets so you'll need to test the fix in 3.15.2
