### ISSUE TITLE
2-3sec freeze when opening EPG or menu or pressing ESC while watching live TV

### ISSUE THREAD

**Issue by Qlink84** [kodi-pvr/pvr.vuplus#144]
i'm using v3.15.1 on my shield with latest Leia RC1 and 1 experience 2-3sec freeze when opening EPG or menu or pressing ESC while watching live TV.
After this short freeze EPG or menu opens up and live tv continues in background.
when i press info button while watching live TV this freeze problem doesn't occur.
i have a vu+ 4K with openATV image.

**Comment by phunkyfish** [comment]
I don’t see this on Mac or LibreELEC on Intel.

I trust this is happening after the EPG has fully loaded?

**Comment by Qlink84** [comment]
yeah, it happens every time. Even after watching more than 1 hour. And not only for EPG but also for kodi menu and ESC button.
2-3 sec freeze + audio gone for this period and then Live TV kicks back in and plays normally.

**Comment by phunkyfish** [comment]
Have a look at this:

https://github.com/xbmc/xbmc/issues/14828#issuecomment-441783762

**Comment by phunkyfish** [comment]
May or may not be related

**Comment by peak3d** [comment]
@phunkyfish will most likely not related. As long video playback is processed in main (GUI) thread, there will always be issues like you described. But there is work in progress to solve this.

**Comment by phunkyfish** [comment]
Thanks @peak3d

**Comment by phunkyfish** [comment]
@Qlink84 is this still occurring?

**Comment by Qlink84** [comment]
unfortunately yes. nothing has really changed. i've tried the leia 18.2 nightly from yesterday, but still the same behavior :(

**Comment by phunkyfish** [comment]
Have you tried a different Enimga2 image?

Like OpenVix, they have good support for VU+. Would be worth a try.

**Comment by phunkyfish** [comment]
I remember an issue from a while back with some perf issues on OpenATV. I could be wrong.

**Comment by Qlink84** [comment]
i don't think it's enigma 2 image related... the problem only occurs on my nvidia shield. it works perfectly fine on my other kodi devices... windows laptop, android cellphone, windows pc... so i guess it's a shield issue...

**Comment by phunkyfish** [comment]
Ok, I guess we wait for the gui thread improvements so.

**Comment by Qlink84** [comment]
why do you think it's related to gui threads ? do you know if there is happening any progress ? is there a place where i can watch gui thread improvements changes ?

**Comment by phunkyfish** [comment]
Simply because I can’t think of anything else. Afraid I don’t know of any progress to date nor where to check.

**Comment by peak3d** [comment]
@phunkyfish , @Ql# You'll most probably not get any reasonable support if you don't provide kodi debug log.
B.t.w.: have you tried how it behaves if you disable MediaCodec h/w decode ?

**Comment by phunkyfish** [comment]
Sorry @peak3d, I had assumed the user had supplied one.

Step One: debug log

**Comment by peak3d** [comment]
Pls. try disabling  h/w decode first

**Comment by Qlink84** [comment]
i did provide a full debug log here(3rd post): https://github.com/xbmc/xbmc/issues/15096

no have not tried disabling h/w decode. will try that when i'm @home from work ...

**Comment by phunkyfish** [comment]
After this please post the settings.xml for the addon and also check that you have prevent EPG updates during playback in Kodi PVR settings.

**Comment by peak3d** [comment]
@Qlink84 pls. simply provide a debug log here instead hunting me into dead links :-)

**Comment by Qlink84** [comment]
hmm seems like the log has been deleted ? do the logs uploaded with kodi log uploader have an expiry date ? strange ...
anyway, i will upload another full debug log when i'm @home and will also post settings.xml

**Comment by phunkyfish** [comment]
I’d say they don’t last too long. you can create a public gist on GitHub if you need it to live for longer.

**Comment by Qlink84** [comment]
disabling h/w decode doesn't solve the problem :(

here's another full debug log: http://paste.kodi.tv/somuhocane.kodi

and i don't have a settings.xml in Android/data/org.xbmc.kodi/files/.kodi/userdata/

**Comment by phunkyfish** [comment]
Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/pvr.vuplus

**Comment by phunkyfish** [comment]
Can you try two things:

1 - Disable signal quality in the Kodi PVR settings
2 - upgrade OpenWebIf to a more current version.

**Comment by Qlink84** [comment]
oh thx4info

here is settings.xml
`<settings version="2">
    <setting id="autoconfig">true</setting>
    <setting id="enableautotimers" default="true">true</setting>
    <setting id="enablegenrepeattimers" default="true">true</setting>
    <setting id="enabletimeshift">2</setting>
    <setting id="epgdelayperchannel" default="true">0</setting>
    <setting id="extractshowinfoenabled" default="true">false</setting>
    <setting id="extractshowinfofile" default="true">special://userdata/addon_data/pvr.vuplus/showInfo/English-ShowInfo.xml</setting>
    <setting id="genreidmapenabled" default="true">false</setting>
    <setting id="genreidmapfile" default="true">special://userdata/addon_data/pvr.vuplus/genres/genreIdMappings/Sky-UK.xml</setting>
    <setting id="host">192.168.222.15</setting>
    <setting id="iconpath" default="true"></setting>
    <setting id="keepfolders" default="true">false</setting>
    <setting id="logmissinggenremapping" default="true">false</setting>
    <setting id="numgenrepeattimers" default="true">1</setting>
    <setting id="onegroup" default="true">Gerald</setting>
    <setting id="oneradiogroup" default="true"></setting>
    <setting id="onetvgroup">Gerald</setting>
    <setting id="onlinepicons" default="true">true</setting>
    <setting id="onlycurrent" default="true">false</setting>
    <setting id="onlyonegroup" default="true">true</setting>
    <setting id="pass" default="true"></setting>
    <setting id="powerstatemode" default="true">0</setting>
    <setting id="prependoutline" default="true">0</setting>
    <setting id="radiofavouritesmode" default="true">0</setting>
    <setting id="radiogroupmode" default="true">2</setting>
    <setting id="readtimeout" default="true">0</setting>
    <setting id="recordingpath" default="true"></setting>
    <setting id="rytecgenretextmapenabled" default="true">false</setting>
    <setting id="rytecgenretextmapfile" default="true">special://userdata/addon_data/pvr.vuplus/genres/genreRytecTextMappings/Rytec-UK-Ireland.xml</setting>
    <setting id="setpowerstate" default="true">false</setting>
    <setting id="streamport" default="true">8001</setting>
    <setting id="streamreadchunksize" default="true">0</setting>
    <setting id="timerlistcleanup">true</setting>
    <setting id="timeshiftbufferpath">/storage/emulated/0/Download/</setting>
    <setting id="tracedebug" default="true">false</setting>
    <setting id="tvfavouritesmode" default="true">0</setting>
    <setting id="tvgroupmode">1</setting>
    <setting id="updateint" default="true">2</setting>
    <setting id="updatemode" default="true">0</setting>
    <setting id="use_login_stream" default="true">false</setting>
    <setting id="use_secure" default="true">false</setting>
    <setting id="use_secure_stream" default="true">false</setting>
    <setting id="useopenwebifpiconpath" default="true">false</setting>
    <setting id="usepiconseuformat" default="true">false</setting>
    <setting id="user" default="true"></setting>
    <setting id="webport" default="true">80</setting>
    <setting id="zap" default="true">false</setting>
</settings>
`

**Comment by phunkyfish** [comment]
What version of openatv are you running?

**Comment by Qlink84** [comment]
OE-System: | OE-Alliance 3.4
-- | --
Firmware-Version: | OpenATV 5.3.0 (2017-03-02)
Kernel / Treiber: | 3.14.28 / 20170123

**Comment by phunkyfish** [comment]
Make that 3 things to try:

1 - Disable signal quality in the Kodi PVR settings
2 - Upgrade to latest OpenATV 6.2
3 - upgrade OpenWebIf to a more current version after step 2

**Comment by Qlink84** [comment]
disabling signal quality doesn't help
deleting settings.xml doesn't help
because the problem only occurs on my shield(i use 4 different kodi devices), i don't think it's enigma2, image or webif related ...

**Comment by phunkyfish** [comment]
My thought process there was that if there was any modification of the video container that may have caused a video issue on the shield. It’s a stretch I know.

What are the other devices? Any of them android?

**Comment by Qlink84** [comment]
yes, 2 android phones... 1x OnePlus 6 and 1x Huawei P10 Lite, on both cellphones all is working smooth without any freezes ... the other devices are windows notebooks and pcs

**Comment by ksooo** [comment]
I wonder how one can be so obsessed by a 2-3 sec freeze. We have so many other serious problems. ;-) 

Seriously, you have two issues open for this problem - one for pvr.vuplus, one for xbmc. Maybe one is sufficient?

**Comment by Qlink84** [comment]
i have two issues open, because no one knows what's the cause of this issue ...
obsessed ??? are you serious ? did you have a bad day or something like that ?
i just want to highlight that there is an existing problem with current kodi version and want to help you guys to fix this problem ... shouldn't it be the main goal to make kodi experience as great as possible ?
most devs are happy if there are users who report issues, so they can make their software better ... i guess you are not one of those devs ... i hope there are other devs reading this issue, who are more interested in fixing problems than you ...

**Comment by ksooo** [comment]
> i hope there are other devs reading this issue, who are more interested in fixing problems than you ...

 :-) I'm widely known to ignore what users report and are interested in.

**Comment by peak3d** [comment]
Pls. don't continue this OT conversation, thx!

**Comment by ksooo** [comment]
Sure sure. I will shut up.

**Comment by peak3d** [comment]
@Qlink84 pls. enable video component debugging, and play the stream some seconds (and attach log)

**Comment by Qlink84** [comment]
here is the log with video component debugging enabled: http://paste.kodi.tv/ecequpubig.kodi

**Comment by peak3d** [comment]
@Qlink84 thx, now pls. enable a/v sync component debugging, too

**Comment by Qlink84** [comment]
here is the log with video component debugging + a/v sync component debugging enabled only: http://paste.kodi.tv/efukegijoh.kodi

**Comment by peak3d** [comment]
Sorry, component debug logging works only if debug logging is enabled, too

**Comment by Qlink84** [comment]
didn't know that, here is another one with debug logging enabled: https://paste.kodi.tv/dosivigiqe.kodi

**Comment by peak3d** [comment]
@Qlink84 from log it seems at least not wrong what we do, you know, that you have refresh rate switching on and before the movie starts there is a switch from 60 -> 50 hz? It takes quite long until the box receives the HDMI event, not sure if you have an AVR in the middle or if there is something other wrong. On my shield between switch and HDMI plug event its ~ 0.5 sec, on your system 3.5.

Long story short, refresh rate switches is hard to track, there are buffer flushes for audio, seek and so on to get thinngs work well. No wonder that it works well on your phone, you will not have refresh rate switching on there.

**Comment by Qlink84** [comment]
i guess thats because in menu delay after refresh rate switching is set to 3 secs ...

**Comment by peak3d** [comment]
Tbh. one cannot compare this with your android phone.
If we want to compare odd video start, you should disable refreshrate switching, change your monitor to 50hz and we can go. All other makes our both lifes harder as needed

**Comment by Qlink84** [comment]
WTF ? i disabled refresh switching and changed to 50hz, now the 2-3sec freeze problem when opening EPG or menu or switching to fullscreen mode is gone !
That fixed the problem !
i'm just curious why refreshrate switch is now causing these problems... with early beta 18.0 nightly these freezes did not occur, altough i had exact the same settings (refresh rate switching on and 60hz)
anyway thank you so much peak3d for guiding me to the solution

**Comment by peak3d** [comment]
@Qlink84 we had to make some changes because of audio issues while refreshrate switching. unfortunately android does not inform application, when refreshrate switching is done. Amazon implemented owh solutions in driver to manage it, but this is nothing we'll do in kodi.

There is one benefit of the changed logic: normal streams start now from start and do not miss the first couble of seconds.

**Comment by Qlink84** [comment]
ah i see ... any signs on the horizon, that android will support this "application informing thing" in the future ?

**Comment by peak3d** [comment]
I'm sure it will come at any day, but from what I read nothing is in the pipeline so far.

**Comment by phunkyfish** [comment]
Great outcome guys. 

Feel free to close both issues once you are ready @Qlink84
