### ISSUE TITLE
Enigma2 client 3.15.1.2 doesnt work with OpenPLi 0.7-rc 

### ISSUE THREAD

**Issue by Dinth** [kodi-pvr/pvr.vuplus#146]
### Describe the bug
Since i updated my sat box to OpenPLi 0.7-rc (build 20181219) yesterday it's not possible to enable Enigma2 client in Kodi. Whenever i restart Kodi or manually go to addons list and disable/re-enable Enigma2 addon im getting "Add-on couldn't be loaded. An unknown error has occured" error. 

## Expected Behavior

Addon should start fetching current channel list.

## Actual Behavior

An error "Add-on couldn't be loaded. An unknown error has occured" appears. 

### Debuglog

```
20:06:47.836 T:139678803232512  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - Open - VU+ Addon Configuration options
20:06:47.836 T:139678803232512  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - Open - Hostname: '192.168.1.175'
20:06:47.836 T:139678803232512  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - Open - WebPort: '80'
20:06:47.836 T:139678803232512  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - Open - StreamPort: '8001'
20:06:47.836 T:139678803232512  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - Open Use HTTPS: 'false'
20:06:47.989 T:139678803232512  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - LoadDeviceInfo - DeviceInfo
20:06:47.989 T:139678803232512  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - LoadDeviceInfo - E2EnigmaVersion: 2018-12-19-rc
20:06:47.989 T:139678803232512  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - LoadDeviceInfo - E2ImageVersion: 7.0-rc
20:06:47.989 T:139678803232512  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - LoadDeviceInfo - E2DistroVersion: openpli
20:06:47.989 T:139678803232512  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - LoadDeviceInfo - E2WebIfVersion: OWIF 1.3.5
20:06:47.989 T:139678803232512  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - LoadDeviceInfo - E2DeviceName: 1
20:06:48.473 T:139678803232512   ERROR: ADDON: Dll Enigma2 Client - Client returned bad status (1) from Create and is not usable
20:06:49.959 T:139678803232512   ERROR: UpdateAddons: Failed to create add-on Enigma2 Client, status = 1

```

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ x] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 8.90.009 Generic x86_64
 - Kodi version: Kodi 18.0-RC2
 - Enigma2 client version: 3.15.1.2 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by phunkyfish** [comment]
Can you please include a full debug log?

So enable debug in kodi, restart and once back up pastebinit the URL here.

Then we can see what the issue might be. Thanks!

**Comment by phunkyfish** [comment]
Also, would be good to know what change were included in the latest version of OpenPli.

This line looks strange: LoadDeviceInfo - E2DeviceName: 1

I would expect that to give your hardware name. May be a bug in OpenPli.

**Comment by phunkyfish** [comment]
I’m not sure this is your problem.

You need to create a debug log and attach a pastebin of it. The log above is just the standard log.

**Comment by phunkyfish** [comment]
You should enable debug logging in kodi and then restart. The attach the resulting log URL that pastbinit gives you.

**Comment by phunkyfish** [comment]
It’s trying to load both the “Favourites (TV)” bouquet and the “Favourites (Radio)” bouquet. Neither bouquet has any services so it’s failing (you need to have at least one channel). You should just enable All bouquets for TV and it should work.

**Comment by Dinth** [comment]
@phunkyfish 
Thank you, this seem to fix the issue.
Although it's not the most intuitive way of reporting such issue, i believe it would be better (more intuitive) if PVR would not show any error at all, just an empty channel list.

**Comment by phunkyfish** [comment]
Added #157 so logging is clear when there are no channels found

**Comment by phunkyfish** [comment]
@Dinth ideally there would be an easy way to show a message to the user on the UI, better logging will have to do currently. Allowing the user to use the interface with no channels is not possible without changing a substantial amount of code, not really worth the effort what will be a minor upside.

**Comment by Dinth** [comment]
Just a loose idea, but maybe plugin could create a single dummy channel called "No channels available" as a workaround?

**Comment by phunkyfish** [comment]
Araid that wouldn’t work. Channel is the base structure that everything is built on. So if it’s not a real channel that relates to the other features nothing works.
