### ISSUE TITLE
In 3.15.2 WebIf that is not OpenWebIf does not support auto timer API - Addon won't load Newnigma2 image

### ISSUE THREAD

**Issue by Randy203** [kodi-pvr/pvr.vuplus#151]
3.15.2 dont load/work on old DM8000 with Kodi 18 RC03 on Fire TV Stick 4k

On my old DM8000 the "e2distroversion" string dont exist in webinterface:

<e2abouts>
<e2about>
<e2enigmaversion>2016-06-16-tarball</e2enigmaversion>
<e2imageversion>Newnigma2-daily 2018-12-14</e2imageversion>
<e2webifversion>1.7.5</e2webifversion>
<e2fpversion>7</e2fpversion>
<e2model>dm8000</e2model>
<e2lanmac>6c:fd:b9:4b:26:fc</e2lanmac>
<e2landhcp>False</e2landhcp>
<e2lanip>192.168.0.23</e2lanip>
<e2lanmask>255.255.255.0</e2lanmask>
<e2langw>192.168.0.1</e2langw>

Kodi.log output:

AddOnLog: Enigma2 Client: pvr.vuplus - LoadDeviceInfo - E2DeviceName: dm8000
08:47:30.286 T:18446744071592474912   ERROR: CCurlFile::Open failed with code 404 for http://192.168.0.22:80/autotimer/get:
08:47:30.287 T:18446744071592474912   ERROR: Open - failed to open source <http://USERNAME:PASSWORD@192.168.0.22:80/autotimer/get>
08:47:30.896 T:18446744071592474912   ERROR: ADDON: Dll Enigma2 Client - Client returned bad status (1) from Create and is not usable
08:47:32.109 T:18446744071592474912   ERROR: UpdateAddons: Failed to create add-on Enigma2 Client, status = 1

Under Kodi 17.6 with the old VU+ Plugin works.

THX for Help !!!

**Comment by phunkyfish** [comment]
Have you tried to access this URL in a browser: http://192.168.0.22/autotimer/get

**Comment by Randy203** [comment]
Here is die full debug log.
[kodi.log](https://github.com/kodi-pvr/pvr.vuplus/files/2705480/kodi.log)

The Error is:
Enigma2 client addon can not be loaded

**Comment by Randy203** [comment]
> Have you tried to access this URL in a browser: http://192.168.0.22/autotimer/get
> 
> You get a 404 on this URL which means it couldn't find it. This usually happens if it can't connect for some reason.

No. This is the ip of my Dreambox. Kodi itself is installed on a Fire TV. I access the Dreambox 8000 from Fire TV with Kodi and Enigma addon.

**Comment by phunkyfish** [comment]
I understand that. I think I know what the problem is.

Are you using a special dreambox image?

The addon assumes if you have version 1.3.0 of webif or later then it supports Autotimers.

But you have 1.7.5 and it’s not OpenWebIf so I assume you have an unusual image. I’ve never heard of newnigma2.

I can modify the auto timer version check to only allow Autotimers if it’s 1.3.x or higher and must be OpenWebIf.

**Comment by phunkyfish** [comment]
Or you could just install OpenWebIf and get auto timer support if you can’t wait for a fix.

**Comment by Randy203** [comment]
Ok. Thx for your Help!
I'm waiting for a fix!

**Comment by phunkyfish** [comment]
@Randy203 quick question. I was thinking of switching to the json API for calling enigma2. However you don't use OpenWebIf. What do you use for the web interface? Does it support a JSON endpoint (i.e. /api/ instead of /web/)?

Thanks

**Comment by phunkyfish** [comment]
If only the web api is available then this url should return a result in a browser:

http://your-ip/web/deviceinfo

If the JSON api is also available this will also work in a browser:

http://your-ip/api/deviceinfo

The results of both calls would be helpful.

Thanks in advance.

**Comment by Randy203** [comment]
<e2deviceinfo>

<e2enigmaversion>2016-06-16-tarball</e2enigmaversion>

<e2imageversion>Newnigma2-daily 2018-12-21</e2imageversion>

<e2webifversion>1.7.5</e2webifversion>

<e2fpversion>7</e2fpversion>

<e2devicename>dm8000</e2devicename>

<e2frontends>

<e2frontend>

<e2name>Tuner A</e2name>

<e2model>BCM4506 (internal) (DVB-S2)</e2model>

</e2frontend>

<e2frontend>

<e2name>Tuner B</e2name>

<e2model>BCM4506 (internal) (DVB-S2)</e2model>

</e2frontend>

<e2frontend>

<e2name>Tuner C</e2name>

<e2model>CXD1981 (DVB-C)</e2model>

</e2frontend>

<e2frontend>

<e2name>Tuner D</e2name>

<e2model>(leer)</e2model>

</e2frontend>

</e2frontends>

<e2network>

<e2interface>

<e2name>eth0</e2name>

<e2mac>00:09:34:1c:ce:b1</e2mac>

<e2dhcp>False</e2dhcp>

<e2ip>192.168.0.22</e2ip>

<e2gateway>192.168.0.1</e2gateway>

<e2netmask>255.255.255.0</e2netmask>

</e2interface>

</e2network>

<e2hdds>

<e2hdd>

<e2model>ATA-WDC WD20EURX-63T</e2model>

<e2capacity>2000.398 GB</e2capacity>

<e2free>983.592 GB</e2free>

</e2hdd>

<e2hdd>

<e2model>USB2.0-Flash Disk</e2model>

<e2capacity>1.993 GB</e2capacity>

<e2free>1.743 GB</e2free>

</e2hdd>

</e2hdds>

</e2deviceinfo>

**Comment by Randy203** [comment]
http://your-ip/api/deviceinfo

Is no works
