### ISSUE TITLE
Change startup issue log statements from Debug to Error

### ISSUE THREAD

**Issue by phunkyfish** [kodi-pvr/pvr.vuplus#157]
Many startup issues are not obvious from a standard log as they are debug only. Anything that causes the addon to fail to start should have an obvious Error Log statement.

**Comment by M2k80** [comment]
i think it would be a good idea, to put some of the plugin output to a special switch.
i think the logfile is already much spammed by the plugin.
if i make for example an debug log, 70% is from this plugin (like epg etc), that makes it confusing.
in the debug log options are already switches, maybe it would be good if we could enable huge logging for this plugin seperatly?

what do you think?

**Comment by phunkyfish** [comment]
I think that's a great idea. Let's move to a new issue. There is trace level in the logger that is unused.

If you can create the issue and lay out a plan I can look at implementing.

**Comment by phunkyfish** [comment]
@M2k80 moved you suggestion to #159
