### ISSUE TITLE
Plugin won't load channels after upgrade to 3.16.0

### ISSUE THREAD

**Issue by Allev8** [kodi-pvr/pvr.vuplus#161]
Hi

I'm using Kodi 18 rc4 on nvidia shield. Enigma2 with egami 8.1.2.
I'm stuck forever in loading at 0%.
Here is the log : 

https://paste.kodi.tv/buvexuboyu.kodi

Thank you for your job

**Comment by phunkyfish** [comment]
Can you put this URL in a browser and post the result?

```
http://192.168.1.96:80/api/getservices?provider=1&picon=1&sRef=1%3A7%3A1%3A0%3A0%3A0%3A0%3A0%3A0%3A0%3AFROM%20BOUQUET%20%22userbouquet%2Evh01%2Etv%22%20ORDER%20BY%20bouquet'
```

**Comment by phunkyfish** [comment]
Great, thanks, based on that I can add a fix, once 3.16.1 is available you
should be ok.

**Comment by phunkyfish** [comment]
As a workaround you could also try upgrading OpenWebIf to 1.3.5. Not sure
if that will fix it but may be quicker than waiting for the next release.

**Comment by phunkyfish** [comment]
Sorry, I had a typo in the URL. Can you try this one:

```
http://192.168.1.96:80/api/getservices?provider=1&picon=1&sRef=1%3A7%3A1%3A0%3A0%3A0%3A0%3A0%3A0%3A0%3AFROM%20BOUQUET%20%22userbouquet%2Evh01%2Etv%22%20ORDER%20BY%20bouquet
```

**Comment by Allev8** [comment]
Yes it works, now under services I can see channels.


services | […]
-- | --
pos | 100

**Comment by phunkyfish** [comment]
Any chance you could post the output using https://paste.kodi.tv ?

Github hides the content.

**Comment by Allev8** [comment]
Sure 

https://paste.kodi.tv/aqaduyoqap

**Comment by phunkyfish** [comment]
Perfect, thanks. Fix tested and working!
