### ISSUE TITLE
Windows build define a macro that forwards snprintf to _snprintf which breaks json.hpp

### ISSUE THREAD

**Issue by phunkyfish** [kodi-pvr/pvr.vuplus#162]
Because of this the resulting code std::_snprintf makes no sense and causes a build error.

Already reported in: https://github.com/nlohmann/json/issues/1408

To workaround I removed ```std::``` from the calls.

The Microsoft compiler used should have snprintf in the std namespace. Any idea where in the build system this macro that changes it? @ksooo @Rechi

**Comment by Rechi** [comment]
https://github.com/xbmc/platform/blob/2c8d36e/src/windows/os-types.h#L88-L90

**Comment by phunkyfish** [comment]
Ok, but snprintf is available since Visual Studio 2015. Does the windows build use an older compiler for windows?

**Comment by phunkyfish** [comment]
From the build output I see it uses Visual Studio 2017 which should be ok. But then it doesn't make sense why the macro takes effect:

```
#ifndef snprintf
#define snprintf _snprintf
#endif
```
As snprintf should be defined.

**Comment by Rechi** [comment]
`snprintf` is a function not a macro definition, so everything behaves as expected.

**Comment by phunkyfish** [comment]
Fixed by https://github.com/kodi-pvr/pvr.vuplus/pull/163
