### ISSUE TITLE
[FEATURE REQUEST] Reset Settings to default

### ISSUE THREAD

**Issue by M2k80** [kodi-pvr/pvr.vuplus#168]
it would be good, if we could complete reset the settings.xml to its default, to prevent debug spam of missing/old paramaters that dont exists anymore.
now, we can only reset a category to their defaults.

OR

but i think its more work.
after an update of the plugin, the plugin checks the settings.xml for invalid/old entrys and remove them automaticly

**Comment by phunkyfish** [comment]
I don’t think option one is possible. The problem with option 2 is it’s dangerous, text manipulation would be used and even a slight mistake and a users settings would be beyond repair.

**Comment by phunkyfish** [comment]
Let me think about it.

**Comment by phunkyfish** [comment]
You mean instructions for this in the readme file?

**Comment by M2k80** [comment]
you mean for  option1 ? no, i thought, this should happen, if click on reset settings to default button :)

**Comment by phunkyfish** [comment]
There is no facility within the PVR addon to do what you are proposing. What you can do is quite limited. The only way to modify the file is to read the file to a string. Run through it line by line deleting the lines you don’t want and then overwrite the resulting string back to the file.

This settings file would then be picked up on next reboot and this would work if they don’t change another setting before a reboot (cause then the file in memory gets written out). You can’t pop up dialogs or anything like that. You can queue notifications only.

**Comment by M2k80** [comment]
thank you,
i am sorry for late answer
