### ISSUE TITLE
GetStreamTimes returning incorrect values dues to time_t bing 32bit on ARM systems

### ISSUE THREAD

**Issue by phunkyfish** [kodi-pvr/pvr.vuplus#171]
Type is time_t instead of int64.

**Comment by weakfl** [comment]
@phunkyfish Does #170 fix the incorrect recording duration? If so, a `3.16.2-Leia` release would be greatly appreciated. Not being able to skip commercials is really annoying 😉

**Comment by phunkyfish** [comment]
Yes it does. Confirmed this morning. What device are you running on?

**Comment by weakfl** [comment]
AFTV 4K, so I'd need an armv7a (32bit) (test)build...

**Comment by phunkyfish** [comment]
Cool, so once the PR is approved you'll be able to get the next official nightly build.

**Comment by weakfl** [comment]
Awesome, thanks. I wasn't sure if the addons are included in the nightlies or are distributed idependently.

**Comment by phunkyfish** [comment]
On that I'm not sure as I only run Vanilla kodi for development. I use LibreElec the rest of the time (and they ship with LibreElec). So it may just appear in the addon repo, let me know if that's how it works ;)

FYI, the 3.17.0 release will have support for Recording EDLs, so if you can generate the EDL files you wouldn't even have to skip commericals, they could skip automatically. I currently have them generated on a remote server but finding a way to build comskip in Engima2 devices would be cool.

**Comment by weakfl** [comment]
> So it may just appear in the addon repo, let me know if that's how it works ;)

Will do :)

> FYI, the 3.17.0 release will have support for Recording EDLs, so if you can generate the EDL files you wouldn't even have to skip commericals, they could skip automatically. I currently have them generated on a remote server but finding a way to build comskip in Engima2 devices would be cool.

That sounds awesome. What hardware are you running comskip on?
I should probably run comskip on the NAS where my recordings are anyway, but I'm concerned if it has enough horsepower to process a h.264 recording in finite time 😂

**Comment by phunkyfish** [comment]
I currently have it on a very very old mac mini. Transferring the files to there and processing overnight is a bit cumbersome. In fairness it takes about 10 mins altogether. I havn't tried building it on my NAS yet. But I store my recordings on the Enigma2 device. Having it run there overnight would be cool. Wouldn't really matter how long it would take as there wouldn't be to many new recordings each night.

**Comment by weakfl** [comment]
I see, thanks. I'll just give [this](https://github.com/linuxserver/docker-comskip) comskip docker image (which supposedly works on qnap) a try and see how it goes.

**Comment by phunkyfish** [comment]
Cool, sure post back on how it goes, might be a solution for other users who store on a NAS

**Comment by weakfl** [comment]
@phunkyfish Thanks for merging, looking forward to the new version ;)

I noticed the version has been set to `3.6.13` in [addon.xml.in](https://github.com/kodi-pvr/pvr.vuplus/blob/master/pvr.vuplus/addon.xml.in) by 91fa48b1a43e08c5dd04bacb8a58ce846ac205ab though. Shouldn't it be `3.6.12`?

And can you tag/release the new version?

**Comment by phunkyfish** [comment]
It's 3.16.3 because the language files were updated after I merged.

**Comment by weakfl** [comment]
I noticed. Still looks wrong considering your merge commit came after the language update and that version `3.16.2` hasn't been released yet 😉

**Comment by ksooo** [comment]
@phunkyfish 

3.16.2 was a transifex update
your PR did not update the addon version number
meanwhile another transifex update came in, on top of your PR, which sets addon version number to 3.16.3

So, not correct, but not a big deal. Just put a tag 3.16.3 on current HEAD. Done.

**Comment by ksooo** [comment]
> I was hoping CI would be triggered by tagging a new release and the addon update would be available as soon as the build has finished. This doesn't seem to be the case however?

 That's the way it is supposed to work, yes. @Rechi right?

**Comment by Rechi** [comment]
At https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.vuplus/detail/3.16.2-Leia/1/pipeline, https://mirrors.kodi.tv/addons/leia/pvr.vuplus+android-aarch64/ and https://mirrors.kodi.tv/addons/leia/pvr.vuplus+android-armv7/all looks fine, if you know about and https://github.com/kodi-pvr/pvr.vuplus/commit/5a00fe9.
Are you aware that Kodi refreshes the repo only once every 24 hours?

**Comment by weakfl** [comment]
> Are you aware that Kodi refreshes the repo only once every 24 hours?

No, I wasn't. That's why I asked ;)

Thanks for the explanation @Rechi

**Comment by okriehn** [comment]
After updating to Kodi (18.0-RC5) on Linux ARM 32-bit with plugin version 3.16.2 still having wrong durations on recordings.

Any Idea on that?

**Comment by phunkyfish** [comment]
Can you provide a full debug log? https://kodi.wiki/view/Log_file/Easy

Also, if you could provide a sample recording, so the TS file and all the other files .cuts etc. I can test it locally.

**Comment by phunkyfish** [comment]
Your openwebif version is quite old.

**Comment by phunkyfish** [comment]
You can install a later OpenWebIf from here, it shoudn't require porting: https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/tree/gh-pages

But I don't think that's your problem.

Have you tried CoreElec or LibreElec?

**Comment by phunkyfish** [comment]
Or maybe it's CoreElec, let me double check. Too many devices ;)

**Comment by okriehn** [comment]
I already tried a newer openwebif version but get an python import error because of movielist...
Haven't tried *Elec.

**Comment by phunkyfish** [comment]
So if you install the beta2 of libreelec then you can upgrade to the later nightly from here:

https://forum.kodi.tv/showthread.php?tid=298461&page=475

 The #0116 build is what I'm running. You want the Rpi2 build (it's for both rpi2/3).

**Comment by okriehn** [comment]
> Your openwebif version is not too old. It's should be ok.

So i will try to update this after you can't see anything in the log i'll provide later. Is that ok for you?

**Comment by phunkyfish** [comment]
Sure

**Comment by okriehn** [comment]
Here is the logfile: https://pastebin.com/k08MeFjW

**Comment by phunkyfish** [comment]
Is the show Paw Patrol and almost 53 minutes long?

**Comment by phunkyfish** [comment]
I don't see anything wrong in your log.

On the version of OpenWebIf you use the only thing that wouldn't work would be autotimers. But the rest of the functionality would be the same. But that won't be causing the issue that you are having.

I think you should try LibreElec since they directly support rpi3. Also I know that works for sure as I have the same device.

So if you install the beta2 of LibreElec from http://libreelec.tv and then you can upgrade to the later nightly from here: https://forum.kodi.tv/showthread.php?tid=298461&page=475

The #116 build is what I'm running. You want the Rpi2 build (it's for both rpi2/3).

**Comment by okriehn** [comment]
From what i understand the osmc does support the pi too. But just to be sure it is worth a try to test libreelec.
But first i want to test an older version from the pvr-plugin. How can i downgrade to the #116 version that you are running?

**Comment by okriehn** [comment]
Tried with libreelec (8.2.5) and it works. But i prefer osmc and would love to see it running there.

**Comment by weakfl** [comment]
@phunkyfish 32bit is not an issue, it's working fine on vanilla kodi leia rc5 armv7/32bit.

It's even working with recordings which are still in progress. This hasn't worked for ages and i really appreciate it 😉

**Comment by okriehn** [comment]
> If that works then we know the issue is with 32bit kodi or OSMC.

Updated to the mentioned version 116 and it works. But i don't understand why this could be a problem with the 32bit kodi? The pi is 32bit, so the kodi should be 32bit in both, libreelec and osmc.

**Comment by phunkyfish** [comment]
The pi is 64bit.

**Comment by phunkyfish** [comment]
Sorry @okriehn I deleted your post in error.

**Comment by phunkyfish** [comment]
I thought you were on a Rpi3?

**Comment by phunkyfish** [comment]
An Rpi3 can run in 32bit mode. So it's reports as that.

**Comment by phunkyfish** [comment]
@okriehn can you provide a debug log from the latest LibreElec nightly?

**Comment by phunkyfish** [comment]
@weakfl you're welcome!

**Comment by phunkyfish** [comment]
@okriehn if it works on 32bit vanilla kodi then it has to be an issue with OSMC. You could try posting the issue in their forum/github.

**Comment by phunkyfish** [comment]
Just wanted to confirm what LibreElec reported your CPU as.

**Comment by okriehn** [comment]
Ok, here is the relevant snippet:

16:10:03.634 T:1936895520  NOTICE: Starting Kodi (18.0-RC5 Git:6733f37). Platform: Linux ARM 32-bit
16:10:03.635 T:1936895520  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
16:10:03.635 T:1936895520  NOTICE: Kodi compiled 2019-01-16 by GCC 8.2.0 for Linux ARM 32-bit version 4.19.15 (267023)
16:10:03.635 T:1936895520  NOTICE: Running on LibreELEC (Milhouse): devel-20190116234343-#0116-g3565115 [Build #0116] 9.0, kernel: Linux ARM 32-bit version 4.19.15
16:10:03.635 T:1936895520  NOTICE: FFmpeg version/source: 4.0.3-Kodi                      
16:10:03.635 T:1936895520  NOTICE: Host CPU: ARMv7 Processor rev 4 (v7l), 4 cores available
16:10:03.635 T:1936895520  NOTICE: ARM Features: Neon enabled

**Comment by phunkyfish** [comment]
So it reports as the same CPU, good to know. Thanks

**Comment by okriehn** [comment]
Wonder why the downloaded image from libreelec was a 32bit version?!

**Comment by okriehn** [comment]
Thanks for your time and support!

**Comment by phunkyfish** [comment]
No problem
