### ISSUE TITLE
Timeshift buffer limits

### ISSUE THREAD

**Issue by tsumitobatsu** [kodi-pvr/pvr.vuplus#173]
*Clarification: Really an enhancement request

I'm very grateful for the new Timeshift options with local buffering, but I'm wondering how I can manage the risk of the disk filling up - in particular as I'm using 64GB SSDs for this (SLC for endurance). Would it be possible to add options to limit the maximum size of the buffer file / maximum length of the buffer in time? (Both would be ideal). Honestly not sure how this would be handled in code as I imagine continuously wrapping could also be heavy on some types of storage, but done sparingly enough would be better than letting the disk fill. Or is there already some built-in mitigations for this scenario?

Many thanks

**Comment by phunkyfish** [comment]
The timeshift buffer should clear each time you stop viewing a channel or change channel. So unless you leave the same channel on for 24 hours+ you should be ok.

The other option is to use a USB thumb drive or create a partition on your HD that is just for timeshift. This would stop it affecting kodi operation I. The case it ever filled up.

**Comment by phunkyfish** [comment]
I’ll update the readme with the above info.

**Comment by phunkyfish** [comment]
Readme updated in 3.16.2/3

**Comment by tsumitobatsu** [comment]
Thanks for the clarification. Sorry I wasn't around.
For the record I was testing the latest LibreElec (beta 2) with the latest copy of the plugin as of about a week ago (not exact i know but can't access it atm).
I haven't yet had problems with full disk but am aware of a handful of true 1080p transport streams here in Germany which are pretty heavy and would soon (in maybe 12 hours or so) eat up my GB if someone forgot to turn off the PC. Was just wondering what exactly would happen in that scenario - i.e. how catastrophic the problem would be.

**Comment by phunkyfish** [comment]
You would run out of disk space. So whatever effect that has on your system.

On a PC it is easily solved. Just create a partition for the maximum size you would allow for timeshift or use a thumb drive. That way it can never overrun.
