### ISSUE TITLE
Signal Quality enabled by default in Kodi but disabled in Libreelec

### ISSUE THREAD

**Issue by phunkyfish** [kodi-pvr/pvr.vuplus#180]
Similar to channel groups being disabled by default in Libreelec the same is true of Signal quality.

Latest Libreelec on Intel not showing channel groups in guide #145

From vanilla kodi:

```
        <setting id="pvrplayback.signalquality" type="boolean" label="19037" help="36229">
          <level>2</level>
          <default>true</default>
          <control type="toggle" />
        </setting>
```

**Comment by phunkyfish** [comment]
@MilhouseVH are there many PVR settings where the defaults are different between Kodi and Libreelec?

**Comment by MilhouseVH** [comment]
Actually for once we have a reasonably descriptive commit that explains why signal quality has been disabled: https://github.com/LibreELEC/LibreELEC.tv/commit/ce4f57d3a5479090b79f092e637e1cf74b256d61
```
 kodi: disable pvrplayback.signalquality on new installs
this was reported to cause stuttering/artifacts
```

**Comment by phunkyfish** [comment]
It's not causing an issue. It's just I get users asking why a feature doesn't work. Then we go through the motions and finally we get to the fact they use libreelec and its just a setting after quite some digging.

With signal quality I guess many addons poll the PVR device each time it's called instead of caching it. Polling the device many times per second could cause stuttering issues on older devices.

I think they all make sense. I could imagine it being a nightmare to diagnose what causes the stuttering and finally find out it's signalquality. Although I would hope the addons would improve over time and that particular default would not be needed.

**Comment by phunkyfish** [comment]
Ty for the info though, at least I know it's just signal quality to worry about ;)

**Comment by phunkyfish** [comment]
Closing as this is expected behaviour in LibreElec.
