### ISSUE TITLE
Concurrent calls to GetEPGForChannel - crash loop on start LibreElec

### ISSUE THREAD

**Issue by phunkyfish** [kodi-pvr/pvr.vuplus#181]
On startup concurrent calls can occur to GetEPGForChannel. Confirmed on LibreElec for for x86 and Rpi.

Crashlog below shows the call occurring on multiple threads.

Fix is to use a mutex on this call in Epg class to ensure one calll at a time.

**Comment by phunkyfish** [comment]
https://gist.github.com/phunkyfish/a343e1bbebbf11ae5e3da49860ead41a

**Comment by phunkyfish** [comment]
The two threads in question:

Thread 2 (Thread 0x7f66ef7fe700 (LWP 1254)):
#0  0x00007f674e86cc2b in std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs(std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_Match_mode, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#1  0x00007f674e86d864 in std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_rep_once_more(std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_Match_mode, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#2  0x00007f674e86cc3b in std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs(std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_Match_mode, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#3  0x00007f674e86cd62 in std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs(std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_Match_mode, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#4  0x00007f674e86d864 in std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_rep_once_more(std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_Match_mode, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#5  0x00007f674e86cc3b in std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs(std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_Match_mode, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#6  0x00007f674e86cd62 in std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs(std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_Match_mode, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#7  0x00007f674e86d864 in std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_rep_once_more(std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_Match_mode, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#8  0x00007f674e86cc3b in std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs(std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_Match_mode, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#9  0x00007f674e86cd62 in std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs(std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_Match_mode, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#10 0x00007f674e86d864 in std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_rep_once_more(std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_Match_mode, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#11 0x00007f674e86cc3b in std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs(std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_Match_mode, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#12 0x00007f674e86cd62 in std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs(std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_Match_mode, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#13 0x00007f674e86d864 in std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_rep_once_more(std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_Match_mode, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#14 0x00007f674e86cc3b in std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs(std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_Match_mode, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#15 0x00007f674e86cd62 in std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs(std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_Match_mode, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#16 0x00007f674e86d864 in std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_rep_once_more(std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_Match_mode, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#17 0x00007f674e86cc3b in std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs(std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_Match_mode, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#18 0x00007f674e86cd62 in std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs(std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_Match_mode, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#19 0x00007f674e86d864 in std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_rep_once_more(std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_Match_mode, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#20 0x00007f674e86cc3b in std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs(std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_Match_mode, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#21 0x00007f674e86ce7a in std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs(std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_Match_mode, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#22 0x00007f674e86cc83 in std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs(std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_Match_mode, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#23 0x00007f674e86248d in ?? () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#24 0x00007f674e86cf62 in bool std::__detail::__regex_algo_impl<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, char, std::regex_traits<char>, (std::__detail::_RegexExecutorPolicy)0, true>(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, std::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > >&, std::basic_regex<char, std::regex_traits<char> > const&, std::regex_constants::match_flag_type) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#25 0x00007f674e88858a in enigma2::extract::IExtractor::GetMatchTextFromString(std::string const&, std::basic_regex<char, std::regex_traits<char> > const&) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#26 0x00007f674e8898c5 in enigma2::extract::IExtractor::GetMatchedText(std::string const&, std::string const&, std::basic_regex<char, std::regex_traits<char> > const&) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#27 0x00007f674e8887c7 in enigma2::extract::ShowInfoExtractor::ExtractFromEntry(enigma2::data::BaseEntry&) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#28 0x00007f674e886aa1 in enigma2::extract::EpgEntryExtractor::ExtractFromEntry(enigma2::data::BaseEntry&) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#29 0x00007f674e879cae in enigma2::Epg::GetInitialEPGForGroup(std::shared_ptr<enigma2::data::ChannelGroup>) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#30 0x00007f674e879f95 in enigma2::Epg::GetInitialEPGForChannel(ADDON_HANDLE_STRUCT*, std::shared_ptr<enigma2::data::Channel> const&, long, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#31 0x00007f674e87a212 in enigma2::Epg::GetEPGForChannel(ADDON_HANDLE_STRUCT*, PVR_CHANNEL const&, long, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#32 0x00000000009e07f0 in ?? ()
#33 0x00000000009d85f2 in PVR::CPVRClient::DoAddonCall(char const*, std::function<PVR_ERROR (KodiToAddonFuncTable_PVR const*)>, bool, bool) const ()
#34 0x00000000009e153e in PVR::CPVRClient::GetEPGForChannel(std::shared_ptr<PVR::CPVRChannel> const&, PVR::CPVREpg*, long, long, bool) ()
#35 0x00000000008fe292 in PVR::CPVREpg::UpdateFromScraper(long, long, bool) ()
#36 0x0000000000901174 in PVR::CPVREpg::GetTagBetween(CDateTime const&, CDateTime const&, bool) ()
#37 0x00000000009015ec in PVR::CPVRTimerInfoTag::GetEpgInfoTag(bool) const ()
#38 0x0000000000901fb4 in PVR::CPVRTimerInfoTag::UpdateEpgInfoTag() ()
#39 0x000000000090b8d7 in PVR::CPVRTimerInfoTag::CPVRTimerInfoTag(PVR_TIMER const&, std::shared_ptr<PVR::CPVRChannel> const&, unsigned int) ()
#40 0x00000000009e891c in PVR::CPVRClient::cb_transfer_timer_entry(void*, ADDON_HANDLE_STRUCT*, PVR_TIMER const*) ()
#41 0x00007f674e860398 in Enigma2::GetTimers(ADDON_HANDLE_STRUCT*) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#42 0x00000000009d60cb in ?? ()
#43 0x00000000009d85f2 in PVR::CPVRClient::DoAddonCall(char const*, std::function<PVR_ERROR (KodiToAddonFuncTable_PVR const*)>, bool, bool) const ()
#44 0x00000000009da0db in PVR::CPVRClient::GetTimers(PVR::CPVRTimersContainer*) ()
#45 0x00000000008c2f33 in PVR::CPVRClients::ForCreatedClients(char const*, std::function<PVR_ERROR (std::shared_ptr<PVR::CPVRClient> const&)>, std::vector<int, std::allocator<int> >&) const ()
#46 0x00000000008c36cd in PVR::CPVRClients::GetTimers(PVR::CPVRTimersContainer*, std::vector<int, std::allocator<int> >&) ()
#47 0x000000000090a8f6 in PVR::CPVRTimers::Update() ()
#48 0x00000000008c56bb in PVR::CPVRTimersUpdateJob::DoWork() ()
#49 0x00000000008ac4f3 in PVR::CPVRManagerJobQueue::ExecutePendingJobs() ()
#50 0x00000000008da1a4 in PVR::CPVRManager::Process() ()
#51 0x0000000000b08bbf in CThread::Action() ()
#52 0x0000000000b2ccad in CThread::staticThread(void*) ()
#53 0x00007f677ee05fb5 in start_thread (arg=<optimized out>) at pthread_create.c:486
#54 0x00007f677c7fc1df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f66edffb700 (LWP 1258)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f677c72a524 in __GI_abort () at abort.c:79
#2  0x00007f677c77f2b8 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f677c8812fe "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007f677c78583a in malloc_printerr (str=str@entry=0x7f677c882f88 "double free or corruption (!prev)") at malloc.c:5352
#4  0x00007f677c7871ac in _int_free (av=0x7f66c0000020, p=0x7f66c074fa70, have_lock=<optimized out>) at malloc.c:4325
#5  0x00007f674e87b332 in void std::vector<enigma2::data::EpgEntry, std::allocator<enigma2::data::EpgEntry> >::_M_realloc_insert<enigma2::data::EpgEntry&>(__gnu_cxx::__normal_iterator<enigma2::data::EpgEntry*, std::vector<enigma2::data::EpgEntry, std::allocator<enigma2::data::EpgEntry> > >, enigma2::data::EpgEntry&) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#6  0x00007f674e879cd3 in enigma2::Epg::GetInitialEPGForGroup(std::shared_ptr<enigma2::data::ChannelGroup>) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#7  0x00007f674e879f95 in enigma2::Epg::GetInitialEPGForChannel(ADDON_HANDLE_STRUCT*, std::shared_ptr<enigma2::data::Channel> const&, long, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#8  0x00007f674e87a212 in enigma2::Epg::GetEPGForChannel(ADDON_HANDLE_STRUCT*, PVR_CHANNEL const&, long, long) () from /usr/lib/kodi/addons/pvr.vuplus/pvr.vuplus.so.3.17.0
#9  0x00000000009e07f0 in ?? ()
#10 0x00000000009d85f2 in PVR::CPVRClient::DoAddonCall(char const*, std::function<PVR_ERROR (KodiToAddonFuncTable_PVR const*)>, bool, bool) const ()
#11 0x00000000009e153e in PVR::CPVRClient::GetEPGForChannel(std::shared_ptr<PVR::CPVRChannel> const&, PVR::CPVREpg*, long, long, bool) ()
#12 0x00000000008fe292 in PVR::CPVREpg::UpdateFromScraper(long, long, bool) ()
#13 0x0000000000900f75 in PVR::CPVREpg::LoadFromClients(long, long, bool) ()
#14 0x000000000090c903 in PVR::CPVREpg::Update(long, long, int, bool) ()
#15 0x000000000090cd18 in PVR::CPVREpgContainer::UpdateEPG(bool) ()
#16 0x000000000090d175 in PVR::CPVREpgContainer::Process() ()
#17 0x0000000000b08bbf in CThread::Action() ()
#18 0x0000000000b2ccad in CThread::staticThread(void*) ()
#19 0x00007f677ee05fb5 in start_thread (arg=<optimized out>) at pthread_create.c:486
#20 0x00007f677c7fc1df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
`

**Comment by phunkyfish** [comment]
So the failed fix brings us from crash loop to a deadlock and only on LibreElec (before and after the fix).

I’m not sure why the thread model is different on LibreElec

**Comment by phunkyfish** [comment]
I've had a few reports of a crash loop again on the testbuilds and just managed to repro. Next I will try disabling the initial EPG load and see if that makes a difference.

Here is a gist. It includes a snippet of Thread 1 and 49 where the contention appears to be. It would appear to be in the PVR code and not the addon: https://gist.github.com/phunkyfish/8be9555b1455699c98302f9a8ec582e3

@ksooo any idea's on this.

**Comment by phunkyfish** [comment]
The initial crash loop had two concurrent calls to GetEpgForChannel. The second appears to be two threads doing roughly the same thing.

I thought you said previously that only one channel is updated at a time. Is this definitely true?

**Comment by phunkyfish** [comment]
A permanent solution to this would be to use async EPG just so that the addon handles the threading for EPG updates. It would be the same data just without the addon asking for the data. Then I could restore the Now and next EPG load functionality on startup.

@ksooo is there a way for the addon to read the current EPG update interval and the prevent updates during playback fields from the PVR settings in Kodi? Or any plans to include them in PVR_PROPERTIES?

**Comment by ksooo** [comment]
> is there a way for the addon to read the current EPG update interval and the prevent updates during playback fields from the PVR settings in Kodi

 I don't think this is currently possible.

> Or any plans to include them in PVR_PROPERTIES

 I'm afraid, not.

**Comment by phunkyfish** [comment]
No worries. I can have separate config items in the addon. It just would have been cleaner.
