### ISSUE TITLE
3.17.0 release not appearing in Leia addon repo on Windows and OSX

### ISSUE THREAD

**Issue by phunkyfish** [kodi-pvr/pvr.vuplus#183]
It was my understanding that once a binary addon was released it would appear as an update within the next 24 or so hours.

I created the above release two days ago. Any way I can check what the issue might be @Rechi ?

**Comment by ksooo** [comment]
Our jenkins had massive problems yesterday... @Rechi ping

**Comment by phunkyfish** [comment]
Ah, good to know. I’m sure it will be ready when it’s ready.

**Comment by Rechi** [comment]
It's now on the mirrors, will be in the repo (addons.xml) soon.

**Comment by phunkyfish** [comment]
Thank you
