### ISSUE TITLE
Kodi does not exit (for several minutes) if Enigma2-receiver is not reachable

### ISSUE THREAD

**Issue by heikoh81** [kodi-pvr/pvr.vuplus#184]
Hi,

I found another bug releated to:
https://github.com/kodi-pvr/pvr.vuplus/issues/154

If Enigma2-plugin is enabled and Enigma2-receiver is offline (e.g. in deep standby), I cannot exit Kodi.
Kodi seems to hang for a very long time, although time varies (from 30 seconds to over 15 minutes!).
Sometimes I have to kill Kodi through FireTVStick2 settings menu.

The problem is reproducable:
If I disable the Enigma2 plugin while Enigma2 is offlline, Kodi exits immediately.
If I enable Enigma2 plugin again (while Engima2 receiver is still in deep standby), Exit seems to hang again.

I hope you can fix this bug as well.

Greetings,
Heiko

**Comment by phunkyfish** [comment]
Yes. This use case should be covered by implementing a sync connection.
