### ISSUE TITLE
Async EPG

### ISSUE THREAD

**Issue by phunkyfish** [kodi-pvr/pvr.vuplus#188]
In 3.17.1 an option was added to avoid an initial load of now and next EPG to avoid a crash loop on LibreElec/CoreElec. In order to permanently fix and remove the default option the addon would need to support async EPG. Functionality wise there would be no change for users but by doing this the EPG threading would be handled by the addon and avoid any possible crash loop.

Expected in 3.20.0 or later release.

**Comment by phunkyfish** [comment]
@ksooo when looking at this I ran into a potential issue. 

For many users they disable epg updates during playback. 

For the way I would use this I would not be pushing just updates, instead the same cadence and size of updates only it would initiate from the addon.

I assume there is no way to know if kodi is currently playing something back? Or does this option only avoid PVR playback and not regular playback?

(I have attempted to answer this myself from the code!)

**Comment by ksooo** [comment]
Sorry, don't know.

**Comment by phunkyfish** [comment]
So this is just for PVR. Which is handy as it means I can mimic it in the addon (although only for this addon).

**Comment by phunkyfish** [comment]
Closing as obselete
