### ISSUE TITLE
latest build crashes kodi

### ISSUE THREAD

**Issue by M2k80** [kodi-pvr/pvr.vuplus#191]
cant start kodi with enabled plugin anymore. just updated to the latest build. pvr.vuplus-3.18.0
stacktrace
https://paste.kodi.tv/zeqobibofa.kodi

and the last entrys of kodi before crash
https://paste.kodi.tv/tapupezafe.kodi

**Comment by rezpower** [comment]
Same thing is happening to me. I was having kodi crash as soon as I opened it and was wondering what was wrong!

**Comment by iophobia** [comment]
Same here. Although it's not the addon per se. If my vuplus is off during kodi launch on a shield tv, I at least get to main menu after being shown that e2 can't be loaded.
Only when the vuplus is on, kodi force closes right after startup screen.

**Comment by phunkyfish** [comment]
It sounds like the addon. Can I get some full debug logs, what platforms you are using etc.?

**Comment by M2k80** [comment]
its the libpvr.vuplus.so, when i use the old one, its working.
i will make a debug now

**Comment by M2k80** [comment]
https://paste.kodi.tv/odeyesikut.kodi

**Comment by phunkyfish** [comment]
Sorry, I know the problem. Will fix shortly.

**Comment by M2k80** [comment]
no problem, thank you for fast help

**Comment by phunkyfish** [comment]
PR Approved - should be in the addon repos in the next 24 hours.
