### ISSUE TITLE
Cmake version depends on version 3.8 due to nlohmann/json

### ISSUE THREAD

**Issue by phunkyfish** [kodi-pvr/pvr.vuplus#194]
Causes issues when building OSMC and for users on Ubuntu as build platform. Creating issue instead of proposed PR: https://github.com/kodi-pvr/pvr.vuplus/pull/190

Upstream issue here: https://github.com/nlohmann/json/issues/1498
Upstream PR which relaxes the dependency: https://github.com/nlohmann/json/pull/1441

**Comment by phunkyfish** [comment]
@StormTrooper @samnazarko will track from here instead of proposed PR.

The upstream PR which relaxed the dependency was incorrect, there is a new one proposed.

**Comment by samnazarko** [comment]
Do we have some progress on this? Anything we can do to help on our side?

S

**Comment by phunkyfish** [comment]
So now we just need a release of nlohmann/json.

I would advice creating an upstream issue stating what you need and why it’s important. If it’s ready for the next major release they might do a minor release just including the fix you need. 

No harm in asking.

**Comment by StormTrooper** [comment]
3.6.1 has been pushed out (Issue actually fixed in 3.6.0)

**Comment by phunkyfish** [comment]
Can you try updating the zip version and SHA hash here:

https://github.com/kodi-pvr/pvr.vuplus/blob/97c67ae039fc0cfdc7a08ba3bc6cb0c9905bc794/depends/common/nlohmann-json/nlohmann-json.txt#L1

And here:

https://github.com/kodi-pvr/pvr.vuplus/blob/97c67ae039fc0cfdc7a08ba3bc6cb0c9905bc794/depends/common/nlohmann-json/nlohmann-json.sha256#L1

to see if it solves your issues?

**Comment by phunkyfish** [comment]
Obviously to 3.6.1 as 3.6.0 had issues.

**Comment by phunkyfish** [comment]
In the meantime I will test using 3.6.1

**Comment by StormTrooper** [comment]
Updating to 3.6.1 fixes the issue. Build completes successfully.

**Comment by phunkyfish** [comment]
Great, will include the update in the next PR
