### ISSUE TITLE
3.19.0: Error messages "Server is unreachable" during playback of Video files

### ISSUE THREAD

**Issue by heikoh81** [kodi-pvr/pvr.vuplus#196]
Hi.

As requested and described in https://github.com/kodi-pvr/pvr.vuplus/issues/154#issuecomment-470670571 I have attached a full log.
[kodi.log](https://github.com/kodi-pvr/pvr.vuplus/files/2943176/kodi.log)

I have problems since version 3.19.0 if I playback SMB-recordings with Enigma2-plugin active.
There are no problems or error messages during live streaming of TV.
After 1 Video has been playback, live TV can not be started again until Kodi has been killed or exited.

What I have recorded in this .log:

- started Kodi
- waited for Engima2-Plugin to load up
- started live TV, switched channel 3 times
- stopped live TV
- switched to Videos category in Kodi, started playback of .ts-File
- After several seconds, but not immediately, Popups start showing up.
- Stopped playback.
- Tried to start live TV again (no success).
- Exit of Kodi -> Kodi crashes.

I hope you can fix this.
Greetings,
Heiko

**Comment by phunkyfish** [comment]
Let’s move the conversation here related to this issue. Thanks for creating.

Can you try 2 things:

1 - can you reproduce if you playback TS recordings via the addon?
2 - can you reproduce if you playback a video file that is mp4, mkv etc instead of TS

**Comment by phunkyfish** [comment]
Could you also try to skip the initial epg import. The option will be in addon settings.

**Comment by heikoh81** [comment]
> 
> 
> Let’s move the conversation here related to this issue. Thanks for creating.
> 
> Can you try 2 things:
> 
> 1 - can you reproduce if you playback TS recordings via the addon?

No error popup.

> 2 - can you reproduce if you playback a video file that is mp4, mkv etc instead of TS

Error popup as soon as file is played from "Videos" category of Kodi.
Full log of this session (no Kodi crash at the end, though): 
[kodi.log](https://github.com/kodi-pvr/pvr.vuplus/files/2943236/kodi.log)

**Comment by heikoh81** [comment]
> 
> 
> Could you also try to skip the initial epg import. The option will be in addon settings.

This setting has been ENABLED at all previous tests.
It is the only Addon setting of Enigma2-Plugin that is enabled at all!
Should I disable it?

**Comment by heikoh81** [comment]
I tried another session.
This time, I was able to watch Video, then return to Live TV, but then, on watching Video again, the Popups started again.
I stopped playback quickly and exited Kodi, maybe you can narrow down the problem at the end of the log file.

[kodi.log](https://github.com/kodi-pvr/pvr.vuplus/files/2943295/kodi.log)

**Comment by heikoh81** [comment]
I found no way how to return to an old version of this addon.
The offical kodi repo only offers 3.19.0.

Where can I find an older .zip-Version of this plugin?

**Comment by heikoh81** [comment]
Manually reverted to 3.18.1 - no problems so far.

**Comment by phunkyfish** [comment]
How come you playback the recordings from a samba share instead of via the recordings in the addon?

**Comment by heikoh81** [comment]
Never used the addon for this.
Also, I watch the recordings on multiple FireTV Stick2s accross the house.
With "Videos", I get the time where I stopped playback from MySQL.

Also, I have video files on my Samba Share that are not accessible with the Enigma2 receiver.

**Comment by phunkyfish** [comment]
Yes, but these recordings are are created by the addon right? In that case they still play from the share but will play far more efficiently, it will still record your progress regardless of mysql or not. There is meta data kodi cannot read associated with the recordings so they should only be played from the addon.

Use videos for all the other files.

**Comment by phunkyfish** [comment]
So the capability you want to to start watching a recording on one fire stick and resume on another? That sounds like a great feature request for the addon!

**Comment by heikoh81** [comment]
> 
> Use videos for all the other files.

But the error Popups appear with other files, too, so this is not a solution for other videos.

> So the capability you want to to start watching a recording on one fire stick and resume on another? That sounds like a great feature request for the addon!

You could add this, but it is also integrated with MySQL.

**Comment by phunkyfish** [comment]
Tuning options for slower E2 devices in next release: https://github.com/kodi-pvr/pvr.vuplus/pull/198

Start with tuning the timeout first, and then possibly the interval.

**Comment by heikoh81** [comment]
Thank you.
If the bugfixes are available in the official repo at
https://mirrors.kodi.tv/addons/leia/pvr.vuplus+android-armv7/
I will try again!

FYI:
After downgrading to 3.18.1, I no longer have any of the Error-Popups described above.
It doesn't matter if I playback from recordings via SMB Share in "Video"-categories.
So maybe you could investigate what changes happened from 3.18.1 to 3.19.0 that cause these Connection lost-popups.

**Comment by phunkyfish** [comment]
The difference is the feature I added so that you don’t have to start your Enigma2 before kodi!

**Comment by heikoh81** [comment]
Yes, but how does this produce the Popup messages during playback of Video files.
Shouldn't the addon just do the following:
If "ping enigma2 box" == OK, then start addon / do whatever it does
If "ping enigma2 box" <> OK, then wait 60 seconds and ping again

**Comment by phunkyfish** [comment]
The addon is always started with the new feature. Then it periodically checks can it still connect to the E2 box. If it can’t it tries to reconnect and can it waits an interval time and checks again.

**Comment by heikoh81** [comment]
So maybe you just have to disable the popup warnings of connection checks fails? This is just interal information for the addon, not for the enduser?

**Comment by phunkyfish** [comment]
The issue is that the check is failing. The popups are generated by kodi and not the addon.

The tuning options in the next release are so you can figure out values that work.

**Comment by phunkyfish** [comment]
Tuning options are in v3.20.0 just released. Will be in addon repos over the next 24 hours

Start with tuning the timeout first, and then possibly the interval. Let me know what works/doesn't

**Comment by heikoh81** [comment]
Will try tomorrow as soon as the update is available.

**Comment by heikoh81** [comment]
"Start with tuning the timeout first, and then possibly the interval. Let me know what works/doesn't"

It is working now with 3.21.0.
It detects my very old and slow VUSolo if powered on after Kodi start.
I can play Videos from "Video"-category in kodi, go back to watching TV etc.

After the startup of my Enigma2-box, I had 3-4 popups "Connection established".
I think that should only be displayed once, but maybe it can be fixed by my following request:

request:
Could you please extend the selectable times to up to 60 seconds.
Shouldn't be much code change I guess.

I have
Connection check timeout = 10 seconds
Connection check interval = 10 seconds

**Comment by phunkyfish** [comment]
If the timeout values are correct the pop up should only appear once.

I will increase to 60 in next release for testing purposes.

**Comment by phunkyfish** [comment]
The timeout value can already be set to 60. So it’s just the interval you want to be able to change up to 60?

**Comment by phunkyfish** [comment]
Interval can be set to 60 seconds in PR: #206

**Comment by heikoh81** [comment]
The plugin is now working great!
I no longer get annoying popups about connection established.
And I can power on my Enigma2 after Kodi-start anytime.

Thanks a lot!

**Comment by phunkyfish** [comment]
What settings did you end up using for interval and timeout that worked best?

**Comment by heikoh81** [comment]
Both settings to 60 seconds.
I don't need that fast recognition if enigma2 is turned on so 60 seconds is OK for me.
