### ISSUE TITLE
Short picture freezes while streaming

### ISSUE THREAD

**Issue by Malzmeier** [kodi-pvr/pvr.vuplus#197]
HI,

since upgrading Kodi from 17.6 to 18 (and 18.1) I am experiencing streaming problems.
The picture keeps freezing for a short time (about 1 second) while the sound is playing on and then the picture keeps up with the sound in „fast-forward“ style.
I have this issue an all my machines (LibreELEC Pi, AndroidTV, Ubuntu Desktop) since upgrading to Kodi 18 and the 3.xx releases of the Addon.
Playing recordings from my backend (OpenATV 6.2 on Xtrand ET8500) is fine. Playing other formats (mkv) is also fine. It‘s only happening while streaming.

Going back to 17.6 and 2.15 addon will fix it.

I tried altering Kodi video and audio settings with no success.

Could it be an issue in the addon? I coudln‘t find other reports on this problem.

**Comment by phunkyfish** [comment]
Can you try disabling EPG updates on playback in kodi PVR settings?

**Comment by Malzmeier** [comment]
I tried and it seems to work for the last hour. Can't believe that there is such simple solution. 

Is this a bug and will be fixed or is this workaround permanent?

Thanks a lot

**Comment by phunkyfish** [comment]
Today kodi pvr manages the epg updates. A future release will move this into the addon potentially, by default the addon would not allow updates during playback so it shouldn’t cause you an issue.

**Comment by phunkyfish** [comment]
So not a bug at all...

**Comment by Malzmeier** [comment]
Ok, the solution works for me and I'm happy with it.
