### ISSUE TITLE
channels that have alternatives can not be watched

### ISSUE THREAD

**Issue by slo617** [kodi-pvr/pvr.vuplus#20]
If a channel can be received in multiple ways it is possible to define alternatives for that channel. (E.g. DVB-S and DVB-T or HD and SD)
While "normal" channels without alternatives can be watched fine, as soon as an alternative is defined that channel can not be watched any more,

**Comment by slo617** [comment]
This problem has also been discussed here: http://forum.kodi.tv/showthread.php?tid=214804

**Comment by hudokkow** [comment]
AFAIK, current openWebIF API doesn't provide that kind of differentiation/information ready to grab and use with our PVR implementation.
Might be worth investigating, though.

**Comment by slo617** [comment]
@hudokkow 
You are right - or at least I do not see a way to read out the alternatives - but that is not necessary.
If you download the stream.m3u file for a channel and open it in you favorite media player (like VLC) or the IPTV simple pvr plugin the channel is played fine and the VU+/enigma2 box will automatically stream one of the available alternatives.

**Comment by slo617** [comment]
It seems that a getServices request responses with another "bouquet" for channels with alternative.

For a channel with alternatives the \<e2servicereference\> field contains this:
    1:134:1:0:0:0:0:0:0:0:FROM BOUQUET "alternatives.das_erste_hd.tv" ORDER BY bouquet

while a "normal" field contains something like this:
    1:0:1:2EE3:441:1:C00000:0:0:0:

Anyhow, the <code>web/stream.m3u?ref=</code> request responds with a proper m3u-file with a proper streaming-URL for both.
So <code>http://10.1.2.3/web/stream.m3u?ref=1:134:1:0:0:0:0:0:0:0:FROM BOUQUET "alternatives.das_erste_hd.tv" ORDER BY bouquet</code> works fine,
while <code>http://10.1.2.3:8001/1:134:1:0:0:0:0:0:0:0:FROM BOUQUET "alternatives.das_erste_hd.tv" ORDER BY bouquet</code> does not work...

The m3u-files changes depending on the currently available channels if channels are blocked by recordings/timer.

I took a short look into the source code but could not find the code for loading the m3u-file, maybe this is the problem.

**Comment by slo617** [comment]
I have uploaded some code that fixes this issue. (see #21 and #22)
I hope you like it.

**Comment by hudokkow** [comment]
Thanks, I saw the PRs. ;-)
Right now I'm way too busy with real life but, as soon as I can, I'll review and test with my Solo2.

**Comment by slo617** [comment]
This has been solved by pull request #22.

To watch channels with alternatives enable automatic configuration for live streams. (add-on settings -> advanced)
