### ISSUE TITLE
username field not present in config dialog

### ISSUE THREAD

**Issue by slughot** [kodi-pvr/pvr.vuplus#200]
In the config dialog the username field is not present.
![image](https://user-images.githubusercontent.com/48380795/54070330-ca4e5100-425e-11e9-880d-19441fa82ba4.png)

**Comment by phunkyfish** [comment]
This config UI looks unfamiliar, what platform and version is this running on?

**Comment by slughot** [comment]
Kodi 18.1 on Linux_x64 (Ubuntu) with the Enigma2 Plugin from the builtin feed. The VU+ forum said, take it from the feed or this GIT. Is it not yours?

**Comment by phunkyfish** [comment]
It should be ok, can you post a full debug log?

**Comment by slughot** [comment]
I realized that the build number is 2.0.0 and referencing to http://enigma-tv.com

**Comment by phunkyfish** [comment]
You should uninstall that addon and then install from PVR->Clients.

What is the content of this folder on your OS: userdata/addon_data

**Comment by slughot** [comment]
I uninstalled it. I dont have a section PVR. I found it in section video

under userdata/addon_data
plugin.video.enigmatv
and two skin folders

**Comment by phunkyfish** [comment]
Ok, now that it’s uninstalled I would delete that. I don’t know what that addon is or does.

**Comment by phunkyfish** [comment]
Looking at this: https://kodi.tv/article/kodi-v18-binary-add-ons-repository

It appears you still use PPA to install the addon.

**Comment by phunkyfish** [comment]
So search for pvr.vuplus and install that.

**Comment by slughot** [comment]
nas@nas:~/pvr.vuplus/build$ cmake -DADDONS_TO_BUILD=pvr.vuplus -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../../xbmc/build/addons -DPACKAGE_ZIP=1 ../../xbmc/cmake/addons
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Addon source tarball caching is enabled
-- ZIP packaging enabled (destination: /home/nas/pvr.vuplus/build/build/zips)
-- Building following addons: pvr.vuplus
-- Overriding addon source directory prefix: /home/nas
-- 
-- ---- Preparing general dependencies ----
-- Processing /home/nas/xbmc/cmake/addons/depends/common/kodi-platform/kodi-platform.txt
-- kodi-platform url: https://github.com/xbmc/kodi-platform
-- kodi-platform depends: tinyxml;p8-platform
-- Processing /home/nas/xbmc/cmake/addons/depends/common/p8-platform/p8-platform.txt
-- p8-platform url: https://github.com/xbmc/platform.git
-- Processing /home/nas/xbmc/cmake/addons/depends/common/tinyxml/tinyxml.txt
-- tinyxml url: http://mirrors.kodi.tv/build-deps/sources/tinyxml-2.6.2_2.tar.gz
-- No platform specific file /home/nas/xbmc/cmake/addons/depends/linux/CMakeLists.txt found
-- 
-- ---- Configuring addon /home/nas/xbmc/cmake/addons/addons/pvr.vuplus/pvr.vuplus.txt ----
-- Processing /home/nas/pvr.vuplus/depends/common/nlohmann-json/nlohmann-json.txt
-- nlohmann-json url: https://github.com/nlohmann/json/archive/v3.5.0.tar.gz
-- nlohmann-json extraflags: -DBUILD_TESTING:BOOL=OFF
-- pvr.vuplus DEPENDENCIES: nlohmann-json
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nas/pvr.vuplus/build

**Comment by phunkyfish** [comment]
Build and install yourself, that works too!

**Comment by phunkyfish** [comment]
Note that you’ll need to copy the addon directory from here: ../../xbmc/build/addons
To where it should be on your system.

**Comment by slughot** [comment]
Thx, got it working. Now I need to make a successful attempt to my box, but thats a different story :)

**Comment by phunkyfish** [comment]
Good luck 😉

**Comment by slughot** [comment]
> Note that you’ll need to copy the addon directory from here: ../../xbmc/build/addons
> To where it should be on your system after you build it.

Actually that directory contains only empty folders. Not sure where the addon has been built... Would appreciate any hints

**Comment by phunkyfish** [comment]
The folder you should copy should be ../../xbmc/build/addons/pvr.vuplus

However if you have this working maybe the make command does the installing for you on Ubuntu.

**Comment by slughot** [comment]
I have tried now several times to build the package but everytime the build folder is empty
../../xbmc/build/addons/       <- there are just empty subfolders 'lib/kodi' + 'share/kodi'.

**Comment by phunkyfish** [comment]
Can you post the build output using pastebinit or similar?

Do you have the addon running? On Linux it might just install the addon for you.

**Comment by phunkyfish** [comment]
I build on MacOSx so I’m not familiar with Linux builds.
