### ISSUE TITLE
Request to add ability to save searches

### ISSUE THREAD

**Issue by poldebruin** [kodi-pvr/pvr.vuplus#205]
Hi, great add-on and work. Hope this request is in the correct area!

I just wanted to float the idea of being able to save searches. 

At the moment I can set the add-on to search for programs between 90 and 210 minutes long with movie as genre and it will fetch and return a fine list of movies to peruse. It would be great to be able to do this at the touch of a (saved search) button. 

Another idea might be to add the option for "Today" or "next XX hours" into the date field so you do not have to enter and update the date every time.

Finally, (although I'm not sure how feasible this would be) if there was a way to include or exclude certain channels only....at the moment it is all or a single......to be able to omit particular channels would make this a powerful feature, similar to the way plex curates upcoming programs/movies on its front end.

Once again, thank you for all the great work you do on this add-on.

**Comment by phunkyfish** [comment]
Thank you. Although most of the credit goes to Kodi PVR for the core functionality. The addon simply populates the data used by the PVR component.

Saved searches and restricting to channel groups (seems like the most logical to do this) would need to be added to the core.

@ksooo any plans for something similar to the above on the roadmap?

**Comment by phunkyfish** [comment]
Closing as request is for kodi.
