### ISSUE TITLE
Improve channel groups selection

### ISSUE THREAD

**Issue by maxbambi** [kodi-pvr/pvr.vuplus#209]
This plugin allows only to pick among three options: All groups, One group, Favourites group.
I think it would be a very good improvement (and not so difficult to be coded) to allow the choice of a list of channel groups (i.e. a comma separated list or strings written in a text file).

'All groups' option is often the best one, but with a lot of channels, system could become very slow,
in particular if a lot of iptv channels have been added in Enigma's services.

**Comment by phunkyfish** [comment]
This is possible. Leave it with me. I’m away for a few weeks but will look into it once back.

**Comment by phunkyfish** [comment]
Depending on complexity this might only be done for Kodi 19.

**Comment by M2k80** [comment]
i think it would really nice, if we could choose which groups we want to be added

**Comment by phunkyfish** [comment]
It will be via a custom xml file, easiest way I can think of doing it.

**Comment by maxbambi** [comment]
Yes, in the first run of plugin, a function could control if this file exists and create it with all groups, if it doesn't.
After user could edit it with a text editor and comment unwanted groups.
According to me, it is not very important in the first step, the implementation of a gui in kodi to modify this file.

**Comment by phunkyfish** [comment]
This won't be done via the GUI in a fancy way. There just isn't any dynamic support for things like this in the addon settings UI.

It will be path to a file, nice and simple. An example will be provided. You would ssh to the device to make a copy of the file and edit it. Then back in the UI select this new file.

I don't think building the file on first run is worthwhile. Group lists can change all the time and the list could become outdated quickly.

**Comment by maxbambi** [comment]
I have tried your mod and it does exactly what I wanted.
But it seems there is a problem with channel order and numbers assigned to channels.
When channel list (from selected group) is shown, numbers sorts channels with a strange order: first all first channels of each group, then all second channels and so on... 
In Previous versions of plugin channels were shown according to group: channels of first group, then channels of second group and so on...
I don't know if it depends on my configutation of pvr setting...
I have seen in log that backend number assigned restart from 1 for each group of channels

**Comment by phunkyfish** [comment]
Just turn off use backend channel numbers in the PVR settings. That was implemented in the last PR. The setting didn’t matter before as the addon decided the order regardless.

**Comment by phunkyfish** [comment]
With a bit of help i’ve Managed to support this in the UI for up to five bouquets. If you need more than that you can use the XML file.
