### ISSUE TITLE
Unable to start addon

### ISSUE THREAD

**Issue by Matthias1992** [kodi-pvr/pvr.vuplus#212]
https://pastebin.com/irS4fNeb

Hello guys, my problem is that if I want to start the pvr addon, it still remains by zero percent by initialization and nothing happens, I have no idea whats wrong ...
 Its Kodi Leia 18

regards,
Matthias

**Comment by phunkyfish** [comment]
You have an error here:

`2019-04-23 22:57:32.818 T:139936830523136    INFO: AddOnLog: Enigma2 Client: pvr.vuplus - GetHttpXML Open webAPI with URL: 'http://192.168.3.54:80/api/getservices?provider=1&picon=1&sRef=1%3A7%3A1%3A0%3A0%3A0%3A0%3A0%3A0%3A0%3AFROM%20BOUQUET%20%22userbouquet%2Efta%5Fdeutsch%2Etv%22%20ORDER%20BY%20bouquet'
2019-04-23 22:57:32.819 T:139936830523136   DEBUG: CFileCache::Open - opening <api/getservices> using cache
2019-04-23 22:57:32.819 T:139936830523136   DEBUG: CurlFile::Open(0x7f458031e550) http://192.168.3.54:80/api/getservices?provider=1&picon=1&sRef=1%3A7%3A1%3A0%3A0%3A0%3A0%3A0%3A0%3A0%3AFROM%20BOUQUET%20%22userbouquet%2Efta%5Fdeutsch%2Etv%22%20ORDER%20BY%20bouquet
2019-04-23 22:57:32.825 T:139937801238912   DEBUG: Keyboard: scancode: 0x74, sym: 0x0112, unicode: 0x0000, modifier: 0x0
2019-04-23 22:57:32.926 T:139937801238912   DEBUG: Previous line repeats 1 times.
2019-04-23 22:57:32.926 T:139937801238912   DEBUG: HandleKey: down (0xf081) pressed, action is Down
2019-04-23 22:57:32.942 T:139935413139200   DEBUG: Thread FileCache start, auto delete: false
2019-04-23 22:57:32.942 T:139935413139200    INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?)
2019-04-23 22:57:32.942 T:139935413139200   DEBUG: Thread FileCache 139935413139200 terminating
2019-04-23 22:57:32.942 T:139936830523136    INFO: AddOnLog: Enigma2 Client: pvr.vuplus - GetHttpXML Got result. Length: 4292
2019-04-23 22:57:32.944 T:139936830523136   ERROR: Process error processing job pvr-startup`

However I'm not sure what is causing it. If you to the addon settings you can enable trace level logging which might give us more clues.

Is this is recent issue or did you upgrade from a previous version?

**Comment by Matthias1992** [comment]
Hey, yep its a recent issue I tried it for the first time, ehm where I can set the level logging, because this was already a debug log from kodi

In the pvr settings I was unable to find some log level stuff

**Comment by phunkyfish** [comment]
Go the settings of the addon, then on the advanced tab there should be something like log trace as debug or something like that.

**Comment by Matthias1992** [comment]
https://imgur.com/Kv3uY4B

Sorry there is nothing there :( "Erweitert" would be advanced in german,

I checked the link manual 
`http://192.168.3.54:80/api/getservices?provider=1&picon=1&sRef=1%3A7%3A1%3A0%3A0%3A0%3A0%3A0%3A0%3A0%3AFROM%20BOUQUET%20%22userbouquet%2Efta%5Fdeutsch%2Etv%22%20ORDER%20BY%20bouque`

`{
 "services": [
  {
   "servicereference": "1:0:1:445D:453:1:C00000:0:0:0:", 
   "program": 17501, 
   "servicename": "ProSieben", 
   "pos": 1
  }, 
  {
   "servicereference": "1:0:1:4461:453:1:C00000:0:0:0:", 
   "program": 17505, 
   "servicename": "Pro7 MAXX", 
   "pos": 2
  }, 
  {
   "servicereference": "1:0:1:445C:453:1:C00000:0:0:0:", 
   "program": 17500, 
   "servicename": "SAT.1", 
   "pos": 3
  }, 
  {
   "servicereference": "1:0:1:4460:453:1:C00000:0:0:0:", 
   "program": 17504, 
   "servicename": "SAT.1 Gold", 
   "pos": 4
  }, 
  {
   "servicereference": "1:0:1:125D:3F7:1:C00000:0:0:0:", 
   "program": 4701, 
   "servicename": "SES 02", 
   "pos": 5
  }, 
  {
   "servicereference": "1:0:1:445E:453:1:C00000:0:0:0:", 
   "program": 17502, 
   "servicename": "kabel eins", 
   "pos": 6
  }, 
  {
   "servicereference": "1:0:1:2EE3:441:1:C00000:0:0:0:", 
   "program": 12003, 
   "servicename": "RTL Television", 
   "pos": 7
  }, 
  {
   "servicereference": "1:0:1:332E:45B:1:C00000:0:0:0:", 
   "program": 13102, 
   "servicename": "NITRO Austria", 
   "pos": 8
  }, 
  {
   "servicereference": "1:0:1:2EFE:441:1:C00000:0:0:0:", 
   "program": 12030, 
   "servicename": "TOGGO plus", 
   "pos": 9
  }, 
  {
   "servicereference": "1:0:1:2EF4:441:1:C00000:0:0:0:", 
   "program": 12020, 
   "servicename": "RTL2", 
   "pos": 10
  }, 
  {
   "servicereference": "1:0:1:308:5:85:C00000:0:0:0:", 
   "program": 776, 
   "servicename": "SIXX", 
   "pos": 11
  }, 
  {
   "servicereference": "1:0:1:2F1C:441:1:C00000:0:0:0:", 
   "program": 12060, 
   "servicename": "VOX", 
   "pos": 12
  }, 
  {
   "servicereference": "1:0:1:2F08:441:1:C00000:0:0:0:", 
   "program": 12040, 
   "servicename": "SUPER RTL", 
   "pos": 13
  }, 
  {
   "servicereference": "1:0:1:2F3A:441:1:C00000:0:0:0:", 
   "program": 12090, 
   "servicename": "n-tv", 
   "pos": 14
  }, 
  {
   "servicereference": "1:0:1:332F:45B:1:C00000:0:0:0:", 
   "program": 13103, 
   "servicename": "Welt der Wunder", 
   "pos": 15
  }, 
  {
   "servicereference": "1:0:1:445F:453:1:C00000:0:0:0:", 
   "program": 17503, 
   "servicename": "WELT", 
   "pos": 16
  }, 
  {
   "servicereference": "1:0:1:33:21:85:C00000:0:0:0:", 
   "program": 51, 
   "servicename": "TELE 5", 
   "pos": 17
  }, 
  {
   "servicereference": "1:0:1:7008:436:1:C00000:0:0:0:", 
   "program": 28680, 
   "servicename": "NICK/MTV+", 
   "pos": 18
  }, 
  {
   "servicereference": "1:0:1:3F:21:85:C00000:0:0:0:", 
   "program": 63, 
   "servicename": "DMAX", 
   "pos": 19
  }, 
  {
   "servicereference": "1:0:16:FDA:451:35:C00000:0:0:0:", 
   "program": 4058, 
   "servicename": "Test 1105", 
   "pos": 20
  }, 
  {
   "servicereference": "1:0:1:2FC:5:85:C00000:0:0:0:", 
   "program": 764, 
   "servicename": "ANIXE SD", 
   "pos": 21
  }, 
  {
   "servicereference": "1:0:1:6DCA:44D:1:C00000:0:0:0:", 
   "program": 28106, 
   "servicename": "Das Erste", 
   "pos": 22
  }, 
  {
   "servicereference": "1:0:1:7034:41B:1:C00000:0:0:0:", 
   "program": 28724, 
   "servicename": "arte", 
   "pos": 23
  }, 
  {
   "servicereference": "1:0:1:6D66:437:1:C00000:0:0:0:", 
   "program": 28006, 
   "servicename": "ZDF", 
   "pos": 24
  }, 
  {
   "servicereference": "1:0:1:6D6E:437:1:C00000:0:0:0:", 
   "program": 28014, 
   "servicename": "zdf_neo", 
   "pos": 25
  }, 
  {
   "servicereference": "1:0:1:6D70:437:1:C00000:0:0:0:", 
   "program": 28016, 
   "servicename": "zdf.kultur", 
   "pos": 26
  }, 
  {
   "servicereference": "1:0:1:6D6B:437:1:C00000:0:0:0:", 
   "program": 28011, 
   "servicename": "ZDFinfo", 
   "pos": 27
  }, 
  {
   "servicereference": "1:0:1:7035:41B:1:C00000:0:0:0:", 
   "program": 28725, 
   "servicename": "PHOENIX", 
   "pos": 28
  }, 
  {
   "servicereference": "1:0:1:7032:41B:1:C00000:0:0:0:", 
   "program": 28722, 
   "servicename": "ONE", 
   "pos": 29
  }, 
  {
   "servicereference": "1:0:1:7033:41B:1:C00000:0:0:0:", 
   "program": 28723, 
   "servicename": "EinsPlus", 
   "pos": 30
  }, 
  {
   "servicereference": "1:0:1:7031:41B:1:C00000:0:0:0:", 
   "program": 28721, 
   "servicename": "tagesschau24", 
   "pos": 31
  }, 
  {
   "servicereference": "1:0:1:3336:45B:1:C00000:0:0:0:", 
   "program": 13110, 
   "servicename": "ServusTV Deutschland", 
   "pos": 32
  }
 ], 
 "pos": 32
}`

And it seems that the webif returns some information

EDIT: I dint build it by my self I use the ubuntu repro for Kodi nightly build

**Comment by Matthias1992** [comment]
Hey all together, now I download kodi leia and build from the build instructions.
Then I copied the pvr-vuplus add on from "xbmc/build/addons" to ~/.kodi/addons
to get the new version and activate the debug logging level.
To my surprise it just worked fine now I was able to watch TV

**Comment by phunkyfish** [comment]
You must have had an old version of the addon.

**Comment by phunkyfish** [comment]
You had a very old version: pvr.vuplus v3.16.0

Current version is 3.22.0!
