### ISSUE TITLE
Tuner get queried every 10s

### ISSUE THREAD

**Issue by cdietrich86** [kodi-pvr/pvr.vuplus#217]
While tracking down an issue with my Sky CI+ module, I realised that the plugin queries the tuner info from OpenWebIf every 10s.
Is this necessary even when idling?

> 15:29:40.000 [e2-python] [OpenWebif] -D- tuner '0' 'Vuplus DVB-S NIM(45308X FBC)' 'Tuner A'
> 15:29:40.002 [e2-python] [OpenWebif] -D- tuner '1' 'Vuplus DVB-S NIM(45308X FBC)' 'Tuner B'
> 15:29:40.003 [e2-python] [OpenWebif] -D- tuner '2' 'Vuplus DVB-S NIM(45308X FBC)' 'Tuner C'
> 15:29:40.004 [e2-python] [OpenWebif] -D- tuner '3' 'Vuplus DVB-S NIM(45308X FBC)' 'Tuner D'
> 15:29:40.005 [e2-python] [OpenWebif] -D- tuner '4' 'Vuplus DVB-S NIM(45308X FBC)' 'Tuner E'
> 15:29:40.006 [e2-python] [OpenWebif] -D- tuner '5' 'Vuplus DVB-S NIM(45308X FBC)' 'Tuner F'
> 15:29:40.006 [e2-python] [OpenWebif] -D- tuner '6' 'Vuplus DVB-S NIM(45308X FBC)' 'Tuner G'
> 15:29:40.007 [e2-python] [OpenWebif] -D- tuner '7' 'Vuplus DVB-S NIM(45308X FBC)' 'Tuner H'
> 15:29:40.016   [e2-core] resolve: resolve ${libdir}/enigma2/python/Plugins/SystemPlugins/TransCodingSetup/plugin.pyo
> 15:29:40.017   [e2-core] resolve: -> /usr/lib/enigma2/python/Plugins/SystemPlugins/TransCodingSetup/plugin.pyo
> 15:29:50.068 [e2-python] [OpenWebif] -D- tuner '0' 'Vuplus DVB-S NIM(45308X FBC)' 'Tuner A'
> 15:29:50.070 [e2-python] [OpenWebif] -D- tuner '1' 'Vuplus DVB-S NIM(45308X FBC)' 'Tuner B'
> 15:29:50.071 [e2-python] [OpenWebif] -D- tuner '2' 'Vuplus DVB-S NIM(45308X FBC)' 'Tuner C'
> 15:29:50.072 [e2-python] [OpenWebif] -D- tuner '3' 'Vuplus DVB-S NIM(45308X FBC)' 'Tuner D'
> 15:29:50.073 [e2-python] [OpenWebif] -D- tuner '4' 'Vuplus DVB-S NIM(45308X FBC)' 'Tuner E'
> 15:29:50.074 [e2-python] [OpenWebif] -D- tuner '5' 'Vuplus DVB-S NIM(45308X FBC)' 'Tuner F'
> 15:29:50.074 [e2-python] [OpenWebif] -D- tuner '6' 'Vuplus DVB-S NIM(45308X FBC)' 'Tuner G'
> 15:29:50.075 [e2-python] [OpenWebif] -D- tuner '7' 'Vuplus DVB-S NIM(45308X FBC)' 'Tuner H'
> 15:29:50.084   [e2-core] resolve: resolve ${libdir}/enigma2/python/Plugins/SystemPlugins/TransCodingSetup/plugin.pyo
> 15:29:50.085   [e2-core] resolve: -> /usr/lib/enigma2/python/Plugins/SystemPlugins/TransCodingSetup/plugin.pyo
> 15:30:00.137 [e2-python] [OpenWebif] -D- tuner '0' 'Vuplus DVB-S NIM(45308X FBC)' 'Tuner A'
> 15:30:00.139 [e2-python] [OpenWebif] -D- tuner '1' 'Vuplus DVB-S NIM(45308X FBC)' 'Tuner B'
> 15:30:00.140 [e2-python] [OpenWebif] -D- tuner '2' 'Vuplus DVB-S NIM(45308X FBC)' 'Tuner C'
> 15:30:00.141 [e2-python] [OpenWebif] -D- tuner '3' 'Vuplus DVB-S NIM(45308X FBC)' 'Tuner D'
> 15:30:00.142 [e2-python] [OpenWebif] -D- tuner '4' 'Vuplus DVB-S NIM(45308X FBC)' 'Tuner E'
> 15:30:00.143 [e2-python] [OpenWebif] -D- tuner '5' 'Vuplus DVB-S NIM(45308X FBC)' 'Tuner F'
> 15:30:00.143 [e2-python] [OpenWebif] -D- tuner '6' 'Vuplus DVB-S NIM(45308X FBC)' 'Tuner G'
> 15:30:00.144 [e2-python] [OpenWebif] -D- tuner '7' 'Vuplus DVB-S NIM(45308X FBC)' 'Tuner H'
> 15:30:00.153   [e2-core] resolve: resolve ${libdir}/enigma2/python/Plugins/SystemPlugins/TransCodingSetup/plugin.pyo
> 15:30:00.154   [e2-core] resolve: -> /usr/lib/enigma2/python/Plugins/SystemPlugins/TransCodingSetup/plugin.pyo
> 15:30:14.000 [e2-python] next real activation isTue Apr 30 00:15:01 2019
> 15:31:53.001 [e2-python] next real activation isTue Apr 30 00:15:01 2019
> 15:33:33.000 [e2-python] next real activation isTue Apr 30 00:15:01 2019

**Comment by phunkyfish** [comment]
You can just switch off the signal quality checks in kodi pvr settings.

What’s the issue with this check happening?

**Comment by phunkyfish** [comment]
Also, are you running this directly on an Enigma2 device?

**Comment by cdietrich86** [comment]
Signal quality check is already disabled.
I see no problem with the request in general but I'm wondering if it is necessary while idling and what purpose it serves.

The plugin is enabled on Nvidia Shield querying my VU+ Uno 4k SE (latest VTI image, openwebif 1.2.8-vti-20181106-r0).

**Comment by cdietrich86** [comment]
Here are the calls from Kodi debug log:

> 2019-04-30 13:10:59.056 T:25998   DEBUG: AddOnLog: Enigma2 Client: pvr.vuplus - CheckHttp Check webAPI with URL: 'http://192.168.2.9:80/web/deviceinfo'
> 2019-04-30 13:10:59.057 T:25998   DEBUG: CurlFile::Open(0x2bddb3b280) http://192.168.2.9:80/web/deviceinfo
> 2019-04-30 13:10:59.128 T:25998   DEBUG: AddOnLog: Enigma2 Client: pvr.vuplus - CheckHttp WebAPI available
> 2019-04-30 13:11:03.338 T:26456   DEBUG: Thread JobWorker 26456 terminating (autodelete)
> 2019-04-30 13:11:09.129 T:25998   DEBUG: AddOnLog: Enigma2 Client: pvr.vuplus - CheckHttp Check webAPI with URL: 'http://192.168.2.9:80/web/deviceinfo'
> 2019-04-30 13:11:09.130 T:25998   DEBUG: CurlFile::Open(0x2bddb3b280) http://192.168.2.9:80/web/deviceinfo
> 2019-04-30 13:11:09.206 T:25998   DEBUG: AddOnLog: Enigma2 Client: pvr.vuplus - CheckHttp WebAPI available
> 2019-04-30 13:11:19.207 T:25998   DEBUG: AddOnLog: Enigma2 Client: pvr.vuplus - CheckHttp Check webAPI with URL: 'http://192.168.2.9:80/web/deviceinfo'
> 2019-04-30 13:11:19.208 T:25998   DEBUG: CurlFile::Open(0x2bddb3b280) http://192.168.2.9:80/web/deviceinfo
> 2019-04-30 13:11:19.282 T:25998   DEBUG: AddOnLog: Enigma2 Client: pvr.vuplus - CheckHttp WebAPI available
> 2019-04-30 13:11:29.283 T:25998   DEBUG: AddOnLog: Enigma2 Client: pvr.vuplus - CheckHttp Check webAPI with URL: 'http://192.168.2.9:80/web/deviceinfo'
> 2019-04-30 13:11:29.284 T:25998   DEBUG: CurlFile::Open(0x2bddb3b280) http://192.168.2.9:80/web/deviceinfo
> 2019-04-30 13:11:29.358 T:25998   DEBUG: AddOnLog: Enigma2 Client: pvr.vuplus - CheckHttp WebAPI available
> 2019-04-30 13:11:39.359 T:25998   DEBUG: AddOnLog: Enigma2 Client: pvr.vuplus - CheckHttp Check webAPI with URL: 'http://192.168.2.9:80/web/deviceinfo'
> 2019-04-30 13:11:39.360 T:25998   DEBUG: CurlFile::Open(0x2bddb3b280) http://192.168.2.9:80/web/deviceinfo
> 2019-04-30 13:11:39.433 T:25998   DEBUG: AddOnLog: Enigma2 Client: pvr.vuplus - CheckHttp WebAPI available

**Comment by phunkyfish** [comment]
That’s checking to see if the connection is still available to your enigma2 device. You can change the time in the advanced settings of the addon.

**Comment by phunkyfish** [comment]
If there is a better mechanism to check for liveness of WebIf happy to use that instead. But it would need to work for OpenWebIf and dreamos.

**Comment by cdietrich86** [comment]
Ah I understand.
However, the trigger seems to be 'Connection check timeout' rather than 'Connection check interval'.
I set interval=30s and still get the request every 10s.
When I change timeout to 20s, it appears every 20s.

Might they be interchanged?

Nevertheless, thank you very much for now. I will increase both values to the maximum.

**Comment by cdietrich86** [comment]
> If there is a better mechanism to check for liveness of WebIf happy to use that instead. But it would need to work for OpenWebIf and dreamos.

Maybe `/web/currenttime` is even more lightweight?

**Comment by phunkyfish** [comment]
If /web/currenttime works on dreamos then it’s possible.

Interval is the time between checks. Timeout is how long the connection waits before closing. Interval being longest and timeout short is the best combo. You shouldn’t really need to change timeout.

EDIT: /web/currenttime is on both platforms will change this in next release.

**Comment by phunkyfish** [comment]
You are also right on timeout, it should use interval and timeout is not even used!

I could set it to use a different interval when connected vs disconnected? 

EDIT: decided not to differentiate.

**Comment by phunkyfish** [comment]
#216 changes:
- Interval now correctly used, default to 10 seconds. 
- Timeout enabled and defaults to 30 seconds (but it should never need to be changed). 
- Also switched check to use /web/currenttime

**Comment by phunkyfish** [comment]
Interval now correctly used, default to 10 seconds. Timeout enabled and defaults to 30 seconds (but it should never need to be changed). Also switched check to use /web/currenttime

**Comment by cdietrich86** [comment]
Great work, thank you very much!
I think we can close this one now.
