### ISSUE TITLE
Deleting folder with recordings hangs Kodi

### ISSUE THREAD

**Issue by bservet** [kodi-pvr/pvr.vuplus#227]
It has already happened a couple of times to me that when I delete a couple of recordings, grouped into a folder by Kodi, Kodi keeps showing "working". So in the end I have to reboot the box and the receiver shows that the recordings have been deleted.

If not easily reproducible I can provide full debug logs. Please note that this OSMC box is running on 3.22 and not the latest release (not yet available). Thanks!

**Comment by phunkyfish** [comment]
Please do provide a full debug of the issue occurring and I’ll take a look.

**Comment by phunkyfish** [comment]
Also can you verify if it happens with only a single recording or does it require multiple to occur?

**Comment by bservet** [comment]
Until now it has only happened with multiple / folder deletions. Full debug log coming up later today.

**Comment by phunkyfish** [comment]
I didn’t manage to reproduce this yet. The largest recording folder I had to delete was 6 items.

**Comment by bservet** [comment]
No luck on the first try, but I reproduced it on the second try. The debug logs have been sent by PM as they didn't fit pastebin.

**Comment by phunkyfish** [comment]
Hmmm, there is no logging around delete’s so logs don’t help. I will continue to try to reproduce.

What happen’s in the background is that a delete recording call is made for each recording and for each recording the STB is queries for an updated set of recordings.

Can you try again but wait 10 minutes after it occurs to see if the addon recovers?

**Comment by phunkyfish** [comment]
Just need to figure out if it’s just a large queue of work that needs to finish or if it’s a locking issue that needs to be fixed.

**Comment by bservet** [comment]
I already waited for over 15m on one occasion if I remember correctly. So as far as I know that doesn't happen.

Earlier this morning I even got a crash / reboot. That didn't happen before.

It's a pity that the logs don't give any additional info.

**Comment by phunkyfish** [comment]
If I can repro the crash/reboot then it's easier to fix. How many recordings did you have in the folders?

**Comment by bservet** [comment]
I think was three. If I'm not mistaken the log also shows them with the names.

**Comment by phunkyfish** [comment]
Can you reproduce this on any other platform?

**Comment by bservet** [comment]
I tried it a couple of times on my PC but the deletion worked just as expected. Apart from running the 3.24 version of the Engima2 client, the Kodi version is also slightly different. I could also try it on my Vero 4K+ system. It's a slightly faster version of the system which has the problem. The software is the same.

The system hanging has happened quite a couple of times, the crash was a first so chances of that happening are rare.

EDIT: It was easily reproducible on my Vero4K (also on OSMC).

**Comment by phunkyfish** [comment]
The fix I've applied is likely the cause but as I can't reproduce you'll need to test this once it's available for your platform.

**Comment by ksooo** [comment]
@bservet can you supply stack traces for the hang? 

Do you have ssh access to the affected boxes and gdb installed there? 

If so, please ssh and enter `sudo gdb -p $(pidof kodi.bin) --batch -ex "thread apply all bt" > ./stacktraces.txt`

**Comment by phunkyfish** [comment]
@bservet so you will want to run that if possible when it's in a hang. It's an ARM based box so I'm not sure you'll have gdb.

**Comment by bservet** [comment]
OSMC runs on Debian and installing gdb wasn't a problem. I don't want to do everything remote via my phone so I'll post the results later today.

**Comment by bservet** [comment]
Here's the trace [https://pastebin.com/NwN3cCgz](url) , after a couple of minutes I pressed CTRL+C because the output stuck at 818 bytes. 

I've restarted the command and I'll check if anything happens after an hour or so.

**Comment by ksooo** [comment]
Thanks for the stacktraces. I see the problem and will try to come up with a fix for KODI core as soon as my time permits.

**Comment by bservet** [comment]
I'm glad that it gives the information needed! I ran a second trace (the machine was still "working" from the previous delete) but I guess it won't give any additional info. https://pastebin.com/ws2XB3gZ
