### ISSUE TITLE
need option to disable debug logging from this addon

### ISSUE THREAD

**Issue by M2k80** [kodi-pvr/pvr.vuplus#228]
hy,
i am again here because of logspam. this plugin does so much output if kodi debug logging is enabled that make it so hard to read the debug log and find informations. i have actually ~10 lines per second from this plugin.
i just wanted to open an issue on kodi git because my amazon 4k stick has problems with the stream of pvr.vuplus, after some minutes the stream stop, it try 1x to buffer and end with freezed picture. its so hard to see what happens, because of so much output from this plugin.
and just after some minutes it about 1.5mb file size - and i think 1mb is only from this plugin

look at my log, i have to upload it somewhere because its too big
https://www.myqnapcloud.com/smartshare/6d8064hjnp2m26729v47308d_6jzF6VI

**Comment by M2k80** [comment]
Could you please clear up, if my problem is related to this plugin oder kodi core?
I thought its kodi core.
https://github.com/xbmc/xbmc/issues/16180

**Comment by phunkyfish** [comment]
So you want an option to ignore debug output from the addon so the only debug is from kodi?

**Comment by phunkyfish** [comment]
BTW, this is a worthwhile feature, and most of the work is already in place for this. The biggest piece of work is cleaning up the options in settings, might take few days to get it done.

**Comment by M2k80** [comment]
yes, it would be good, if we could decide if we want debug output from the plugin or not.
actually its very hard to read the kodi debug log.
maybe you saw my issue on github, link is in the second post, peak3k also asked me if can disable addon logging for better log reading.

and pls would you take a look at my issue, its actually marked as closed, because they say my problem is related to this plugin.

**Comment by ksooo** [comment]
> actually its very hard to read the kodi debug log.

grep -i -v "pvr.vuplus" debug.log

is your friend.

No need for even more settings which only bloat settings UI and addon code.

**Comment by M2k80** [comment]
in the meanwhile the plugin has so much settings and many of them i will never need and one option more to disable debug logging cant be so worse :)
my personal opinion is, addon debug logging should be only enabled if its needed, because if someone is using this plugin, but is searching for other problems, he has to do for every log grep -i -v "pvr.vuplus" debug.log like ksooo said.
but ok its not my decision, i am not a dev, so do what you think what is right for the plugin - you make a very good job here - i think many users are very happy that someone is working on the plugin
peak3d asked me to disable addon logging for better readings - so other devs seems to want it too.

**Comment by ksooo** [comment]
> in the meanwhile the plugin has so much settings and many of them i will never need ...

 This is absolutely no reason for making it even worse.

> peak3d asked me to disable addon logging for better readings - so other devs seems to want it too.

 and I do not understand this. I prefer "huge" debug logs with "everything" in it, because then I can decide what I want to see and what not. IMO, every dev should be familiar with "grep". It's a mighty standard tool. But maybe I'm just old-school. ;-)

**Comment by M2k80** [comment]
just only a last word,
kodi is a big program with many components etc, its round about 63mb, but compared to the plugin, the plugin does 90 percent more debug output than kodi. if every plugin would do that, your debug log would in 1min about 100mb or more.
its same like my issue on kodi that i have reported, they said my problem is not a kodi core problem.
a plugin is not kodi core too and should not use more output then kodi itself if its not needed - or better, the addon output should be able to get disabled.

> I prefer "huge" debug logs with "everything" in it

realy? then ok, remove all component logging switches from kodi core and let kodi output all stuff all the time. that is what you realy want? i cant believe. lol

dont get me wrong, and dont be mad now
hartnäckig und stur - typical german (with a smile) i like
have a nice day
