### ISSUE TITLE
Connection not possible if HTTPS is used

### ISSUE THREAD

**Issue by 00178003** [kodi-pvr/pvr.vuplus#249]
Hi,
1st of all thks and congrats for the amazing add-on... it's been great using in all of my house several room Kodi units (Rasps/PC) connected to my main Enigma2 Box.
Now the thing is I want to connect it to outside my home, to be able to stream to my mobile when I'm out, and as such I had to enable HTTPS and Login for obvious security reasons.
The problem is that in this case I cannot sync the PVR plug in with the enigma box... from code and logs it's a clear https thing... I simply copy/paste the link in the logs that is stated to be unreacheable it works bt pops up the login/pass pop-up window... it does NOT allow to be used in the link itself...
Bit of log that shows it (hid login/pass) further below.
The plug-in runs perfectly when no http login or https is selected in Webif interface settings.
I suspect it's the way the login method is requested by the box... the add-on uses it on the weblink itself whilst if I try in a browser the same link (with login and pass in it) it always pops-up requesting to input login/pass...
Any help is appreciated. Thks

Rui

2019-09-19 02:57:41.931 T:12408  NOTICE: Running the application...
2019-09-19 02:57:41.937 T:2036  NOTICE: ES: Starting UDP Event server on port 9777
2019-09-19 02:57:41.938 T:2036  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
2019-09-19 02:57:42.193 T:10492   ERROR: AddOnLog: Joystick Support: Device "Sony Interactive Entertainment Wireless Controller": can't find <controller> tag
2019-09-19 02:57:42.207 T:10492  NOTICE: PERIPHERALS::CPeripheralAddon::Register - new joystick device registered on addon->peripheral.joystick/0: Xbox 360-compatible controller
2019-09-19 02:58:12.236 T:9920   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
2019-09-19 02:58:12.236 T:9920   ERROR: CCurlFile::Open failed with code 0 for https://192.168.1.5:50010/web/currenttime:
2019-09-19 02:58:12.236 T:9920   ERROR: AddOnLog: Enigma2 Client: pvr.vuplus - enigma2::ConnectionManager::Process - unable to connect to: https://<login>:<pass>@192.168.1.5:50010/web/currenttime
2019-09-19 02:58:12.236 T:9920  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - Enigma2::ConnectionLost Lost connection with Enigma2 device...

**Comment by phunkyfish** [comment]
Note that Enigma2 devices are not that secure on the internet. Really you should just create a VPN from your router and connect to that when remote on mobile or laptop.

I assume you have set a username and password in settings? Also, that’s a local IP address in the log, it must be your WAN IP address used if connecting remotely (a static IP is better), or some kind of dynamic DNS service.

**Comment by phunkyfish** [comment]
Not that supplying a full debug log helps speed thus process up. Remember to use a paste service post the link.

**Comment by 00178003** [comment]
Hi phunkyfish,

Thks for the quick reply. 
1st LET ME CORRECT THE ISSUE: it's ONLY in HTTPS case. I've retested with HTTP and works fine, ONLY when enabling HTTPS options and configuring add-on (after HTTP is working OK) do I have the problem. So it seems related to HTTPS only (corrected the title already accordingly)

I aknowledge that VPN would be the best solution from security perspective, but also has its drawbacks from my experience (actually still using it for a particular type of access): performance, anoying 1st VPN login when you want quick access sometimes, stability (if your web access is poor VPN can drop).
From my last +5Y experience with several other applications and Webif HTTPS+login+using non-default ports+full FireWall router side (only open a few ports)+record of accesses regularly monitored its a good compromise from security perspective.
So I want to keep the access to my E2 channels from outside world quick a simple: I have 2 options here:
1) keep the same way -> problem in inside LAN Kodi's reported with this issue
2) somekind of a middle-man with authentication -> need to develop and could be an oppotunity to include a transcoding function in it along

As to your other questions (bear in mind that I have the setup fully working in HTTPS accessible from anywhere in the internet for a few years now..) 
1) User/pass : yes, of course, I've just hidden them in the log.. actually I understand your question after looking to what is presented in the page: I've put them inside '<' and '>' to be more obvious for you but it seems to be deleted in the HTML presentation :)... but yes they were used of course
2) Internal LAN was used 1st to avoid extra variables during intial tests, till the setup is fully running (actually that's how I've detected the issue...) Step 1-LAN+no auth OK Step2-LAN+Auth NOK Step3-Internet+Auth, for this case I'm using a DDNS option working perfectly for several years now, as stated

Later on today I'll collect the full log with debug on+PVR debug on and send it to you along with E2 and WebIf version
Thks
Rui

**Comment by phunkyfish** [comment]
Ok, that all makes sense.

So you can curl to the URL from a laptop or PC?

**Comment by 00178003** [comment]
Hi,

confirmed to be a curl issue along with certificates... (check curl tests outputs further below).
I did a step by step procedure as per below and confirmed to be a curl SSL certificate check problem. Please check my debugging below.
Thks in advance

**=== Step 1 ===**
Webif settings:
	http 50011 & https 50010 enabled in Webif
	require client cert for https - set to No
Status:
In PC web browser:
	Both HTTP and HTTPS accessible OK from PC web browser! (with same user:passwd)
In Kodi PVR Add-on: 
	a) HTTP works OK!
	b) HTTPS fails due to certificate (simply chg port # and enabled HTTPS to ON in Add-on settings)
		DEBUG: Curl::Debug - TEXT: SSL certificate problem: self signed certificate

**So curl was the issue...** tested from another machine and in fact curl could not reach E2 box

**=== Step 2 ===**
Since curl is the issue in accessing due to certificates I've created a new one self signed and add it in E2 box /etc/enigma2
Also put it in my testing curl machine
Webif settings:
	http 50011 & https 50010 enabled in Webif
	require client cert for https - set to No
Status:
In PC web browser:
	Both HTTP and HTTPS accessible OK from PC web browser! (with same user:passwd) but with HTTPS NET::ERR_CERT_AUTHORITY_INVALID that I can proceed in Chrome
In curl testing machine Pi: 
	simple HTTPS could also not go through, now due to EE certificate too weak :(
	by overridding the certificate check (-k option) connection is OK! confirming certificates to be the issue...
	Please check webpage mentioned by curl error: https://curl.haxx.se/docs/sslcerts.html

**Not sure if anything can be done here?! would it be possible to add the -k option in the add-on?**

```
pi@Pi4Server:~` $ curl -v https://myUser:myPass@192.168.1.5:50010/web/currenttime
* Expire in 0 ms for 6 (transfer 0x8007c0)
*   Trying 192.168.1.5...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x8007c0)
* Connected to 192.168.1.5 (192.168.1.5) port 50010 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, bad certificate (554):
* SSL certificate problem: EE certificate key too weak
* Closing connection 0
curl: (60) SSL certificate problem: EE certificate key too weak
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

pi@Pi4Server:~ $ curl -v -k https://myUser:myPass@192.168.1.5:50010/web/currenttime
* Expire in 0 ms for 6 (transfer 0xa1c7c0)
*   Trying 192.168.1.5...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0xa1c7c0)
* Connected to 192.168.1.5 (192.168.1.5) port 50010 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: OU=vuduo2; CN=vuduo2; O=Home
*  start date: Sep 20 02:26:54 2019 GMT
*  expire date: Sep 18 02:26:54 2024 GMT
*  issuer: OU=vuduo2; CN=vuduo2; O=Home
*  SSL certificate verify result: EE certificate key too weak (66), continuing anyway.
* Server auth using Basic with user 'myUser'
> GET /web/currenttime HTTP/1.1
> Host: 192.168.1.5:50010
> Authorization: Basic cm9vdDpNYXhpMjAxNw==
> User-Agent: curl/7.64.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Date: Fri, 20 Sep 2019 02:33:13 GMT
< Content-Type: text/xml
< Server: TwistedWeb/16.4.0
< Set-Cookie: TWISTED_SECURE_SESSION=d73b3aa6c6c817d055f80a6cdffbf335b9355bdf6d01bf8a5ba0e101b140e020; Path=/; Secure
<
<?xml version="1.0" encoding="UTF-8"?>
<e2currenttime>
         3:33:13
</e2currenttime>
* Connection #0 to host 192.168.1.5 left intact

pi@Pi4Server:~ $ curl -v --cacert /mnt/Pi4Share/my_certs/ca.pem https://myUser:myPass@192.168.1.5:50010/web/currenttime
* Expire in 0 ms for 6 (transfer 0x1e017c0)
*   Trying 192.168.1.5...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x1e017c0)
* Connected to 192.168.1.5 (192.168.1.5) port 50010 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /mnt/Pi4Share/my_certs/ca.pem
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, bad certificate (554):
* SSL certificate problem: EE certificate key too weak
* Closing connection 0
curl: (60) SSL certificate problem: EE certificate key too weak
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

pi@Pi4Server:~ $ openssl s_client -showcerts -servername 192.168.1.5 -connect 192.168.1.5:50010
CONNECTED(00000003)
depth=0 OU = vuduo2, CN = vuduo2, O = Home
verify error:num=66:EE certificate key too weak
verify return:1
depth=0 OU = vuduo2, CN = vuduo2, O = Home
verify error:num=18:self signed certificate
verify return:1
depth=0 OU = vuduo2, CN = vuduo2, O = Home
verify return:1
---
Certificate chain
 0 s:OU = vuduo2, CN = vuduo2, O = Home
   i:OU = vuduo2, CN = vuduo2, O = Home
-----BEGIN CERTIFICATE-----
MIIB1DCCAT0CBF2EOO4wDQYJKoZIhvcNAQEFBQAwMTEPMA0GA1UECwwGdnVkdW8y
MQ8wDQYDVQQDDAZ2dWR1bzIxDTALBgNVBAoMBEhvbWUwHhcNMTkwOTIwMDIyNjU0
WhcNMjQwOTE4MDIyNjU0WjAxMQ8wDQYDVQQLDAZ2dWR1bzIxDzANBgNVBAMMBnZ1
ZHVvMjENMAsGA1UECgwESG9tZTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEA
mjS+MHjm7vFhZzj/cYHowgA4tvfp06s0jpmX1UAKREXscA1oAz5C4S6ceQpqXoGH
o4lsy9hCpcDDGgGJiKbrJheEzPk8PPSUTfOWyvJoVo/WqB2RTzItAja3gj7YWdqK
4M/Tiy1eAMQCeHmOhmxqWIv+oHQyFg6BPqalmrujqwkCAwEAATANBgkqhkiG9w0B
AQUFAAOBgQACAZAwwt92y7ypWZ4OXU11JtCvU757/O3WIoOOFHNaN+4t4BDUBc9V
WKtzYQQXOK+tG0HqzEdX6ziDRCgVbJEoou39RoUawoAbdh4ThK05ItO0olhgiOMP
Wur1hd8gA5boR+zHdpux85TlVU23Fn2ZcDqIPs8c6pn9WfujNaGgzA==
-----END CERTIFICATE-----
---
Server certificate
subject=OU = vuduo2, CN = vuduo2, O = Home

issuer=OU = vuduo2, CN = vuduo2, O = Home

---
No client certificate CA names sent
---
SSL handshake has read 796 bytes and written 493 bytes
Verification error: self signed certificate
---
New, TLSv1.2, Cipher is AES256-GCM-SHA384
Server public key is 1024 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AES256-GCM-SHA384
    Session-ID: B316A7F10269641F1AE7FE966C24D4EFA6659D338CC59282435B6A5211B964A0
    Session-ID-ctx:
    Master-Key: BFB563C55C0BC2D908329D5AE3E5E682160569AB8415BE997DB9AF4B8DF2F8966C45A8101FB1E2F72E82B988008672EE
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - 17 1a d1 32 71 70 d1 bd-81 cc c6 3d 60 62 a0 4f   ...2qp.....=`b.O
    0010 - d7 cd 7e e5 dc 2e 13 50-9c 48 9b e2 52 16 b5 29   ..~....P.H..R..)
    0020 - da dd 90 26 96 b0 1f 7f-e9 6a 40 bb 68 00 a7 c5   ...&.....j@.h...
    0030 - 88 26 e6 5a 47 79 19 a8-ba c4 42 fa b0 c0 39 fb   .&.ZGy....B...9.
    0040 - 44 e9 e1 04 44 e2 c4 46-34 98 c4 c1 4c e0 13 08   D...D..F4...L...
    0050 - ea 72 a9 52 a5 74 11 fe-39 6b 51 0c 48 33 10 3a   .r.R.t..9kQ.H3.:
    0060 - 4f e5 12 f2 a3 dd 4f 9a-52 f5 7a 06 62 64 d8 da   O.....O.R.z.bd..
    0070 - 34 a3 4a 3d fd 8e fb 81-bc c6 27 a5 77 4d 8f 0e   4.J=......'.wM..
    0080 - bc 20 50 ab ed aa 01 ea-d9 a9 26 85 7e b1 53 2c   . P.......&.~.S,
    0090 - ff 09 75 4b 10 4e 58 2b-90 4b 44 e6 04 69 ac 25   ..uK.NX+.KD..i.%
    00a0 - ba 65 aa 9a 15 30 79 8a-ba 41 f2 09 00 89 81 c1   .e...0y..A......

    Start Time: 1568946823
    Timeout   : 7200 (sec)
    Verify return code: 18 (self signed certificate)
    Extended master secret: no
---
```

**Comment by phunkyfish** [comment]
This is because kodi will only allow a valid cert. It won’t accept self signed.

Just purchase a real cert from namecheap, I think they cost like $10 a year.

**Comment by phunkyfish** [comment]
Or even better, free certs from https://letsencrypt.org

Also found this on the forum:
```
you have to add your server cert to kodi's cert store: [install_dir]\system\certs\cacert.pem
Alternatively, you can provide your own Cert file, by setting the env var SSL_CERT_FILE
```

Here: https://forum.kodi.tv/showthread.php?tid=331918

**Comment by 00178003** [comment]
Hi
Actually it can accept self signed... curl was the one thing anoying and could not verify the alternative names... I've put it fully working now with a new self signed certificate with a simple definition in etc/hosts :)...
As you can see below, in a previous curl self signed cert test it was rejecting it due to me accessing by IP vs. cert checking by name:
```
*  subject: C=PT; ST=Porto; L=Porto; O=Private; OU=VuDuo2; emailAddress=myEmail@provider.com; CN=vuduo2
*  start date: Sep 20 18:08:20 2019 GMT
*  expire date: Sep 17 18:08:20 2029 GMT
*  **subjectAltName does not match 192.168.1.5**
* **SSL: no alternative certificate subject name matches target host name '192.168.1.5'**
* Closing connection 0
```
Now simple defining in /etc/hosts the IP of my E2 box with the same name as the Distinguished Name defined when generating the certificate, in the machine I was testing/curling from did the trick!
Check further below the same command trying to access/curling the E2 box via 2 ways: via IP (NOK) and via its already defined name in etc/hosts (OK). This way it would match the subject name defined in the CA certificate.

After this was working, yes, I could then define the associated CA that I've used/generated self signed cert and include it at the end of [install_dir]\system\certs\cacert.pem file... 

After that... **VOILÁ!! I can now access the E2 Box via HTTPS in Kodi via the PVR add-on and with certificate check!**

Many thanks for the discussions and sorry to open up an issue that in fact was not an issue with your great add-on! Keep up the fantastic work!

```
pi@Pi4Server:~ $ curl -v --cacert /mnt/Pi4Share/Fix_certs/ca.pem https://myUser:myPass@192.168.1.5:50010/web/currenttime
* Expire in 0 ms for 6 (transfer 0x174e7c0)
*   Trying 192.168.1.5...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x174e7c0)
* Connected to 192.168.1.5 (192.168.1.5) port 50010 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /mnt/Pi4Share/Fix_certs/ca.pem
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=PT; ST=Porto; L=Porto; O=Private; OU=VuDuo2; emailAddress=myEmail@provider.com; CN=vuduo2
*  start date: Sep 20 18:08:20 2019 GMT
*  expire date: Sep 17 18:08:20 2029 GMT
*  subjectAltName does not match 192.168.1.5
* SSL: no alternative certificate subject name matches target host name '192.168.1.5'
* Closing connection 0
curl: (60) SSL: no alternative certificate subject name matches target host name '192.168.1.5'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

pi@Pi4Server:~ $ ping vuduo2
PING vuduo2 (192.168.1.5): 56 data bytes
64 bytes from 192.168.1.5: icmp_seq=0 ttl=64 time=3.416 ms
64 bytes from 192.168.1.5: icmp_seq=1 ttl=64 time=3.405 ms
64 bytes from 192.168.1.5: icmp_seq=2 ttl=64 time=3.793 ms
--- vuduo2 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max/stddev = 3.405/3.538/3.793/0.180 ms

pi@Pi4Server:~ $ curl -v --cacert /mnt/Pi4Share/Fix_certs/ca.pem https://myUser:myPass@vuduo2:50010/web/currenttime
* Expire in 0 ms for 6 (transfer 0x9847c0)
* Expire in 1 ms for 1 (transfer 0x9847c0)
* Expire in 0 ms for 1 (transfer 0x9847c0)
* Expire in 1 ms for 1 (transfer 0x9847c0)
* Expire in 0 ms for 1 (transfer 0x9847c0)
* Expire in 0 ms for 1 (transfer 0x9847c0)
* Expire in 2 ms for 1 (transfer 0x9847c0)
* Expire in 0 ms for 1 (transfer 0x9847c0)
* Expire in 0 ms for 1 (transfer 0x9847c0)
* Expire in 2 ms for 1 (transfer 0x9847c0)
* Expire in 0 ms for 1 (transfer 0x9847c0)
* Expire in 0 ms for 1 (transfer 0x9847c0)
* Expire in 0 ms for 1 (transfer 0x9847c0)
*   Trying 192.168.1.5...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x9847c0)
* Connected to vuduo2 (192.168.1.5) port 50010 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /mnt/Pi4Share/Fix_certs/ca.pem
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=PT; ST=Porto; L=Porto; O=Private; OU=VuDuo2; emailAddress=myEmail@provider.com; CN=vuduo2
*  start date: Sep 20 18:08:20 2019 GMT
*  expire date: Sep 17 18:08:20 2029 GMT
*  subjectAltName: host "vuduo2" matched cert's "vuduo2"
*  issuer: C=PT; ST=Porto; L=Porto; O=Private; OU=VuDuo2; CN=vuduo2; emailAddress=myEmail@provider.com
*  SSL certificate verify ok.
* Server auth using Basic with user 'myUser'
> GET /web/currenttime HTTP/1.1
> Host: vuduo2:50010
> Authorization: Basic cm9vdDpNYXhpMjAxNw==
> User-Agent: curl/7.64.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Date: Fri, 20 Sep 2019 18:22:04 GMT
< Content-Type: text/xml
< Server: TwistedWeb/16.4.0
< Set-Cookie: TWISTED_SECURE_SESSION=4628d1a51168586b733793e46af8827df25d3f890a12a3f9f16bc30a1abce96f; Path=/; Secure
<
<?xml version="1.0" encoding="UTF-8"?>
<e2currenttime>
        19:22:04
</e2currenttime>
* Connection #0 to host vuduo2 left intact
```

**Comment by phunkyfish** [comment]
No problem, happy you got it working.
