### ISSUE TITLE
enigma2 playing radiochannels in kodi results in jittered sound

### ISSUE THREAD

**Issue by rvgestel** [kodi-pvr/pvr.vuplus#26]
When playing radio channels from satellite tuner (vusolo2 running enigma2), the pvr addon vuplus creates interruptions in the sound stream. This results in drops in the sound stream. Oher clients playing the same stream in the same LAN do play the stream flawlessly. This issue arose since version 15 for Kodi.
The sound and movie in tv channels are played flawlessly by the add-on from the same satellite tuner, hence, it looks like an audio codec issue. Maybe increasing buffersize suffices.

**Comment by hudokkow** [comment]
I'm not experiencing the same problems. Debug log, please. See http://kodi.wiki/view/Log_file

**Comment by rvgestel** [comment]
Run the debugging and found the error is already known. 

http://trac.kodi.tv/ticket/16240

 

The ticket is correct, there is a failing sync condition causing the stuttering. It was not there in version 14.2 and I also got it when switching to kodi version 15.

 

….CDVDPlayerAudio::OutputPacket skipping a packets of duration 24

15:37:28 T:140502389217024  NOTICE: Previous line repeats 3 times.

15:37:28 T:140502389217024   DEBUG: CDVDPlayerAudio::HandleSyncError - average error -25941.543183 below threshold of 50000.000000

15:37:28 T:140502389217024   DEBUG: CDVDClock::Discontinuity - CDVDPlayerAudio::HandleSyncError2 - was:38450813010.187668, should be:38450787070.552483, error:-25939.635185

15:37:29 T:140502389217024   DEBUG: CDVDClock::Discontinuity - CDVDPlayerAudio::HandleSyncError2 - was:38451811015.429482, should be:38451823455.644783, error:12440.215302

15:37:35 T:140502389217024 WARNING: CDVDMessageQueue(audio)::Get - asked for new data packet, with nothing available

15:37:35 T:140502801315584   DEBUG: audio stream stalled. start buffering

15:37:35 T:140502801315584   DEBUG: CDVDPlayer::SetCaching - caching state 2

15:37:35 T:140502801315584 WARNING: CDVDMessageQueue(video)::Put MSGQ_NOT_INITIALIZED

15:37:35 T:140502389217024 WARNING: Previous line repeats 1 times.

15:37:35 T:140502389217024   DEBUG: CDVDPlayerAudio - CDVDMsg::GENERAL_SYNCHRONIZE

15:37:35 T:140502801315584   DEBUG: CDVDPlayer::HandleMessages - player started 1

15:37:35 T:140503693211520   DEBUG: ------ Window Init (DialogSeekBar.xml) ------

15:37:35 T:140502801315584   DEBUG: set caching from pvr to done. audio (1) = 11. video (0) = 0

15:37:35 T:140502801315584   DEBUG: CDVDPlayer::SetCaching - caching state 0

15:37:35 T:140502389217024   DEBUG: CDVDPlayerAudio - CDVDMsg::GENERAL_RESYNC(38458360033.333328, 1)

15:37:35 T:140503693211520   DEBUG: ------ Window Deinit (DialogSeekBar.xml) ------

15:37:36 T:140502389217024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 24

15:37:36 T:140502389217024  NOTICE: Previous line repeats 3 times.

15:37:36 T:140502389217024   DEBUG: CDVDPlayerAudio::HandleSyncError - average error -12773.144724 below threshold of 50000.000000

15:37:36 T:140502389217024   DEBUG: CDVDClock::Discontinuity - CDVDPlayerAudio::HandleSyncError2 - was:38458360048.283325, should be:38458347276.583603, error:-12771.699722

15:37:43 T:140502389217024 WARNING: CDVDMessageQueue(audio)::Get - asked for new data packet, with nothing available

15:37:43 T:140502801315584   DEBUG: audio stream stalled. start buffering

 

 

Van: Cristiano A. Silva [mailto:notifications@github.com] 
Verzonden: zaterdag 19 september 2015 23:14
Aan: kodi-pvr/pvr.vuplus
CC: rvgestel
Onderwerp: Re: [pvr.vuplus] enigma2 playing radiochannels in kodi results in jittered sound (#26)

 

I'm not experiencing the same problems. Debug log, please. See http://kodi.wiki/view/Log_file

**Comment by rvgestel** [comment]
Found this topic:

http://forum.kodi.tv/showthread.php?tid=203365

I also use an Inte NUC, just as the publisher of this topic.

 

Checked the switches, netgear switch restarted and audio is fine J. Problem solved.

Pfff, so many hours spent, but probably ticket http://trac.kodi.tv/ticket/16240 can be closed as well because of network issues.

 

 

Van: Cristiano A. Silva [mailto:notifications@github.com] 
Verzonden: zaterdag 19 september 2015 23:14
Aan: kodi-pvr/pvr.vuplus
CC: rvgestel
Onderwerp: Re: [pvr.vuplus] enigma2 playing radiochannels in kodi results in jittered sound (#26)

 

I'm not experiencing the same problems. Debug log, please. See http://kodi.wiki/view/Log_file

**Comment by rvgestel** [comment]
Last research on this topic. If I switch radio channel in kodi, the jittering sound returns! 

If I turn off/on one of the switches (there is 3 in between the vusolo2 pvr and openelec NUC), the problem is gone.

 

Apparently there is something related to network traffic and synchronisation which is different from version 14. Kodi seems more sensitive to this in version 15. 

It only occurs on radio channels, watching tv channels causes no jutter, so I assume it still remains a kodi issue which is only noticeable when there are enough switches in the line.

 

Van: Cristiano A. Silva [mailto:notifications@github.com] 
Verzonden: zaterdag 19 september 2015 23:14
Aan: kodi-pvr/pvr.vuplus
CC: rvgestel
Onderwerp: Re: [pvr.vuplus] enigma2 playing radiochannels in kodi results in jittered sound (#26)

 

I'm not experiencing the same problems. Debug log, please. See http://kodi.wiki/view/Log_file

**Comment by rvgestel** [comment]
If buffering is adapted in the advanced settings for kodi, the issue can be improved. The error is still there, but only visible in the kodi.log. The jittering is not observed in the audio stream. Unfortunately, switching channels now takes more time, because of the buffering.

CDVDPlayerAudio::HandleSyncError - average error 3278.291944 below threshold of 50000.000000
09:11:51 T:140087602087808   DEBUG: ------ Window Deinit (DialogSeekBar.xml) ------
09:11:52 T:140087548192512   DEBUG: CDVDClock::Discontinuity - CDVDPlayerAudio::HandleSyncError2 - was:66498892815.169884, should be:66498879749.242386, error:-13065.927498


<advancedsettings>
    <musiclibrary>
        <cleanonupdate>true</cleanonupdate>
    </musiclibrary>
  <pvr>
      <timecorrection>0</timecorrection>  
      <infotoggleinterval>3000</infotoggleinterval>  
      <minaudiocachelevel>100</minaudiocachelevel> 
      <cacheindvdplayer>true</cacheindvdplayer> 
      <channeliconsautoscan>true</channeliconsautoscan> 
      <autoscaniconsuserset>false</autoscaniconsuserset> 
      <numericchannelswitchtimeout>1000</numericchannelswitchtimeout> <!-- Time in ms before the numeric dialog auto closes when confirmchannelswitch is disabl
    </pvr>
</advancedsettings>

**Comment by phunkyfish** [comment]
@rvgestel does this still happen in the latest version of kodi? This doesn't look like an addon issue, more to do with Kodi itself.

**Comment by Jalle19** [comment]
Yeah this was originally a Kodi issue but it should be fixed

**Comment by phunkyfish** [comment]
Ok, will close so ;)
