### ISSUE TITLE
Loading channels in last version of DreamOS is not possible

### ISSUE THREAD

**Issue by palik42** [kodi-pvr/pvr.vuplus#266]
Hi,
my setup:
Enigma2 Client 4.9.3.1
Dreambox 920, Newnigma 2 and Dream-Elite image.. both are DreamOS OE2.5
They've changed something in this year and I am not able to fetch channel list from receiver.. (multiple or single ) 
when I've tried to fetch with different application(android) it ask me to sign certificate (like ssh cert in putty)

**Comment by phunkyfish** [comment]
Can you supply a full debug log using a paste site?

I‘m afraid I have no access to a dreamos device or newnigma 2.

**Comment by palik42** [comment]
I've found workaround for this issue. 
Now is automatically enabled setup (of Webinterface):
Simple Anti-Hijack Measures (may break clients) 
Token-based security (may break clients) 

After disable of them your plugin is now working.
(Maybe you can provide information do readme for DreamOS.)

I've disabled both of them. 
I can provide you log, but where I can find it or how can get it?

**Comment by phunkyfish** [comment]
Do you have any details on what both items mean? Anti hijack measures could mean anything.

I can add the that detail to the readme in a future release.

**Comment by palik42** [comment]
Sorry I don't know I am just user :( .. 
maybe you can find something here: 
[https://github.com/opendreambox/enigma2-plugins/tree/master/webinterface](https://github.com/opendreambox/enigma2-plugins/tree/master/webinterface)

[https://github.com/opendreambox/enigma2-plugins/blob/master/webinterface/src/webif.py](https://github.com/opendreambox/enigma2-plugins/blob/master/webinterface/src/webif.py)

**Comment by phunkyfish** [comment]
Ok, maybe easier to just leave it as the descriptions you have given.

Do you have to disable both options or will it work with only one disabled.

**Comment by palik42** [comment]
I've found log [here](http://ix.io/250s)
Problem is only with Token-based security enabled.

**Comment by phunkyfish** [comment]
Ya, you get a 412 which means the request needs something else to complete which must be the token.

**Comment by palik42** [comment]
Token-based security enabled:
http://192.168.1.41/web/currenttime:
412 - Precondition failed!
sessionid is missing, invalid or expired!
_____________________________________________________
Token-based security disabled:
http://192.168.1.41/web/currenttime
< e2currenttime >15:00:39< /e2currenttime>

**Comment by phunkyfish** [comment]
Solution: https://github.com/kodi-pvr/pvr.vuplus/issues/308
