### ISSUE TITLE
Is't possible to  activate hdr (HLG) during streaming UHD with HLG broadcasting?

### ISSUE THREAD

**Issue by kokikoku** [kodi-pvr/pvr.vuplus#267]
I found Kodi can play hdr video and activate hdr correctly. Is't possible to  activate hdr (HLG) during streaming UHD with HLG broadcasting by enimga2 addon? I will try video recorded from UHD channel to confirm if HLG can activate with Kodi later.

**Comment by kokikoku** [comment]
Just confirmed, same channel, when I play the channel by recorded video, HLG was activated correctly; but when the channel streamed by Enigma Client, HLG can't be activated.

**Comment by phunkyfish** [comment]
Ok, I’m not quite sure how to debug this one!

**Comment by phunkyfish** [comment]
Do you have a full debug log of one vs the other?

**Comment by kokikoku** [comment]
I'm sorry I can't make judgement there is no HDR activated just because of addon problem. I recorded the UHD channel by myself and made an analysis, no HDR info broadcasted, maybe local CATV bureau reason HDR not be transferred. Anyway, I paste the log for your reference.
https://paste.kodi.tv/penosoqiri

including 3 actions

1. same channel including HLG record shared by others
2 local same channel without HLG recorded by myself
3 live streaming local same channel

**Comment by phunkyfish** [comment]
How did you make the recording? Was it recorded on the Enigma2 device?

**Comment by kokikoku** [comment]
I recorded by VLC streaming in windows 10.

**Comment by kokikoku** [comment]
VLC streaming from Enigma2 Set-top Box.

**Comment by phunkyfish** [comment]
Ok, and if you record using kodi and play it back does the recording work correctly using HLG?

**Comment by kokikoku** [comment]
I don't know how to record with Kodi, I tried to press the record button but it seemed no action to be done and didn't find record file. I made a feedback for the parameter problem to CATV bureau, I hope they make some adjustment in frontend.

**Comment by phunkyfish** [comment]
You can't record because your E2 image is quite old. You really should upgrade. OpenWebIf latest version is 1.3.8, you image is from 2017.

Can you post the output of: `http://<your-e2-ip>/web/deviceinfo`?

**Comment by phunkyfish** [comment]
You may not have a HDD for recordings on your E2 device which may be why you can't record.

**Comment by kokikoku** [comment]
Yes, my image is old. You can check my device model, image version and OpenWebif version from Kodi log I pasted above. I will make upgrade later.

**Comment by phunkyfish** [comment]
Do you have a HDD installed?

**Comment by kokikoku** [comment]
I used to record by mounting HDD before. If need, I can record from set-top box directly, that's no problem. I just think Kodi record should save in PC. The CATV bureau called me yesterday, they confirmed the frontend parameter is correct. I must make further anlysis,  including record according to your recommendation.

**Comment by phunkyfish** [comment]
Kodi will never record to pc. Recording is a function of backend system, in your case, the Enigma2 STB.

**Comment by kokikoku** [comment]
The Enigma2 Client activates HLG normally and synchronizes auto frame rate. The CATV bureau said the parameter is correct, in fact they corrected the parameter from my understanding. Same VLC streaming in windows, I found the media info changed to ITU-R BT.2020 log-gamma hybrid instead of ITU-R BT.709.

**Comment by phunkyfish** [comment]
So it works?

**Comment by kokikoku** [comment]
Yeah, it works ,no need any work for the plugin. Thanks.
