### ISSUE TITLE
Connection via https

### ISSUE THREAD

**Issue by stefan1983** [kodi-pvr/pvr.vuplus#269]
I recently switched all my local network products to be accessed via HTTPS (own certificates). My problem is that I can't access my vu+ via the Kodi plugin via https (http works fine). Is there any way to debug what's happening? Did anyone test HTTPS successfully yet?

Thanks

**Comment by phunkyfish** [comment]
By own certificates do you mean self generated?

**Comment by stefan1983** [comment]
Yes, based on own CA created with openssl. Is there any way to install the CA cert into the trusted store on Apple TV?

**Comment by stefan1983** [comment]
So, after I figured out how to install the CA cert it is working now. I had to install the ca cert to be trusted (via Apple Configurator - wirelessly). But streaming via HTTPS is not working when selection the option. Is there anything else needed to allow that?

**Comment by phunkyfish** [comment]
These days you might be better creating a real cert with LetsEncrypt etc just saves hassle.

Anyway, I think you need to tell kodi that it's ok to use self singed certs. In Leia, there were changes made to only allow CA certified certs I think.

**Comment by phunkyfish** [comment]
Try this for adding to kodi's own cert store: https://forum.kodi.tv/showthread.php?tid=331918&pid=2735088#pid2735088

Or switch to using a VPN ;)

**Comment by stefan1983** [comment]
Any idea how to achieve that on an Apple TV (MrMC)? It seems I can not access the install path within MrMC file manager (only profile path).

**Comment by phunkyfish** [comment]
MrMc is based on a much older version of kodi so I really don’t know. Might be better asking on their forum.

Maybe test this on a version that is not tvOS first to make sure it’s the right answer.
