### ISSUE TITLE
Server is unreachable (Odroid N2 with current CoreElec) 

### ISSUE THREAD

**Issue by Cosmicbase** [kodi-pvr/pvr.vuplus#270]
I never had trouble watching TV with Libreelec via a Linux receiver and PVR Enigma2 client.
I am currently using an Odroid N2 with current CoreElec. 
The connection to the Enigma2 server breaks at regular intervals. 
I have tried several receivers with different firmware. (OpenATV, Opendroid, OpenHDF).

 Error: "Enigma2 Client - Server is unreachable" and the image hangs 

and is then automatically repeated with the following

Enigma2 Client - Established A Connection

Why do I get this error?
Under Libreelec with RPi3 B I could watch TV for hours without disconnections.

**Comment by phunkyfish** [comment]
Is the the Odroid N2 less powerful than the RPi3? Just curious.

You can play with settings regarding connection checks. On the connection tab addon settings at the bottom you will see connection check timeout and interval.

**Comment by Cosmicbase** [comment]
The N2 is 50% faster than an RPi4.

**Comment by Cosmicbase** [comment]
Timeout and the interval for connection checking.

What values should I write in?

**Comment by phunkyfish** [comment]
Try increasing the interval first bit by bit to see does it help. Then the timeout bit by bit.

Usually you only need to increase these values if:

- your STB is very old and can’t respond fast enough
- your network bandwidth is limited so responses take to long to arrive

**Comment by Cosmicbase** [comment]
OK I tried your instructions. It is still the same problem.
My Dinabot 4K Plus supports 4k and H265. 
I almost think it's an amlogic problem. 
I never had any problems with RPi3 B. 
I watch TV and after a few minutes the picture gets stuck and the connection to the Enigma2 server is lost. 
It sometimes takes up to 1 minute for message to return "connected"

**Comment by phunkyfish** [comment]
Yes, it may just be that CoreElec needs to fix some issues.

The RPi3 B+ is my baseline for changes so I don’t believe this is an addon issue.

**Comment by Cosmicbase** [comment]
Can you pass the problem on to CoreELEC. Would be really great if this is solved quickly. I've always used the AddOn and I really appreciate it.

**Comment by Cosmicbase** [comment]
I always have a fixed ethernet connection (1000mbit) and fast hardware.
Dinabot 4K + (OpenATV 6.4) and Odroid N2 (Last Nightly CoreELEC).
I've tried other distributions on Dinobot and LibreELEC on Odroid N2.
Unfortunately always the same problem. So I think it's a problem with CoreELEC using AmLogic hardware.

**Comment by phunkyfish** [comment]
You will need to contact CoreElec support/forum yourself I’m afraid. I try to support users on all platforms for the addon but for kodi core we only support the team kodi releases and amlogic is not a supported platform.

**Comment by phunkyfish** [comment]
Do bear in mind that like the RPi4 the Odroid N2 is a relatively new platform. Full support will take time.

It would be a good idea to do a bandwidth test (RPi3 vs Odroid N2) from STB to the device to see if you can track down where the bottleneck might be.

**Comment by Cosmicbase** [comment]
Is there any tool for kodi to test the bandwidth?
Maybe I will try a test and change the Lan connection to 5Ghz wifi and will see the bandwidth results.

**Comment by phunkyfish** [comment]
I simply scp a large file to/from the devices and compare the transfer times if I suspect a device has network issues.

**Comment by Cosmicbase** [comment]
OK I'll test it.

**Comment by Cosmicbase** [comment]
So I looked in the basement into my network cabinet and found that the network activity of the Dinabot 4k + only 100MBit (Yellow LED) shows.
The background is probably that the receiver is sold at 100Mbit instead of 1000Mbit. 
With the built-in Wi-Fi, I no longer have any connection cancellations. 
However, I still ordered a USB 3.0 Gigabit LAN Adabter with AX88179 chip. He should definitely get even more speed out. But one thing is definitive. At 100Mbit, proper streaming over the home network is very difficult. 

Thank you for your help and tips.

**Comment by phunkyfish** [comment]
No problem. You’re very welcome
