### ISSUE TITLE
Wrong channel order if channel is repeated at multiple bouquets

### ISSUE THREAD

**Issue by Azureit** [kodi-pvr/pvr.vuplus#271]
If a channel is repeated at multiple bouquets, only the first processed bouquet will have the right order, all the other will have this repeated channels at the beginning.

**Comment by phunkyfish** [comment]
That’s correct and expected behaviour. A channel gets assigned the number from the first time it’s loaded and the order is via Channel number.

In kodi Matrix you have the option of preserving the order in each group.

**Comment by Azureit** [comment]
Thanks mate.
It would make sense that option be on by default.

**Comment by phunkyfish** [comment]
Can’t really be the default as it’s a new feature and works across all PVR addons.

That would mean a behaviour change for every user which wouldn’t be good.
