### ISSUE TITLE
[RFC] Rename "VuPlus" PVR client addon to Enigma2 or something else for Kodi?

### ISSUE THREAD

**Issue by Hedda** [kodi-pvr/pvr.vuplus#28]
Please, would you consider renaming the "VuPlus" PVR client addon to Enigma or something else?

Arguments for this is that it is is not a specific Vu+ PVR client addon but actually an "Enigma2" PVR client addon. As Vu+ (written as VuPlus) is a specific company that makes set-top boxes based on the Enigma2 open source platform, and the  "VuPlus" PVR client addon does not only work with  Vu+ set-top boxes but actually works with any Enigma2 based set-top boxes, including the popular Dreambox, DBox2, SAB, and Amiko boxes from different competing companies, as well as many more Enigma2 based set-top boxes from other manufacturers. Even one of Kodi's official sponsors, WeTek, have Enigma2 based images available or their WeTek Play set-top box, so they too can use this addon which is still named the "VuPlus" PVR client addon.

To add to that argument is that Vu+ is not even the original developer of the Enigma2 open source platform, as that is DreamMedia who makes the Dreambox series. So originally it would even have made more sense to name the PVR client addon "Dreambox" than "VuPlus", but now that is not either true as DreamMedia have very recently abandoned the Enigma2 open source platform for all their new set-top box as they have switched so use a propriatary OS which they call "Dreambox OS".

Call it bikeshedding or OCD is you will, but having this addon keeping the name "VuPlus" is very bad form, and I think that it could make it look like the Kodi team is only supporting set-top boxes from Vu+ as a company for whichever reason, and not all Enigma2 based set-top boxes which is more in the spirits of open source philosofy, and even more so now that WeTek too is offering several Enigma2 based images for their WeTek Play device which just so happen is known to be in the possession of many Kodi developers because them being a sponsor of the project.

Regardless it would really make a lot of sense to rename this addon for Kodi to "Enigma2" or just "Enigma", or whatever. Only thing that does does not make sense is the addon being named "VuPlus" as it is today.

Also note subforum in Kodi community is called "Enigma" http://forum.kodi.tv/forumdisplay.php?fid=167

EDIT: For reference read this Kodi forum thread http://forum.kodi.tv/showthread.php?tid=214947

**Comment by Hedda** [comment]
@jdembski, what are your options today on such a name change?

**Comment by Jalle19** [comment]
If this goes through, please make sure you don't end up with the same Ubuntu package naming snafu like we did with pvr.hts. @wsnipex pinging you just in case.

**Comment by jdembski** [comment]
I don't have a problem with changing its name - the reason why I named it "vuplus" in the first place was because I 
a) just own a VU+ device
b) back then I heard stories about DreamMedia suing people who were using the term "enigma2". As I didn't want any trouble I picked "vuplus" instead. 

The KODI sub-forum should be named "enigma2" and not just enigma, as the addon does not support enigma1 boxes. 

In general it may seem that the development stopped on this addon - which is kind of true as I'm just using it to see sports broadcasts in my home cinema, so I do not really care about features like timeshift, advanced timer handling or zapping times. So if anyone wants to step up and pick up the further development for this addon - please go ahead.

**Comment by hudokkow** [comment]
-1
I already wrote a new enigma2 pvr addon with added functionalities.
I still have to clean the code, refactor some stuff, etc. and then I'll push it to official addons before Isengard final is out.
Coincidentally, it's named pvr.enigma2.stb. Maybe I can shorten the name to pvr.enigma2... :wink:

btw, thanks @jdembski for the excellent code base.

**Comment by Hedda** [comment]
@hudokkow @jdembski Will the new mentioned addon for Enigma2 make the old VuPlus addon obsolete?

That is, does the new addon replace all functions and features of the old one so that it can be removed?

**Comment by hudokkow** [comment]
@Hedda, yes and a few more.

Timeshifting is working.
EPG guide coloured by genre is working but needs a small change to openWebif (PR coming)
Up to 5 TV channel groups. I use 3. Can up the limit but I don't see the point.
Jarvis style timers, still a work in progress.
Much faster EPG loading
Backend info (signal, quality)

BTW, I need your help.
Please read http://forum.kodi.tv/showthread.php?tid=247476 and https://github.com/kodi-pvr/pvr.vuplus/issues/25

**Comment by Hedda** [comment]
@hudokkow @jdembski Thanks for the update! I have got an follow-up question but it might be a little too much off-topic so you don't have to answer it but I will at it anyway, and that follow-up question this:

Have you or anyone tested to compile and run your Enigma2 PVR client addon for Kodi running nativly on a hardware set-top box that runs the Enigma2 OS image? That is, wil you be able to run both the Kodi (GUI) application AND your Enigma2 Enigma2 PVR client addon locally on a hardware box that is runing an Enigma2 based image for a all-in-one DVR device solution without streaming video over the network from an Enigma2 box o Kodi running on a a other non-Enigma2 based computer?

As you probably know by now, WeTek now have Enigma2 based images/ditros available from the OE-Alliance for the WeTek Play (see https://github.com/wetek-enigma/ and http://wetekforums.com/vb5/forum/wetek-play/enigma-2 ), and they even got Kodi running on nativly on some of those Enigma2 based images. And also Vu+ have ported Kodi so that it runs nativly on their newer Enigma2 based set-top boxes, though they do not yet hardware accelerated video decoding working yet in Kodi's internal video player, (see for example http://www.vuplus-community.net/board/forums/xbmc-black-hole.115/ ).

**Comment by Hedda** [comment]
@hudokkow do you have news on your new/replacement PVR client addon for Enigma2 backends?

Maybe you could even hint of an ETA for pushing and publish it to a public repo here on GitHub?

**Comment by hudokkow** [comment]
Will be available for Krypton alphas and *maybe* for Jarvis when it hits final. Haven't decided yet.

**Comment by Adricool** [comment]
@hudokkow, great news, we hispasat users have a common problem we cannot stream most of the channels on kodi with vuplus add-on, can you have a look and maybe fix this problem in your add-on? Many thanks

**Comment by freddysmith1** [comment]
@hudokkow  did your version ever get released or has it just replaced the old one ?

**Comment by phunkyfish** [comment]
@hudokkow did you ever release the new plugin?

**Comment by Hedda** [comment]
@hudokkow any news or this or your new PVR client addon for Enigma2 / Vu Plus and its name?

**Comment by phunkyfish** [comment]
He made a lot of changes to the existing plugin. I’m maintaining it now.

**Comment by phunkyfish** [comment]
I havn’t looked at what is involved in changing the name. If it means breaking the addon for a lot of users I’m not sure I’d be keen on it. Or is it just the displayed name you are looking to change?

I maintain this in my spare time so would rather not spend cycles on something if it doesn’t have to happen or if there is a simpler solution.

**Comment by Hedda** [comment]
@phunkyfish Changing only the display name cosmetically should be more than enough I think. 

That is, the name change would really be made to make it more clear to the end-users (not to make it clear for developers). 

The idea was to make people know that this addon is not dedicated only for PVR-boxes manufactured by VuPlus but instead for all PVR-boxes that are based on the Enigma2 software platform (which is used by many other manufacturers too, and in fact, VuPlus was not even the first to use Enigma2 software platform, the first was  Dreambox as developed by Dream Multimedia).

**Comment by phunkyfish** [comment]
Makes perfect sense, same reasoning as XBMC->Kodi

Name will be Enigma2

**Comment by Hedda** [comment]
Good decision! Maybe it would be different if XBMC Foundation was sponsored by Vu+ but since it is not ;)

**Comment by Hedda** [comment]
@phunkyfish Submitted pull request #105 and pull request #106 to reflect this name change.
