### ISSUE TITLE
Timeshift trashes FireTV Cube (No Factory Reset possible)

### ISSUE THREAD

**Issue by Troox73** [kodi-pvr/pvr.vuplus#286]
First i dont blame you oder your beautiful piece of Software, only to let you know ;-)

Today at 2am i tell Alexa "Turn off TV in 45min" - she did, pvr.vuplus was set to Timeshift on Pause.
But Timeshift runs and runs and wrote the HDD down to 17kb free. FireOS cant even load its Icons on the Startscreen and on the Next reboot it has a "Bootloop" at the FireTV sign with the three dots on the right bottom. No Factory Reset possible, not with Remote, USB Keyboard, adb... Return to sender ^^

Solution, please build in a function "min. HDD space left" - at this point, cancle Timeshift or throw a Error"

Thanks!

**Comment by Troox73** [comment]
Leia 18.6 with latest GitHub version used.

**Comment by phunkyfish** [comment]
Bummer, sorry about that. You can try adding a usb thumb drive to the fire tv and set the timeshift buffer to that location. Then it can’t use all the space.

It is strange that the FireTv allows all space to be eaten up in the first place.

I have many devices that can run out of space but they always contribute to boot after all the space is gone.

Does kodi automatically pause when the TV is switched off? Why not have the FireTV go into power save mode when the TV goes off.

Just trying to give you options.

**Comment by Troox73** [comment]
It's the Headunit in my Home with watchdog installed to scan directorys on my Server. I'm to lazy and dont know much about Linux/Docker for a headless installation. Maybe i got somehow time for that :-)
Anyway, the Cube is on the Way to Amazon. Tomorrow comes the new one ^^

**Comment by Troox73** [comment]
New Cube arrived :D Do you plan to add something like a Space Check? For now, timeshift set to off ;-)

**Comment by phunkyfish** [comment]
What I would prefer to do is build something where the timeshift buffer is limited to a size. So a circular buffer. But that’s quite a lot of work.

Even doing what you suggest is quite problematic as the addon has no notion of not being able to timeshift and depending on what channel is being viewed the amount of free space required can vary largely (even by device).

In the meantime I would just purchase a cheap usb mini thumb drive and put the buffer on that. I will come up with a good solution eventually 😉

**Comment by Troox73** [comment]
Nice Idea, BUT afaik the Cube USB can only be use with the LAN Adapter OR a USB Drive. I need LAN :D A circular buffer? Perfect, but lot of work - hehe. A "kill-switch" for Timeshift at a User Adjustable min. Device Space Size should do the Trick i think :)

**Comment by phunkyfish** [comment]
You just need a USB hub. Then you should be able to use both.

**Comment by phunkyfish** [comment]
Fixed by: https://github.com/kodi-pvr/pvr.vuplus/pull/313
