### ISSUE TITLE
Fix spelling errors reported by Lintian

### ISSUE THREAD

**Issue by basilgello** [kodi-pvr/pvr.vuplus#291]
`configuraton`:
https://github.com/kodi-pvr/pvr.vuplus/blob/9f71c7297d947833c69a5470a9b841c1b31bc2d9/src/Enigma2.cpp#L151
`Transfered`:
https://github.com/kodi-pvr/pvr.vuplus/blob/9f71c7297d947833c69a5470a9b841c1b31bc2d9/src/Enigma2.cpp#L844

@phunkyfish

**Comment by phunkyfish** [comment]
Feel free to submit the PR if you like 😉

**Comment by basilgello** [comment]
> Feel free to submit the PR if you like wink

OK! I will collect more lintian warnings from different packages and batch-fix them as series of PRs :)
