### ISSUE TITLE
pvr.vuplus crash at 75% on Kodi Matrix

### ISSUE THREAD

**Issue by AnTri** [kodi-pvr/pvr.vuplus#294]
Hey, I tried to test kodi matrix with the actual pvr.vuplus add-on. After config and restart, kodi crashes (close) during pvr manager is starting up at 75%.

I've a VU+ Ultimo 4K with latest VTI Image.

**Comment by phunkyfish** [comment]
Please provide a full debug log.

**Comment by AnTri** [comment]
https://paste.kodi.tv/evaxigociz.kodi

Thank you!

**Comment by phunkyfish** [comment]
The version of OpenWebIf on your device is quite old. It’s version 1.2.8. The latest version is 1.3.X and it had been for several years. Upgrading to an image with a later version would be a good idea. Most of the new features in the addon won’t work with a version that old. I have never been able to test that version.

Can you try disabling initial EPG load in the addon settings under EPG? Not sure if that will help.

Your log just stops. It has not started loading the EPG yet. When the crash happen does kodi exit? Anyway you can get a crash log on windows or does it just freeze?

**Comment by AnTri** [comment]
Thanx for helping me!!!

I've no problem using the add-on (v 3.x) with version Kodi Leia. When the crash happens, Kodi close immediatly. I've no change to edit the configuration via GUI.

OpenWebIf 1.2.8  is the actual supported version on VTI 14.x. 

I will check if the current version runs with the VTI image.

**Comment by phunkyfish** [comment]
Ok, you can modify that setting by hand before starting kodi to try. Just find your userdata folder on windows and it should be in `userdata/addon_data/pvr.vuplus/settings.xml`.

The setting will be called `skipinitialepg` and you should set it to true.

**Comment by AnTri** [comment]
changing skipinitialepg  to true makes no difference. 

I try to update OpenWebIf

**Comment by AnTri** [comment]
Kodi/add-on crashes using OpenWebIf 1.3.x / 1.4  too. Do you have any further idea?

**Comment by phunkyfish** [comment]
Ok. What we need is a crashlog, and I don’t know how to get that on windows it if it’s is possible.

I don’t suppose you can run kodi from a Mac or Linux as a test to get one?

**Comment by AnTri** [comment]
From Windows Event Log:

Fehlerbucket , Typ 0
Ereignisname: BEX64
Antwort: Nicht verfügbar
CAB-Datei-ID: 0

Problemsignatur:
P1: kodi.exe
P2: 18.9.701.0
P3: 5f1d91c6
P4: ucrtbase.dll
P5: 10.0.19041.488
P6: 0d8057d8
P7: 0000000000071218
P8: c0000409
P9: 0000000000000005
P10:

**Comment by AnTri** [comment]
Name der fehlerhaften Anwendung: kodi.exe, Version: 18.9.701.0, Zeitstempel: 0x5f1d91c6
Name des fehlerhaften Moduls: ucrtbase.dll, Version: 10.0.19041.488, Zeitstempel: 0x0d8057d8
Ausnahmecode: 0xc0000409
Fehleroffset: 0x0000000000071218
ID des fehlerhaften Prozesses: 0x2604
Startzeit der fehlerhaften Anwendung: 0x01d688331070282a
Pfad der fehlerhaften Anwendung: C:\Program Files\Kodi\kodi.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\ucrtbase.dll
Berichtskennung: ca3a5952-8ccf-4ff2-aa5f-8fc5798e9c86
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by phunkyfish** [comment]
Unfortunately that doesn't tell me anything, what I need is the state of all threads in kodi when the crash happens. As previously stated I know no idea how to get that from windows.

All I can see from your log is that it starts to read the recordings but never finishes.

I don't suppose there is a way for me to connect to your device remotely and see if I can reproduce this?

**Comment by AnTri** [comment]
Today, I try to get a crashlog with Visual Studio Debugger. Maybe it can help. If this is no working, I try to install Ubuntu on a VM. Then I need your help how to get the log/information you need...

**Comment by phunkyfish** [comment]
Cool, thanks. What I'm looking for is a reference to the code line where the crash occurs. Do you require a PDB file for windows?

**Comment by AnTri** [comment]
![image](https://user-images.githubusercontent.com/6997604/93082270-ea9b6f00-f690-11ea-9de8-fcd0d5bd43d7.png)

**Comment by AnTri** [comment]
I used the kodi pdb from http://mirrors.kodi.tv/snapshots/windows/win64/

**Comment by AnTri** [comment]
I hope this helps

**Comment by phunkyfish** [comment]
Hmmm, the calls in the vuplus addon are hidden.

**Comment by phunkyfish** [comment]
I’m not sure how we can access those.

**Comment by AnTri** [comment]
Can you send me the pdb? I try to debug the add-on

**Comment by phunkyfish** [comment]
I don’t know how to generate a PDB file for an addon 😔

**Comment by phunkyfish** [comment]
@emveepee do you knew how to do this or could you provide the addon with a Pdb file?

**Comment by emveepee** [comment]
> 
> 
> @emveepee do you knew how to do this or could you provide the addon with a Pdb file?

Here is a debug build package (untested) with the current Matrix https://1drv.ms/u/s!Ar-w3NVk_f-MlhA56CJFV1PchXE9?e=WKyCuS It includes the matching dll and pdb

It is trivial to build for Windows just following the linux instructions if you the base tools installed.

**Comment by phunkyfish** [comment]
Thanks. I'm not sure @AnTri has a configured build environment.

**Comment by emveepee** [comment]
> 
> 
> Thanks. I'm not sure @AnTri has a configured build environment.

NP.  If you need to send me a diff with extra logging I can build that too.

**Comment by AnTri** [comment]
I have tried to build the add-on, but have failed for the moment.

**Comment by phunkyfish** [comment]
@AnTri the link provided above contains the addon and debug file for the vuplus addon so you don’t need to build it yourself.

**Comment by AnTri** [comment]
I have tried. But the debugger does not use/call the add-on.

**Comment by phunkyfish** [comment]
@emveepee any hints on how to set this up so the debugger uses the add-on you supplied in addition to kodi?

**Comment by emveepee** [comment]
> 
> 
> @emveepee any hints on how to set this up so the debugger uses the add-on you supplied in addition to kodi?

@AnTri did you replace the dll and put the pdb with it in C:\Users\AndreasTrinkle\AppData\Roaming\Kodi\addons\pvr.vuplus\ with Kodi stopped and give the debugger the location of the pdb too?

**Comment by AnTri** [comment]
I forgot to replace the dll

**Comment by AnTri** [comment]
![image](https://user-images.githubusercontent.com/6997604/93220791-41767680-f76d-11ea-9245-642f599f4350.png)

**Comment by AnTri** [comment]
When I try to debug (Press "Wiederholen") I get the following code:

![image](https://user-images.githubusercontent.com/6997604/93220930-6f5bbb00-f76d-11ea-928c-2d8b9c2dd92c.png)

**Comment by AnTri** [comment]
Content of the variable m_channelName

![image](https://user-images.githubusercontent.com/6997604/93221150-b184fc80-f76d-11ea-83b8-2c9ba858476b.png)

**Comment by emveepee** [comment]
@phunkyfish would you like me to try a build with this

```
inline int unch(unsigned char const c) { return(isspace(std::char_traits<char>::to_int_type(c))); };
...
  m_fuzzyChannelName.erase(std::remove_if(m_fuzzyChannelName.begin(), m_fuzzyChannelName.end(), unch), m_fuzzyChannelName.end());
```

**Comment by AnTri** [comment]
i still can't compile. can you send me a debug dll with pdb?

**Comment by phunkyfish** [comment]
Yes @emveepee please do.

**Comment by emveepee** [comment]
@AnTri  unzip these over the others.  https://1drv.ms/u/s!Ar-w3NVk_f-MlhFMfeVR3aa2tOqC?e=cT2xwD

**Comment by AnTri** [comment]
![image](https://user-images.githubusercontent.com/6997604/93251318-4f8bbd80-f794-11ea-9b82-6850e645b897.png)

**Comment by AnTri** [comment]
I think it has something to do with the "german" umlauts.

**Comment by AnTri** [comment]
![image](https://user-images.githubusercontent.com/6997604/93251554-a2657500-f794-11ea-9823-142a3478d670.png)

**Comment by AnTri** [comment]
In german "WDR HD Köln"

**Comment by emveepee** [comment]
Yes it likely the negative char.  That doesn't look like what I compiled.  Are your sure you updated the dll and pdb from vuplus.zip?  Kodi would need to be stopped to do the update.

**Comment by AnTri** [comment]
I have double-checked it. It's the dll / pdb from your zip. Probably the sourcecode "recordingentry.cpp" is not the one you use. I got it from the github...

**Comment by AnTri** [comment]
Please find attached the output from the debugger:

https://paste.kodi.tv/utejevejir.kodi

**Comment by phunkyfish** [comment]
That output looks to me like recordings were successfully loaded. I wonder is there another place where there can a negative int character. Or else I'm just reading the log wrong.

**Comment by emveepee** [comment]
@AnTri  sorry I didn't look at the screen shot carefully it is from another location try this  https://1drv.ms/u/s!Ar-w3NVk_f-MlhFMfeVR3aa2tOqC?e=9J5cft

@phunkyfish assuming this works the better solution would likely be to expose StringUtils::isspace_c or wrap it in another call

**Comment by phunkyfish** [comment]
`StringUtils::isspace_c` should be available in the addon so I guess that's the best call.

**Comment by phunkyfish** [comment]
I wonder if `std::isspace` would solve this issue instead.

**Comment by emveepee** [comment]
> 
> 
> I wonder if `std::isspace` would solve this issue instead.

By this documentation it was pretty clear that it wouldn't https://en.cppreference.com/w/cpp/string/byte/isspace

```
"Like all other functions from <cctype>, the behavior of std::isspace is undefined if the argument's value is neither representable as unsigned char nor equal to EOF. To use these functions safely with plain chars (or signed chars), the argument should first be converted to unsigned char: "
```

**Comment by phunkyfish** [comment]
Ya, just read that myself.

**Comment by AnTri** [comment]
> @AnTri sorry I didn't look at the screen shot carefully it is from another location try this https://1drv.ms/u/s!Ar-w3NVk_f-MlhFMfeVR3aa2tOqC?e=9J5cft
> 
> @phunkyfish assuming this works the better solution would likely be to expose StringUtils::isspace_c or wrap it in another call

I tried the last version you provided on OneDrive. It looks like there is another error:

https://paste.kodi.tv/upevatowaf.kodi

**Comment by emveepee** [comment]
@Antri That is going to be something different.  Do you have the line number from the debugger or could you turn on debug logging and also PVR and EPG component logging so I an narrow that down?

Also this might need to be looked at but if it is from line 187 of Channels.cpp it could be ok.

```
2020-09-16 22:09:12.563 T:13512   ERROR <general>: AddOnLog: pvr.vuplus: pvr.vuplus - LoadChannels Could not find <e2service> element
```

**Comment by AnTri** [comment]
Here is the advanced log:

https://paste.kodi.tv/ehibidosug.kodi

and the "new" errror:

![image](https://user-images.githubusercontent.com/6997604/93431352-56195280-f8c4-11ea-800a-ceffb0a496a5.png)

**Comment by phunkyfish** [comment]
Do you have the code line from the debugger UI?

**Comment by AnTri** [comment]
![image](https://user-images.githubusercontent.com/6997604/93434080-f58c1480-f8c7-11ea-8996-9fe89d58cdb8.png)

**Comment by phunkyfish** [comment]
Ok there are two different places in the code where this is used in a similar way:

```cpp
std::string ParseAsW3CDateString(time_t time)
{
  std::tm* tm = std::localtime(&time);
  char buffer[16];
  std::strftime(buffer, 16, "%Y-%m-%d", tm);

  return buffer;
}
```

I'm not sure how this behaves differently on windows. @emveepee any ideas?

```
Der Thread 0x329c hat mit Code 0 (0x0) geendet.
Debug Assertion Failed!

Program: C:\Program Files\Kodi\kodi.exe
File: minkernel\crts\ucrt\src\appcrt\time\strftime.cpp
Line: 135

Expression: timeptr != nullptr

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.
```

**Comment by emveepee** [comment]
>
> ![image](https://user-images.githubusercontent.com/6997604/93434080-f58c1480-f8c7-11ea-8996-9fe89d58cdb8.png)

Too bad we don't have the line number on the row under the cursor but I suspect 63.  @AnTri  could you try this one https://1drv.ms/u/s!Ar-w3NVk_f-MjwL8CLkDT-v1JTKb?e=QqNyO9I just need to see the log.   

Perhaps the xml this generates http://192.168.50.111:80/web/movielist?dirname=/media/hdd/movie/ would be useful too

**Comment by phunkyfish** [comment]
It says line 31 in the top left I think. I'm assuming Zeile means line. But the code is the exact same in two different places.

**Comment by emveepee** [comment]
> 
> 
> It says line 31 in the top left I think. I'm assuming Zeile means line. But the code is the exact same in two different places.

@phunkyfish  I found those yesterday, but the row under that is the call.   I am assuming it is a time pre 19070

**Comment by phunkyfish** [comment]
So negative time_t?

**Comment by emveepee** [comment]
> 
> 
> So negative time_t?

Yes easy for movies and reruns.   Checking std::localtime https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/localtime-localtime32-localtime64?view=vs-2019 it return NULL for those times.

**Comment by phunkyfish** [comment]
But whether this is a movie or a re-run a negative value should be impossible.

It's a recording start time, which makes it's impossible to be before 1970. Really not sure how this data is bad to begin with.

But no harm in testing for a NULL return anyway I guess.

**Comment by phunkyfish** [comment]
This should work for any invalid cases (which should be impossible anyway!).

```cpp
std::string ParseAsW3CDateString(time_t time)
{
  std::tm* tm = std::localtime(&time);
  char buffer[16];
  if (tm)
    std::strftime(buffer, 16, "%Y-%m-%d", tm);
  else // negative time or other invalid time_t value
     std::strcpy(buffer, "1970-01-01");

  return buffer;
}
```

@AnTri you seem to be finding all the crazy issues!

**Comment by emveepee** [comment]
> 
> But no harm in testing for a NULL return anyway I guess.

I did a test and std::locale() will return nullptr before 1970.  I was hoping that the movielist API call would show what is in the database since the first aired date is supposed to show older dates https://github.com/xbmc/xbmc/pull/17192 and you might have another future feature.

I made your change and here it is https://1drv.ms/u/s!Ar-w3NVk_f-MlhFMfeVR3aa2tOqC?e=H4hjOs

**Comment by phunkyfish** [comment]
I don’t think that would ever be a future feature as the notion of a recording or epg entry on Enigma2 is defined as something that occurred when the device was running. This cannot be the case here unfortunately.

Thanks for implementing 😉

**Comment by AnTri** [comment]
> > But no harm in testing for a NULL return anyway I guess.
> 
> I did a test and std::locale() will return nullptr before 1970. I was hoping that the movielist API call would show what is in the database since the first aired date is supposed to show older dates [xbmc/xbmc#17192](https://github.com/xbmc/xbmc/pull/17192) and you might have another future feature.
> 
> I made your change and here it is https://1drv.ms/u/s!Ar-w3NVk_f-MlhFMfeVR3aa2tOqC?e=H4hjOs

@emveepee 👍  Your version works like a charm !!!

Many thanks to all of you

**Comment by emveepee** [comment]
Thanks @AnTri  did you have a chance to look at the xml file to see what the negative numbers in e2time are showing?

**Comment by AnTri** [comment]
There are many entries with -1 for e2time

`<e2movie>
<e2servicereference>1:0:0:0:0:0:0:0:0:0:/media/hdd/movie/20190922 1128 - KiKA HD - Die Sendung mit der Maus.ts</e2servicereference>
<e2title>Die Sendung mit der Maus</e2title>
<e2description>Welt-Schul-Maus Lach- und Sachgeschichten, mit einem ungewöhnlichen Schulbus, einer tanzenden Schule, mit Essen im Klassenzimmer, Hosenbodenrodeln in der Schulpause, mit fleißig putzenden Schulkindern und natürlich mit der Maus, dem Elefanten und der Ente. Die Maus drückt weltweit die Schulbank - Ein besonderer Schultag mit der Maus! In zehn Ländern begleitet Ralph Caspers Kinder in Schulen. Sie alle lernen Mathe, Geschichte, Sprachen, aber die Unterschiede fallen Ralph auch gleich auf: In London tragen sie Uniformen, sogar eine eigene für den Sport gibt es. In der südafrikanischen Hauptstadt Tshwane versucht Ralph, die Klicklaute zu lernen, die in zwei der elf offiziellen Landessprachen zum Einsatz kommen. Viel einfacher müsste es im Norden sein, aber in Reykjavik spricht man fast noch die Sprache der alten Wikinger. Unter anderem in Ankara stellen sich Kinder vor Unterrichtsbeginn zur Begrüßung auf dem Schulhof auf. In Indien werden die Kinder beim Schulhof-Frühsport richtig wach. In NeuDelhi en</e2description>
<e2descriptionextended>Welt-Schul-MausLach- und Sachgeschichten, mit einem ungewöhnlichen Schulbus, einer tanzenden Schule, mit Essen im Klassenzimmer, Hosenbodenrodeln in der Schulpause, mit fleißig putzenden Schulkindern und natürlich mit der Maus, dem Elefanten und der Ente.Die Maus drückt weltweit die Schulbank - Ein besonderer Schultag mit der Maus! In zehn Ländern begleitet Ralph Caspers Kinder in Schulen. Sie alle lernen Mathe, Geschichte, Sprachen, aber die Unterschiede fallen Ralph auch gleich auf: In London tragen sie Uniformen, sogar eine eigene für den Sport gibt es. In der südafrikanischen Hauptstadt Tshwane versucht Ralph, die Klicklaute zu lernen, die in zwei der elf offiziellen Landessprachen zum Einsatz kommen. Viel einfacher müsste es im Norden sein, aber in Reykjavik spricht man fast noch die Sprache der alten Wikinger. Unter anderem in Ankara stellen sich Kinder vor Unterrichtsbeginn zur Begrüßung auf dem Schulhof auf. In Indien werden die Kinder beim Schulhof-Frühsport richtig wach. In NeuDelhi entdeckt Ralph, wo unser Zahlensystem herkommt. Und die Ursprünge des lateinischen Schriftsystems lernt er in der griechischen Hauptstadt Athen kennen. Ralph wundert sich: In Tokio müssen sich die Kinder manchmal unter dem Tisch verstecken, denn zum Unterricht in Japan gehört auch der Erdbebenschutz. Und in Brasilia kann man vormittags noch in aller Ruhe Videospielen. Hier gibt es Schicht-Unterricht, die Schule beginnt für manche Kinder erst am Nachmittag. In Warschau freuen sich die Kinder besonders, wenn sie eine Sechs bekommen. Die schlechteste Schulnote ist hier eine Eins.Die Maus im Internet www.wdrmaus.deE-Mail-Adresse maus@wdr.deHD-Produktion</e2descriptionextended>
<e2servicename>KiKA HD</e2servicename>
<e2time>-1</e2time>
<e2length>38:58</e2length>
<e2tags>0</e2tags>
<e2filename>/media/hdd/movie/20190922 1128 - KiKA HD - Die Sendung mit der Maus.ts</e2filename>
<e2filesize>4518256828</e2filesize>
</e2movie>`

**Comment by phunkyfish** [comment]
That makes sense. Thanks for checking it.

Could you also try the tesbuild here: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.vuplus/detail/PR-295/5/artifacts

This is what will be released. You may require the latest kodi nightly build from here to be able to test it: https://mirrors.kodi.tv/nightlies/windows/win64/master/

If it doesn't work with the current alpha the nightly build from the 16th may be too old. Maybe wait for the one from the 18th to appear and try it then.

**Comment by emveepee** [comment]
Thanks for replying and glad it worked out.  It seems a regex on the filename would be better than 1970 (at the bottom of the list by date)

**Comment by phunkyfish** [comment]
Good idea. The filename format is not guaranteed but I guess it would be better to at least try that first before the default.

**Comment by AnTri** [comment]
@phunkyfish 
I tried your testbuild (pvr.vuplus-6.1.2) with the latest nightly (KodiSetup-20200918-a4936523-master-x64). IT WORKS!!!

Thank you all for the great support.

**Comment by phunkyfish** [comment]
Great. Thanks for testing 😉

**Comment by AnTri** [comment]
hey, i'm back again. I tried the latest matrix and the dll from onedrive --> Addon could not load

The link for the add-on from 

> That makes sense. Thanks for checking it.
> 
> Could you also try the tesbuild here: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.vuplus/detail/PR-295/5/artifacts
> 
> This is what will be released. You may require the latest kodi nightly build from here to be able to test it: https://mirrors.kodi.tv/nightlies/windows/win64/master/
> 
> If it doesn't work with the current alpha the nightly build from the 16th may be too old. Maybe wait for the one from the 18th to appear and try it then.

did not work anymore...

**Comment by phunkyfish** [comment]
There will be an update by the end of the week which will work.

**Comment by AnTri** [comment]
> There will be an update by the end of the week which will work.

Thanks for the Information and Quick reply.
I am looking forward to the new version/build.
