### ISSUE TITLE
Audio/Video not in sync when DD5.1

### ISSUE THREAD

**Issue by r2ixuz** [kodi-pvr/pvr.vuplus#296]
When watching a channel which streams 5.1 DD, audio must be delayed around 250ms to get synchronous. If the same channel is sending 2.0 DD source material A/V is in sync.

I think this has something todo with setting audio to passthrough. I am on Kodi 18.8 LibreELEC 9.2.5 with RPi 4B 4GB. Enigma box is VU+ with latest VTI image. Audio there is in sync no matter if 5.1 or 2.0.

Everything else is in sync.

**Comment by phunkyfish** [comment]
Sorry, you say it's not working with 5.1DD and then it's in sync in 51/2.0 the next paragraph. I don't follow.

**Comment by r2ixuz** [comment]
I meant if I watching directly via the VU+ receiver it is always in sync. Only Kodi has a problem with 5.1DD.

**Comment by phunkyfish** [comment]
Ah, ok. Let me see if I can find a channel with 5.1 to check this.

**Comment by r2ixuz** [comment]
Could you reproduce this issue?

**Comment by phunkyfish** [comment]
Not yet. Sorry, busy week. Will try to check this at the weekend.

**Comment by r2ixuz** [comment]
Yeah Ok absolutely no problem. 

Just fyi: I think it has something todo with encrpyted channels. Free channels seems to have no out of sync issue at 5.1. 

Another thing if I switch to an encrypted 5.1 channel the first couple of seconds a/v seems to be in sync but then it gets hardly out of sync. 250ms and more

**Comment by phunkyfish** [comment]
By encrypted do you mean channels that require a card to decrypt?

**Comment by r2ixuz** [comment]
Yes.

**Comment by phunkyfish** [comment]
So then there is no way I can test this.

**Comment by r2ixuz** [comment]
I think I found the problem. My Kodi Box (RPi4) is new and I did not properly adjust the a/v delay. I needed 100ms more delay, now it seems to be OK. Dunno why I couldn't see this with 2.0DD PVR VU+ streaming or 5.1 MKV files. Sorry for bothering you! :(

**Comment by phunkyfish** [comment]
No worries!
