### ISSUE TITLE
getservices?provider=1 is much slower than getservices?provider=0

### ISSUE THREAD

**Issue by phunkyfish** [kodi-pvr/pvr.vuplus#297]
PROVRS said:
Can you please give an option to set these 2 parameters somehow - getservices?provider=1&picon=1 (located in src/enigma2/Channels.cpp file)
If provider is set to 0, loading times are much faster from the WebIf. If I could compile this myself I would do it with provider=0.

**Comment by phunkyfish** [comment]
@PROVRS

Can you supply some timings for this and also supply a full debug log?

**Comment by PROVRS** [comment]
@phunkyfish, I'm sorry for not answering this sooner.
When I test in my browser IP_DM800se/api/getservices?provider=0&picon=1 vs IP_DM800se/api/getservices?provider=1&picon=1 the time difference is 1 seconds for provider=0 and 45 seconds for provider=1. I don't see need for me to extract provider name.
I'm sorry but I'll not publish my kodi log in public. It's just a suggestion for improvement of the plugin. Either way I got used to waiting 40-50 seconds until channels are listed :) By the way this is working just fine with immediate channels loading when using Kodi 17 and it's enigma2 plugin.

One more thing which I found and probably you will want to be logged under new issue. While initial ZAP is done fine, changing of channels is fine, the plugin never really sends stop descrambling for program when hitting stop button or exit KODI. This leaves the channel active forever and receiver cannot be used from another device to ZAP new channel. The only way is to wake up the receiver and send it to standby again.

Thank you for your support. Keep up the good work!

**Comment by phunkyfish** [comment]
The reason I asked for your debug log was to be able to tell what version of Enigma2/OpenWebif you are using etc so I can prepare a test and compare against my version. In addition I don't know how many bouquets or channels you have so I don't know if any test I would do would be comparable. It's likely this would need to be fixed upstream rather than removing the provider option.

There is no call to the STB to say you have finished watching a channel I'm afraid so there is no way to fix that issue of yours.

**Comment by PROVRS** [comment]
Here are the versions:

> Enigma2 Client: pvr.vuplus - enigma2::Admin::LoadDeviceInfo - E2EnigmaVersion: 2020-06-05-develop
> Enigma2 Client: pvr.vuplus - enigma2::Admin::LoadDeviceInfo - E2ImageVersion: 9.3
> Enigma2 Client: pvr.vuplus - enigma2::Admin::LoadDeviceInfo - E2DistroName: openpli
> Enigma2 Client: pvr.vuplus - enigma2::Admin::LoadDeviceInfo - E2WebIfVersion: OWIF 1.4.0
> Enigma2 Client: pvr.vuplus - enigma2::Admin::LoadDeviceInfo - E2DeviceName: DM800 HD se
> Enigma2 Client: pvr.vuplus - enigma2::Admin::LoadDeviceInfo - ServerVersion: OWIF 1.4.0 - openpli (9.3/2020-06-05-develop)
> Enigma2 Client: pvr.vuplus - enigma2::Admin::LoadDeviceInfo - AddonVersion: 3.28.9

Results are the same with OpenPli 7.2 and 10. Also tested with Odroid N2+, same time wait. Just my dreambox struggles with such request for providers and I'm not sure where this information will be used later? Probably there's a good reason to collect it. I'm just guessing here :)

Regarding the stop descambling, it is working with MPC HC player when you exit it, that's why I was wondering if it's possible to be done with Kodi also. But I guess it's not Addon related thing.

Thank you for your quick support on this. You can close the case if it's not relevant anymore.

**Comment by phunkyfish** [comment]
And roughly how many channels do you load from kodi?

**Comment by PROVRS** [comment]
While channels are not that much around 90, I just counted the providers from the query and they are around 30 :) So I guess that's why it takes so much time to output the result.
I can send you the bouquet if you want to test.

**Comment by phunkyfish** [comment]
Expert setting added here: https://github.com/kodi-pvr/pvr.vuplus/pull/303

FYI, this will only be available on Matrix version.

**Comment by phunkyfish** [comment]
Testbuilds are here: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.vuplus/detail/PR-303/1/artifacts

**Comment by PROVRS** [comment]
Thank you again for your quick response.
Can you please check my comment here https://github.com/kodi-pvr/pvr.vuplus/pull/303/files#r512733122

**Comment by phunkyfish** [comment]
Nice catch!

Testbuilds with fix here: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.vuplus/detail/PR-303/2/artifacts

**Comment by PROVRS** [comment]
12 seconds to load all channels in Kodi. Impressive 👍 
You can close this issue. When to expect it on CoreElec?

**Comment by phunkyfish** [comment]
I'm afraid I have no idea about CoreElec. It's a different team, I would ask in their forum.
