### ISSUE TITLE
Very long channel open times on Matrix Alpha1-3

### ISSUE THREAD

**Issue by phunkyfish** [kodi-pvr/pvr.vuplus#304]
I recently upgraded our living room setup with the latest Alpha builds. Prior to that the previous version was over a year old, and would have been quite close to a Leia build, I believe at that time the FFpmeg version would have been the same as Leia.

```
2020-11-12 19:54:33.138 T:3596879   DEBUG <general>: Open - av_probe_input_buffer start
2020-11-12 19:54:34.661 T:3596879   DEBUG <general>: Open - av_probe_input_buffer finished [mpegts]
2020-11-12 19:54:34.662 T:3596879   DEBUG <general>: Open - avformat_open_input start
2020-11-12 19:54:47.705 T:3596879   DEBUG <general>: Open - avformat_open_input finished
```

From the debug statements above you will see that the probing time is approximately 1.5 seconds and the time to open the stream is approximately 13 seconds.

Testing on Leia this time is consistently 2-3 seconds in total for both.

Here are the logs for opening a sample channel: https://gist.github.com/phunkyfish/ddf7bec4bd00423f45e7aee43cea9f71
And the same log with the pvr.vuplus specific logs stripped: https://gist.github.com/phunkyfish/d9e5ebbfc3347f9a73c79c63ec8a14e7

Another log when switching to sample channel while one is playing: https://gist.github.com/phunkyfish/f40065c8ed0e1c802360f8c38e6c5f45
And the same log with the pvr.vuplus specific logs stripped: https://gist.github.com/phunkyfish/16a068ffe5b0495d5c8b1c6d9567c522

`pvr.vuplus` uses a PVR inputstream. However if I play the same stream via iptvsimple the resulting timings are similar. Once all PVR add-ons move to have their own inputstreams in kodi 20 it's easy to completely remove the probing delay by supplying the mime type. However the time taken in `avformat_open_input` must have been introduced in the later version of FFmpeg or then a setup piece now required that is missing.

@FernetMenta / @a1rwulf any advice you have on how to track down the issue I'd be grateful. I will attach a sample of the stream shortly.

**Comment by phunkyfish** [comment]
Here is a sample of the video stream @FernetMenta / @a1rwulf. This is a raw capture of the live stream: https://drive.google.com/file/d/1LAPi8__b33kKVGfHaOx5azLQAVDM8nV1/view?usp=sharing

**Comment by a1rwulf** [comment]
@phunkyfish I tried to reproduce this issue with my setup and iptvsimple:
When I stream it with ffmpeg as udp multicast:
```
/opt/ffmpeg/bin/ffmpeg -re -i ~/Videos/samples/broken/slowopensample.ts -f mpegts "udp://224.0.0.2:5000?ttl=1&pkt_size=1316"
```
Opening time is normal, ~2s.

If I put it on my http-server, I can't open it at all for different reasons.
Can you try above ffmpeg command and see if it's slow for you?

**Comment by a1rwulf** [comment]
I probably found another issue with http streams that is unrelated.
It works 1 time and when it works it's also fast, so I really cannot reproduce it.

**Comment by phunkyfish** [comment]
Serving it via multicast it plays instantly as you have found, similar results if I place the file on a http server. But that's not surprising as recordings work perfectly.

It is something specific to live streams via http. Also tried in vlc which matches the 2-3 seconds in Kodi Leia. I could not easily find out what version of ffmpeg vlc uses but I would imagine it's the current stable version like kodi master.

Let me try the ffmpeg master and see if that makes a difference. Assuming it builds of course.

**Comment by phunkyfish** [comment]
No trouble building with ffmpeg master. Unfortunately the same delay is present there too so not fixed since.

I guess bisecting is the only course here. Only problem is I don't have a last known good build. I guess the commit used in Leia's FFmpeg.

**Comment by a1rwulf** [comment]
Mhm.
Yeah I'd probably try last few versions to get an idea when it started to get slow.

**Comment by phunkyfish** [comment]
Found the offending commit: https://github.com/FFmpeg/FFmpeg/commit/a221af1f5eea7313472b1cbeaa566b66d025fea6

`avformat/mpegts: add support for EPG extraction from mpegts`

The frustrating thing is there was a previous issue with this change whereby seeking was broken for streams with embedded EIT data which was fixed by this commit in Kodi: https://github.com/xbmc/xbmc/commit/ea1ef306c68ed204ffdff192c725c9cc6af49d0c

@FernetMenta I wonder if there was something else that would have needed to accompany this change. Any idea?

**Comment by phunkyfish** [comment]
Success! Fix proposed by FFmpeg team almost immediately!

http://ffmpeg.org/pipermail/ffmpeg-devel/2020-November/272422.html

PR to include the fix in kodi's ffmpeg: https://github.com/xbmc/FFmpeg/pull/17
