### ISSUE TITLE
After changing IP "Needs to restart"

### ISSUE THREAD

**Issue by AndKe** [kodi-pvr/pvr.vuplus#307]
I noticed that first time config trigger a strange message "needs to restart" when exiting configuration
- this is a bad message. 
What needs to restart ?
I cannot believe that the Linux or Libreelec needs to restart - can it be that Kodi needs to restart?  
- maybe just the plugin needs to restart, IF it is streaming in the background ?
Please make it clear if there is such a need

**Comment by phunkyfish** [comment]
All this means is that the addon needs to restart and it’s informing you that is what will happen. No action is required on your part. It is kodi showing this message. Not the addon.

**Comment by AndKe** [comment]
Thank you.
I'll report to Kodi, this can be improved.
