### ISSUE TITLE
en_gb Translations are empty

### ISSUE THREAD

**Issue by dklemm** [kodi-pvr/pvr.vuplus#31]

**Comment by hudokkow** [comment]
@alanwww1 ping

**Comment by alanwww1** [comment]
This is perfect this way. By definition of PO source language file, there should NOT  be any text as "translation" at the msgstr fields. Would nit make any sense at all. All kodi related english files are like this.

**Comment by dklemm** [comment]
Maybe I have another issue but the settings have no titles and my system is set to en_gb.  I have tried to fix this but updating my local files but still get no settings tiles.

<img width="961" alt="vuplus" src="https://cloud.githubusercontent.com/assets/2111972/12067702/53264b1c-aff6-11e5-9f1a-222c45828c0f.png">

**Comment by alanwww1** [comment]
@dklemm 
Sorry, but I cannot reproduce this problem. I tried to install this addon on my Linux system and all works fine both with en_gb and my native language.

Could you try to delete, than completely remove ALL files related to THIS addon and reinstall it clean ?
That could help.
