### ISSUE TITLE
EPG data not updating

### ISSUE THREAD

**Issue by r2ixuz** [kodi-pvr/pvr.vuplus#311]
I am using a VU+ UNO 4K SE with VTi 14.0.6 Image.

Kodi starts the vuplus addon normally and EPG data is fetched. But after around 3 days EPG is getting more and more empty. So the automatic recurring EPG data fetching does not work correctly. Tried several things but the only thing wich helps is to stop the vuplus Kodi addon and restart it again.

So I tried to workaround it with a nightly cronjob which triggers this python script:

```
import xbmc, time

#return to homescreen
xbmc.executebuiltin('ActivateWindow(home)')

#sleep long enough for the home screen to come up
time.sleep(30)

#stop PVR addon
xbmc.executeJSONRPC('{"jsonrpc":"2.0", "method":"Addons.SetAddonEnabled", "params":{ "addonid": "pvr.vuplus", "enabled": false }, "id":1}')
#sleep
time.sleep(30)
#start PVR addon
xbmc.executeJSONRPC('{"jsonrpc":"2.0", "method":"Addons.SetAddonEnabled", "params":{ "addonid": "pvr.vuplus", "enabled": true }, "id":1}')
```

Stopping works but when the plugin gets started again, the Kodi app crashes.

Is there a working solution for this EPG data not updating issue?

**Comment by phunkyfish** [comment]
What version of kodi and the addon are you running? Can you include a full debug log?

**Comment by r2ixuz** [comment]
I am using Libreelec 9.2.6 with Kodi 18.9 on a RPi 4B 4GB RAM.

How do I do a "full debug log" ? And when: When my script kicks in or after couple days of use to see missing EPG data?

**Comment by r2ixuz** [comment]
Addon version 3.28.9.1

**Comment by phunkyfish** [comment]
What are your settings for `Guide` in kodi pvr settings? It seems like to me kodi has been set to never update EPG.

Instructions for debug log are here: https://kodi.wiki/view/Log_file/Easy

**Comment by r2ixuz** [comment]
Sorry Kodi is set to German. Hope this is the correct settings page:

[https://imgur.com/a/iXFFifT](https://imgur.com/a/iXFFifT)

I changed every parameter there and nothing worked so I resetted it to default settings.

**Comment by r2ixuz** [comment]
This is the addon EPG (guide) setting: [https://imgur.com/a/fLv0UhB](https://imgur.com/a/fLv0UhB)

**Comment by phunkyfish** [comment]
Your settings look to be correct.

Have your tried clearing all PVR data?

**Comment by r2ixuz** [comment]
I cleared all EPG data and changed from hostname to IP. No luck...

**Comment by r2ixuz** [comment]
Oh, one more thing: I can observe randomly this error message in my kodi.log:

`NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - GetEPGForChannel Could not find <e2event> element`

**Comment by phunkyfish** [comment]
That’s just a channel that has no EPG data.

**Comment by phunkyfish** [comment]
You could also try the Kodi 19 beta1 release, it pretty stable at this point and I guess would solve your problem.

**Comment by hacky98** [comment]
I have the same problem with the newest CoreELEC on two Orbsmart S86 Pro.

I have the same settings.

When I clear the EPG data not every time Kodi fetches the EPG data.
Often I have to clear the EPG data again to start the fetching process.

Sometimes this also not helps and I need to restart Kodi completely.

**Comment by phunkyfish** [comment]
Why do you need to clear the data?

**Comment by hacky98** [comment]
I delete the EPG data so that Kodi retrieves the EPG data again.

Without deleting the data, after a certain time the EPG data is missing for more and more channels and after some time there is none at all.

**Comment by phunkyfish** [comment]
> I delete the EPG data so that Kodi retrieves the EPG data again.
> 
> Without deleting the data, after a certain time the EPG data is missing for more and more channels and after some time there is none at all.

Ok. Then this is the real problem. It should update the EPG without have to clear it. What are your EPG update settings?

**Comment by hacky98** [comment]
> > I delete the EPG data so that Kodi retrieves the EPG data again.
> 
> > 
> 
> > Without deleting the data, after a certain time the EPG data is missing for more and more channels and after some time there is none at all.
> 
> 
> 
> Ok. Then this is the real problem. It should update the EPG without have to clear it. What are your EPG update settings?
![image](https://user-images.githubusercontent.com/1338837/120074870-23546a80-c09f-11eb-8bf2-da7390783575.jpeg)
![image](https://user-images.githubusercontent.com/1338837/120074879-323b1d00-c09f-11eb-897e-9fa1d09a854f.jpeg)

This are my settings.(German language)

**Comment by phunkyfish** [comment]
Very strange. Can you try setting 1 or 2 days of past days to display and see if that makes a difference.

If not see if restarting updates the EPG instead of clearing the data.

**Comment by hacky98** [comment]
> Very strange. Can you try setting 1 or 2 days of past days to display and see if that makes a difference.
> 
> If not see if restarting updates the EPG instead of clearing the data.

I will try this out and let you know.

**Comment by hacky98** [comment]
It did not help, the problem still occurs.

**Comment by phunkyfish** [comment]
Any errors in the log?

**Comment by phunkyfish** [comment]
Every 2 hours there should be an error in the log when it tries to update the EPG. Try it without debug mode first as it will be easier to see. If nothing then try in debug mode.

**Comment by hacky98** [comment]
I attached the latest log file. Can you see there any relevant information?

[kodi.log](https://github.com/kodi-pvr/pvr.vuplus/files/6584491/kodi.log)

**Comment by phunkyfish** [comment]
Ok, there is nothing in that log. Can you provide a full debug log like here: https://kodi.wiki/view/Log_file/Easy

**Comment by hacky98** [comment]
Here is a log with debug mode enabled.
[kodi.log](https://github.com/kodi-pvr/pvr.vuplus/files/6599770/kodi.log)

**Comment by phunkyfish** [comment]
This is just the startup log. What we need is the log after a few hours to see why the EPG update is failing to be read after a number of days.

What you want to see after a few days is something like these kind of statements:

```
2021-06-04 18:00:49.774 T:27121   DEBUG <general>: AddOnLog: pvr.vuplus: pvr.vuplus - GetEPGForChannel Loaded 33 EPG Entries for channel 'Sky Cinema Classics'
2021-06-04 18:00:49.776 T:27121   DEBUG <general>: AddOnLog: pvr.vuplus: pvr.vuplus - IsInitialEpgCompleted Waiting to Get Initial EPG for 0 remaining channels
2021-06-04 18:00:49.776 T:27121   DEBUG <general>: AddOnLog: pvr.vuplus: pvr.vuplus - GetEPGForChannel Getting EPG for channel 'Sky Sport 2 HD'
```

Obviously you won't be able to upload this log file as it will be very large. What I recommended is once you start to see the Guide without data, enable debug mode and let it run for several hours. Then check the log for statements like the above.

Does that make sense?

**Comment by borygo77** [comment]
Has this ever been solved? I got exactly same problem :/ restarting box every day to have epg fetched :(

**Comment by hacky98** [comment]
> Has this ever been solved? I got exactly same problem :/ restarting box every day to have epg fetched :(

Unfortunately, I could not solve the problem for me.

That's why I replaced one of my two boxes with a real receiver.

This works better for me overall, but unfortunately without timeshift.

**Comment by phunkyfish** [comment]
> Has this ever been solved? I got exactly same problem :/ restarting box every day to have epg fetched :(

No the thread went cold. What version of kodi/addon are you running and on what platform?

After a few days do you see log lines similar to those above of you grep for `GetEPGForChannel`?

**Comment by borygo77** [comment]
I'm on CoreElec 19.3 with Enigma 2 client 19.0.0.1.
There is nothing coming up if I journalctl |grep GetEPGForChannel unfortunately

**Comment by phunkyfish** [comment]
Does `journalctl` include the kodi log?

**Comment by borygo77** [comment]
You're right. It does not. Just checked kodi.log and there is GetEPGForChannel but only minutes after reboot nothing for next couple of hours

edit: Opened some old logs and found plenty of those messages;
WARNING <general>: AddOnLog: pvr.vuplus: pvr.vuplus - GetEPGForChannel Could not find <e2event> element for channel: .....

**Comment by phunkyfish** [comment]
> You're right. It does not. Just checked kodi.log and there is GetEPGForChannel but only minutes after reboot nothing for next couple of hours
> 
> edit: Opened some old logs and found plenty of those messages; WARNING : AddOnLog: pvr.vuplus: pvr.vuplus - GetEPGForChannel Could not find element for channel: .....

Ok, can you provide an example of some of those? Do they appear only after reboot or every couple of hours?

**Comment by borygo77** [comment]
I'll will when back home. Working another 2 hours :/
Time is random and it looks like it's trying to refresh random channels from time to time.

**Comment by phunkyfish** [comment]
> I'll will when back home. Working another 2 hours :/
> Time is random and it looks like it's trying to refresh random channels from time to time.

No rush. Yes. It shouldn’t try them all at once. Let’s see.

**Comment by borygo77** [comment]
Here you have a log file from my aml box :) Hope you can find something interesting :) https://drive.google.com/file/d/1RGyIKQYEo6Fk5hEtgmrS6o60cppKe9UH/view?usp=sharing

**Comment by phunkyfish** [comment]
Is Skip Initial EPG load enabled or disabled in the addon settings?

BTW, if you use a Github gist for your log it's searchable. Google drive is not.

**Comment by borygo77** [comment]
It's disabled  😉

**Comment by phunkyfish** [comment]
I could create a test build but as you use CoreElec I have no way of giving you a testbuild. Do you have a laptop or something you could use to try out a few different scenarios?

**Comment by borygo77** [comment]
I do :) won't be watching on it but I can leave it on to check if it's updating epg as it should :) 
my coreelec device is rebooting every night and I'm grand for now ;)

**Comment by phunkyfish** [comment]
Ok, I’ll let you know once I have something ready.

**Comment by phunkyfish** [comment]
@borygo77 I've added this PR that pretty much just rips out the old logic for initial EPG from the add-on. If it resolves your EPG problems then I will clean it up (https://github.com/kodi-pvr/pvr.vuplus/pull/387)

You'll find testbuilds here: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.vuplus/detail/PR-387/1/artifacts

**Comment by borygo77** [comment]
Thank you will try it when back home and let you know how it's going 😊

**Comment by borygo77** [comment]
Can't install this unfortunately. Trying windows version and it throwing error on dependency kodi.binary.global.main 2.0.
Do you know how to fix this ? ;)
![Screenshot_2](https://user-images.githubusercontent.com/43052061/150649425-159ed797-9d83-465a-af76-aa33693ceeb3.png)

**Comment by phunkyfish** [comment]
Ah, sorry you need to use Kodi Nexus. So the latest nightly from here: https://mirrors.kodi.tv/nightlies/windows/win64/master/

**Comment by phunkyfish** [comment]
Maybe I’ll quickly create a Matrix verison as the EPG code has changed quite a bit in Nexus.

**Comment by phunkyfish** [comment]
Ok, please test on Nexus first. The code is a lot more complex in Matrix and would take a lot more time to make the change. If it works we can see about Matrix and if it's possible there.

**Comment by borygo77** [comment]
2022-01-22 23:54:28.984 T:12336    INFO <general>: Starting Kodi (20.0-ALPHA1 (19.90.101) Git:20220120-441c7a0a9c). Platform: Windows NT x86 64-bit

2022-01-23 18:37:21.715 T:2988    DEBUG <general>: AddOnLog: pvr.vuplus: pvr.vuplus - GetEPGForChannel Loaded 72 EPG Entries for channel 'HBO HD'

Seems to be working after 18h on... Never watched on it but checking debug logs it looks like it's downloading epg...

**Comment by phunkyfish** [comment]
Ok, that sounds promising. I’ll take a look at what would be needed on Matrix in the next few weeks. There is a chance this will be done on Nexus only.

**Comment by borygo77** [comment]
That’s no problem at all buddy. My libreelec device which is Matrix rebooting every night and I have my epg downloaded after reboot for 3 days. Happy with that and happy to help diagnose it for others 😊


Left it on for another day and looks like it's still downloading epg

**Comment by phunkyfish** [comment]
@borygo77 could you do one more test for me on Nexus?

Kodi Nexus: https://mirrors.kodi.tv/nightlies/windows/win64/master/
vuplus testbuild: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.vuplus/detail/PR-387/6/artifacts

**Comment by borygo77** [comment]
Updated on a laptop and will let you know soon :) It's just I won't test it for long term use. 
My daily kodi running with libreelec matrix so can't really say if it's 100% accurate.

**Comment by phunkyfish** [comment]
> Updated on a laptop and will let you know soon :) It's just I won't test it for long term use.
> My daily kodi running with libreelec matrix so can't really say if it's 100% accurate.

No need to long term test. Just to make sure it works for your setup. Thanks!

**Comment by borygo77** [comment]
It works with Nexus alright. 28 hours on and still see the requests to update EPG.

I can not update my amlogic device to Nexus for now ;)

**Comment by phunkyfish** [comment]
Brilliant, thanks for testing this. I’ll merge this in the Nexus add-on!

**Comment by phunkyfish** [comment]
Fixed by https://github.com/kodi-pvr/pvr.vuplus/pull/387, Nexus only.

**Comment by borygo77** [comment]
@phunkyfish is there any command I could use to refresh epg in matrix release? 😉 Have my box rebooted every day and it partially solve the problem but if there is no fresh epg in the vu box at the time of reboot in the early morning I'm left without epg for whole day.

**Comment by phunkyfish** [comment]
No, I don’t believe so.

How are you loading the epg on the VU box?

**Comment by borygo77** [comment]
Vu box downloading epg straight from satellite.. Im pointing your addon to vu ip 😉

**Comment by phunkyfish** [comment]
Hmm, I not see if there is anything we can do here as this is exactly the problem we fixed in Nexus.

Nexus just had its first Alpha. Is that any good for you?
