### ISSUE TITLE
Kodi <=> Enigma 2 : can record, can't change TV channel

### ISSUE THREAD

**Issue by Skelos** [kodi-pvr/pvr.vuplus#314]
Hi all,
I want see TV in Kodi. 

* Environment=> I have ZGemmaH7C with Enigma2 and OpenATV 6.5. I set up OpenWebIF as web interface and Kodi as plugin of OpenATV. So, I downloaded pvr.vuplus as Kodi addon.

* Problem =>
In my box Kodi plugin "Enigma 2" is configured fine : I see EPG in Kodi, I see channel list, and so on...  so communication between Enigma2/OpenATV <=> Kodi is ok, but when I change TV channel in Kodi using TV remote **video is black and no sound/video are received**.

* How I do in order to see TV in Kodi using webinterface
The only way to see TV channel in Kodi is connect via web to OpenWebIF and **manually change shown TV channel** click on his name in channel list when pvr.vuplus plugin is active in Kodi and shown any TV channel (it was black before click on channel name, show fine after click ). 
If I do this I see TV video and heard sounds in Kodi like standard TV. 

* What I did for try to understand this behaviour
I connected also via web to the Kodi interface (keeping OpenWebIF in other tab of my browser). I try to manage TV channel using Kodi web interface checking change on OpenWebIF.
In Kodi webinterface, when I try to record something OpenWebIF start to record. I see red circle and click on it record stop => record Json call is ok, it works.
In Kodi webinterface, **when I try to change TV channel** click on his name a quick popup shown "Change channel... ok" (or something like it) but if I check **shown channel** in OpenWebIF this **is NOT changed** and video on TV is always black. So I think Json is not calling fine despite quick popup said "OK".

Using the browser for analyse Json call, I see that change channel method is successfully called but without expected results. So I suppose Json said lies: return a success but really is failure.

I wrote same issue here : htt ps:// ww w.opena.tv /kodi-plugins-und-repos /54187-change-channel-kodi.html

**Comment by phunkyfish** [comment]
Please supply a full debug log capturing a channel change using the remote.

1. Enable debug mode (Usually Ctrl + shift + D)
2. Restart kodi
3. Play any channel
4. Change channel using the remote
5. Submit the log

Guide to submitting log files here: https://kodi.wiki/view/Log_file/Easy. Or if it's too large you can also copy it into a github gist.

Also, please supply a working link for the issue you raised on the openatv site, the one above doesn't work.

**Comment by Skelos** [comment]
Thank you for kindly reply.
I will give you a log as soon as possible. 

Regarding the link I inserted some space supposing posting external link is forbidden.
I try now with the clickable url: [https://www.opena.tv/kodi-plugins-und-repos/54187-change-channel-kodi.html](https://www.opena.tv/kodi-plugins-und-repos/54187-change-channel-kodi.html)

Let me know if it works.

**Comment by phunkyfish** [comment]
External links should be fine. 

How many tuners are there on your device? I wonder if your Enigma2 device is using one tuner and kodi the other one. There is a setting for Zap in the addon settings you might try and see if that makes a difference.

Also please take some screen shots of playing the channel the switching it using the remote.

**Comment by Skelos** [comment]
In my device I have 2 tuners DVB-T2 (and one other one for the satellite but I don't use it).
They are identified by 3 letters: A, B, C.  Satellite is A, DVB-T2 are B and C.
Actually I attached only one tuner (tuner B) and tuner C is empty : no cable for antenna TV attached.

For sure, first thing I will do is to study and set the Zap setting. May be this solve the issue, as you suggest. In this case I will update this thread and it may be closed.

Otherwise, I will send here the log as you requested and some screenshots about TV channel and switching it.
Give me few hours. I'm not at home now. ☺

**Comment by phunkyfish** [comment]
If you only have one tuner then you definitely need to enable the zap setting.

For DVB-T2 you should be able to use any standard splitter to create two feeds. This would be much better. This can’t be done with satellite but for terrestrial it’s easy.

**Comment by Skelos** [comment]
Ok. So, if I got it right: 
=> With 2 tunsers I don't need to enable zap setting.
=> You suggest to try with other anntenna cable in C tuner (now not linked) using a standard split of antenna cable.

2nd point is easy to do. Actually a second antenna TV is linked directly to the TV: I move this cable from TV to Zgemma DVB-T2 (tuner C). 

This could appears a little bit stranger. In my country (Italy) now DVB-T first version is enabled. The upgrade from DVB-T2 is started and it will ends in 2022. So, my TV is DVB-T and Zgemma DVB-T2. I will use only Zgemma when upgrade to DVB-T2 will be completed. In this moment, I have some feature in Smart TV available only if antenna is linked directly on TV. I explained this in order to show you I'm not crazy. ☺

**Comment by phunkyfish** [comment]
Yes, correct. T2 should be backward compatible with T.

You should be able to leave the cable going into your TV and just split the one going into the zgemma.

**Comment by Skelos** [comment]
I have to Enable component-specific logging before create log file? May be useful this for you?

**Comment by phunkyfish** [comment]
No, no need.

**Comment by Skelos** [comment]
Yea! First time for me sharing a log using system like this! It is very easy!
If I did all fine, you could see something in this link: https://paste.kodi.tv/qevicemuja.kodi

For me this is a lof of informations! You should see that I select "Rai 1 HD" as channel TV, after few second of black screen I pressed 'exit' on the remote and select "Rai 3 HD". After this I disable the log navigating in Kodi menu.

Let me know if this is ok.

In a glance the problem may be that my channel group name contain spaces : "Tutti i canali". Or may be not: it is contained into double quotes ("pvr://channels/tv/Tutti i canali/pvr.vuplus_252548224.pvr")

**Comment by Skelos** [comment]
You can see also this video. You see that I do:
=> go to TV in Kodi 
=> select RAI 3 HD with remote and see black screen on TV
=> go to OpenWebIF and click manually on "RAI 2 HD" and TV turns on it, image and sound are shown in TV.
=> go to OpenWebIF and click manually on "Canale 5 HD" and TV turns on it, image and sound are shown in TV
=> go to OpenWebIF and click manually on "RAI 2 HD" and TV turns on it, image and sound are shown in TV.
=> go to AWX for change TV channel in kodi, I click many times on "RETE 4 HD" and TV channel NOT change (I will back in OpenWebIF and the channel is "RAI 2 HD" again, as before)
=> I will show you the green standby button in OpenWebIF without red circle close, go to AWX for press Record on "CANALE 5 HD" and go back to OpenWebIF red rircle appears (but channel TV is "RAI 2 HD" again, as before) and 2 different channes are not good thing...

So, I'm not a developer but I think that when Kodi (via remote or via web is the same) calls OpenWebIF webservice using json something fails. 

The link to the video: https://drive.google.com/file/d/1Wjl1sStoksQqIipQdqvzJhG6h29V-e1l/view?usp=sharing

**Comment by phunkyfish** [comment]
Is your remote a CEC remote or something else?

Did you try the zap setting?

**Comment by Skelos** [comment]
No, my remote is the one I found in the Zgemma box (black remote in the video). 
I also activate CEC in order to use remote of samsung TV (this remote is white) but I did't use TV one in this test.

Not at all. I will try today zap setting.

**Comment by phunkyfish** [comment]
Which remote shouldn't matter once it can control Kodi.

What you are doing by starting the feed by using OpenWebIf is essentially zapping.

Zap essentially means switching the set top box TV output to display this channel before connecting kodi to the feed. As you only have one tuner this is the only things that will work I think.

**Comment by Skelos** [comment]
I test with Zap option enabled. **Nothing change**. You have reason: in addon interface is clearly specified "i.e. for one tuner only". I've never seen this option before.
I test also with and without option under this but **noting changes again.** :-(

**Comment by phunkyfish** [comment]
Ok, can you post a debug log with zap enabled?

Also, what skin are you using in kodi?

**Comment by phunkyfish** [comment]
The only channel I see open in your log is 
`Tutti i canali` twice via JSOn. Nothing else is opened.

There should be debug log statements like this:

`pvr.vuplus - StreamReader StreamReader: Started; url=http://192.168.1.200:8001/1:0:19:835:3EA:2174:EEEE0000:0:0:0 `

But there are none.

**Comment by phunkyfish** [comment]
Can you try switching to the estuary skin (this is the default) and see what happens.

**Comment by Skelos** [comment]
You guess! I use Confluence skin. Now I switch to Estuary. 

Using Estuary I've got a crash. 
Here log with Estuary and Zap enabled.
The Kodi log file : https://paste.kodi.tv/bokefalibu.kodi
the Enigma log crash file : https://paste.kodi.tv/sizexoreqi

Let me know if this time I got log fine.
This is the channel I selected on TV in Kodi (nothing like StreamReader):
```
2020-11-27 23:21:52.945 T:2986943136  NOTICE: OpenFile json: {
                                            	"DVDLabel": "",
                                            	"dateTime": "",
                                            	"extrainfo": "",
                                            	"lastmodified": "",
                                            	"listItem": {
                                            		"CacheThumb": "/media/hdd/.kodi/userdata/Thumbnails/3/31561ac7.jpg",
                                            		"Fanart": {
                                            			"thumb": "http://<user>:<password>@192.168.1.200:88/picon/1_0_19_BBE_3A2_110_EEEE0000_0_0_0.png"
                                            		},
                                            		"label": "Italia1 HD",
                                            		"label2": ""
                                            	},
                                            	"mimetype": "application/octet-stream",
                                            	"playerOptions": {
                                            		"startPercent": 0.0,
                                            		"startTime": 0.0
                                            	},
                                            	"size": 0,
                                            	"strPath": "pvr://channels/tv/Tutti i canali/pvr.vuplus_1158054299.pvr",
                                            	"
```

**Comment by phunkyfish** [comment]
I should have read your first post better. 

> Environment=> I have ZGemmaH7C with Enigma2 and OpenATV 6.5. I set up OpenWebIF as web interface and Kodi as plugin of OpenATV. So, I downloaded pvr.vuplus as Kodi addon.

You have kodi running on the Enigma2 device. I'm afraid you will need to go to the OpenATV forum for support. The image providers take kodi and change it to run on the their image (they change it a lot), and build it as a package.  Therefore it is not the same kodi as is available here: https://kodi.tv/download

If you install kodi on your laptop (or any of our support platforms) it will run just fine.

Sorry it took so long to get to this point.

**Comment by Skelos** [comment]
Oh, this Is a very bad news!
I am sad because I studied calling between kodi and Openwebif and my opinioni Is that replacing JSON call with a link like this http://box_ip:box_port/web/zap?sRef=channel_id
it runs fine.
I.e. this Is a working link for me:
http://192.168.1.200:88/web/zap?sRef=1:0:19:2EF:107:217C:EEEE0000:0:0:0
and It turns channel fine. 
Bit I'm not a developer so I don't have idea of how change software , create new Git branches and compile It...
This approach Is indipendent from OpenATV, Pure2 or other release of Enigma2 because It pass from a standard weblink and not from custom JSON.

May be a dream find a skilled developer can do this.

**Comment by phunkyfish** [comment]
I would just ask on the OpenATV forum if they can change this. Alternatively the current method might work if you have multiple tuners connected ;)

**Comment by Skelos** [comment]
Ok. Now I have tuners connected. I got a "T" connector and so I double TV canale (3 if count the one in TV).
Now the result Is this: https://drive.google.com/file/d/1XIot5kfvJSqVM0pTq1SK36cwcQMo1CaR/view?usp=drivesdk
I see video for 1 or 2 second after It crash.
I have to set kodi for use 2nd tuner? How?

**Comment by phunkyfish** [comment]
If you run kodi on your laptop and use the Enigma2 addon for there does it work correctly?
