### ISSUE TITLE
XBOX SERIES X Crash - reboot

### ISSUE THREAD

**Issue by koubafire** [kodi-pvr/pvr.vuplus#315]
When i try stream tv channels from vu+ solo console crash and reboots. Its worked on previous xbox one x console.

**Comment by phunkyfish** [comment]
Please provide a full debug log. You have not specified any detail of versions of anything either so hard to know what the problem could be.

**Comment by koubafire** [comment]
how i can do this on xbox?

**Comment by phunkyfish** [comment]
https://kodi.wiki/view/Log_file/Easy

**Comment by koubafire** [comment]
http://paste.kodi.tv/luyejapopo  I streamed from ip 192.168.1.111 which is VU+ Solo SE vith VTI os 

It worked on XBOX ONE X but on SERIES X its make console crash and reboot.

![image](https://user-images.githubusercontent.com/32030778/104057458-7b72f900-51f2-11eb-956e-ab8139ed55f7.png)

**Comment by phunkyfish** [comment]
Please remove the banned add-ons you have installed if you would like support. I would completely remove kodi and set it up from scratch.

then post a fresh debug log and I’ll see if I can help.

anything in orange in the log you provided is banned.

**Comment by koubafire** [comment]
WHAT BANNED ADDONS?

**Comment by phunkyfish** [comment]
Read my post again. Anything in orange in the log you provided.

**Comment by koubafire** [comment]
![3](https://user-images.githubusercontent.com/32030778/104061105-410c5a80-51f8-11eb-8111-d1f2cb422a48.PNG)
![2](https://user-images.githubusercontent.com/32030778/104061107-41a4f100-51f8-11eb-997a-5ec9e369c488.PNG)



STREAM-CINEMA is streamer from public share server in czech republic - something similar like if should you have mega.nz plugin for streaming all the mkv content from server. its main reason why i have kodi.

Simply open plugin choose movie (any from the world - choose quality and play)

**Comment by phunkyfish** [comment]
So users share content with each other using that plugin/site?

and anyone can access any of the content?

**Comment by koubafire** [comment]
FROM this server https://en.webshare.cz/#/ plugin search whole server (sotheing like you have addon which finds all mkv on mega.nz a make daabase to play choosen movie) and use users database to link video files on sever and then you can choose movie from plugin list and play (show the window list with all videos with name of the movie )

**Comment by koubafire** [comment]
> So users share content with each other using that plugin/site?
> 
> and anyone can access any of the content?

EXACTLY

**Comment by phunkyfish** [comment]
> > So users share content with each other using that plugin/site?
> > and anyone can access any of the content?
> 
> EXACTLY

But this is what pirating software is. You are sharing content that is not legally yours to share.

**Comment by koubafire** [comment]
Pirating is everywhere in the world . I am sure you know where to find.

**Comment by phunkyfish** [comment]
If you used banned add-ons I cannot support you. Those are the rules. It’s up to you remove them and supply a fresh debug log.

**Comment by koubafire** [comment]
PROBLEM SOLVED on another forum

**Comment by phunkyfish** [comment]
Glad to hear you figured it out.
