### ISSUE TITLE
pvr manager is starting up 0% - Disable & Enable

### ISSUE THREAD

**Issue by Thomas-O** [kodi-pvr/pvr.vuplus#317]
I'm having a little difficulty at boot of my LibreElec box. The Vu+/Enigma2 Client can't be loaded because of an unknown error. However, the add-on will load if I disable it and then a few seconds later re-enable. Thereafter the epg populates and everything works fine. The box is powered down each night (and sometimes several times a day) so I'm seeing this quirk quite a bit of late.

When I previously used TVheadend I selected an option in the TVheaded client's settings to delay the add-on start up to give the box time to put everything in place. I've looked for an option in the Vu+/Enigma2 Client settings but it doesn't appear to be there. Is it a similar issue and if so how can I delay the VU+ add-on's start-up? Or if there's more to it do you think it can be rewired at your end?

Thanks for your help

Thomas

Vu+/Enigma2 Client Version 2.4.12.1
LibreElec 8.2.5 on WeTek Play2
OpenViX 5.4.003 on Zgemma H92S

**Comment by phunkyfish** [comment]
You need to update LibreElec to 9.2.5 and then select wait on network in LibreElec settings.

The enigma2/vuplus addon you are running is so old is has loads of thread issues. You need at least something based on kodi 18 to fix those.

**Comment by Thomas-O** [comment]
Thanks for the advice. Though unfortunately my WeTek Play 2 has LibreElec installed on the NAND. At present there isn't a NAND version of LibreElec or CoreElec with Kodi 18. At least not one you're advised to install. There's an SD card version of 9.0.2, but switching to the SD card boot 2-3 times a day is more hassle than just flipping the disable/enable button. I'll stick with it for the while and hope for an updated NAND version in the near future.

**Comment by phunkyfish** [comment]
Sorry about that. There are 3 years worth of fixes in both v18 and v19. 

I didn’t start to maintain the addon till v18 but I remember there were some crazy bugs back then. All these have been resolved now.

**Comment by phunkyfish** [comment]
Closing as fixing on older LibreElec is not possibe.
