### ISSUE TITLE
[Question] Setting missing "Wake on LAN MAC"

### ISSUE THREAD

**Issue by ovz93br43v7** [kodi-pvr/pvr.vuplus#319]
Hello,

according to the setting overview your plugin contains a setting "Wake on LAN MAC". I have installed Kodi 18.9 on my FireTV and installed your plugin from the repo.
In my case I can't see the setting section "backend". But I found for example the backend setting "Send powerstate mode on addon exit" in advanced section. I already switched kodi settings to expert mode, to ensure that I see every setting of your plugin.

How can I make the setting "Wake on LAN MAC" visible?
And/or is it possible to extend this setting, because most VU+ receiver don't support WOL to for example send some kind of signal to a smart power plug?

**Comment by phunkyfish** [comment]
Only on kodi 19.

**Comment by ovz93br43v7** [comment]
Ok thanks.
