### ISSUE TITLE
"help needed" Load external xml EPG from local directory

### ISSUE THREAD

**Issue by uNbAs** [kodi-pvr/pvr.vuplus#322]
I have a vu + only networked with kodi using the pvr.vuplus plugin, but I have problems with EPG sync.

My version of kodi is Leia (CoreElec) I have some EPG XMLs that work fine if I import them in enigma2 and then synchronize with Kodi, but it is a somewhat uncomfortable manual work, I have seen that XML for the EPG is supported in the plugin configuration What would be the correct site?

**Comment by phunkyfish** [comment]
You should be able to automate importing the EPG data on your Enigma2 STB.

It’s not possible to import this data directly into kodi. Can you clarify which option you are referring to?

**Comment by uNbAs** [comment]
Thank you very much for your reply. He thought he could import an xml with the EPG directly from kodi.

**Comment by phunkyfish** [comment]
Iptvsimple allows you to import xml directly. But not pvr.vuplus.

I guess you could export an M3U from OpenWebIf and then import that and the xmltv in kodi using iptvsimple. I’ve never tried it though. What you are doing now might be simpler.

Is what you are doing now with the xmltv just downloading it on your STB and running an import command?

**Comment by uNbAs** [comment]
Yes, now I download the xml from http://tropical.jungle-team.online/tvheadend/koala42_individual.tar

Then with crontab I do epgimport and the kodi client sees all the epg correctly.

I like the xml option in kodi, because it relieves the load on the decoder and my device is somewhat old

With pvr.simple I need to extract the channel list in m3u format and I don't like the idea

**Comment by phunkyfish** [comment]
What you are doing with the crontab currently is correct. There is no way to get the EPG data into pvr.vuplus without it being loaded from the STB.
