### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by radimbarsa** [kodi-pvr/pvr.vuplus#335]
Hi,
I would like o ask you, how to update or get a latest enigma2 client in my Vero 4K device.
As I could see in log, latest version available is v7.4.1 , but my Kodi version shows 3.28.9 and wont update.
Is there any other option to do so ?

Thank you

**Comment by phunkyfish** [comment]
Are you running kodi 19?

**Comment by radimbarsa** [comment]
> Are you running kodi 19?

I am running the OSMC Kodi 18.9, as the Kodi 19 is not released yet.

**Comment by phunkyfish** [comment]
Then you are on the highest available version for kodi 18.
