### ISSUE TITLE
"Use Secure HTTP (https)" should not influence streaming connection

### ISSUE THREAD

**Issue by ret1** [kodi-pvr/pvr.vuplus#34]
hi!

if "Use Secure HTTP (https)" is enabled, it also tries to connect over https to the streaming port. on my dreambox with enigma2 there is no option to server the video stream over ssl. i doubt there is on any other enigma2 box.

i think there are 2 possible solutions:
1. dont let "Use Secure HTTP (https)" influence the streaming connection
2. add a 2nd "Use Secure HTTP (https)" option for the streaming connection to make it optional

thomas

**Comment by MrMC** [comment]
fixed in https://github.com/MrMC/pvr.vuplus/commit/33efe15e487c7276fd07c3a2a7484647f1ea8508

**Comment by cvigo** [comment]
Pull Request created #50
