### ISSUE TITLE
No Enigma2 PVR client in KODI v19

### ISSUE THREAD

**Issue by radimbarsa** [kodi-pvr/pvr.vuplus#340]
Hi, i have just updated my Vero 4K to latest Matrix V19 Kodi, but my Enigma2 client is not there now.
I have tried to install it from PVR repository, but it is not there. How to install it ?
Thank you

**Comment by phunkyfish** [comment]
I assume you are running OSMC?

If so you will need to ask via their support channels.

**Comment by radimbarsa** [comment]
Is there an option to download the client from your side directly ?

**Comment by radimbarsa** [comment]
Yes, I will write to the OSMC forum. Is there an option to download it from you directly and install as a zip file ?

**Comment by phunkyfish** [comment]
> Yes, I will write to the OSMC forum. Is there an option to download it from you directly and install as a zip file ?

It’s a binary addon. So it must be compiled for each platform separately. We only provide builds for the standard Kodi platforms I’m afraid.

**Comment by radimbarsa** [comment]
Thank you, just got response on OSMC. There wil review it and add it into next build if there are no issues.
