### ISSUE TITLE
Tag 7.4.6-Matrix has 7.4.5 version

### ISSUE THREAD

**Issue by MartB** [kodi-pvr/pvr.vuplus#355]
https://github.com/kodi-pvr/pvr.vuplus/commits/7.4.6-Matrix

Is missing the tooling commit https://github.com/kodi-pvr/pvr.vuplus/commit/d9833652ad57282e6e8059eefc0556081a0827a9 that increased the version and added the changelog.

**Comment by phunkyfish** [comment]
@anxdpanic might need your help with this. It’s appears the workflow released before the changelog and version commit was added.

@MartB I will fix this shortly, manually this time!

**Comment by MartB** [comment]
Thanks for fixing this, im closing this as it seems to be resolved.
