### ISSUE TITLE
Needs API 4.2.0 support

### ISSUE THREAD

**Issue by MilhouseVH** [kodi-pvr/pvr.vuplus#38]
This patch might suffice as a band aid: http://nmacleod.com/public/oebuild/patches/01_pvr_vuplus_420.txt (shamelessly nicked from @stefansaraev)

Otherwise should this add-on be put on notice for marking as broken?

**Comment by MartijnKaijser** [comment]
see
https://github.com/kodi-pvr/pvr.vuplus/pull/35

**Comment by stefansaraev** [comment]
this patch is just a hack to make it compile and is not complete. it will work only for users who dont do recordings.

**Comment by MilhouseVH** [comment]
OK fine, so presumably this add is no longer maintained? I'll drop it from future builds in that case. Thanks both.

**Comment by stefansaraev** [comment]
I meant it will work for livetv playback, no clue what side effects it might have on timeshift/recordings :)

**Comment by MilhouseVH** [comment]
The add-on can't be loaded without this patch due to the missing symbol issue, if there's no plans to upgrade to 4.2.0 then this add-on is surely dead.

**Comment by MartijnKaijser** [comment]
i wonder why it only fails to build on win32 while the rest is just happy. shouldn't it just fail?

**Comment by MartijnKaijser** [comment]
Besides it only fails for nightlies and release is still many months away so you shouldn't give a dam that this isn't include for the next months. If people really care some one will pop up to maintain it

**Comment by stefansaraev** [comment]
> i wonder why it only fails to build on win32 while the rest is just happy. shouldn't it just fail?

no. it will compile fine but fail at runtime

btw https://github.com/kodi-pvr/pvr.vuplus/issues/28#issuecomment-154194060 :)

**Comment by MilhouseVH** [comment]
I don't give a damn. I just wanted to know if this would be updated or not because as it stands it's broken. For now I'll stop building it. Thanks.

**Comment by MartijnKaijser** [comment]
@stefansaraev on windows it fails ;)
http://jenkins.kodi.tv/job/WIN-32/7827/

kodiplatform.lib(XMLUtils.cpp.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance

   Creating library pvr.vuplus.lib and object pvr.vuplus.exp

client.cpp.obj : error LNK2001: unresolved external symbol _IsRealTimeStream

pvr.vuplus.dll : fatal error LNK1120: 1 unresolved externals
