### ISSUE TITLE
Xbox Series X Crash when run Kodi-enigma2 plugin with HW Acceleration

### ISSUE THREAD

**Issue by koubafire** [kodi-pvr/pvr.vuplus#389]
Xbox Series X crash (reboot) everytime when I try stream tv form my VU+ Box. It works only when I turn off HW acceleraiton in Kodi.

**Comment by phunkyfish** [comment]
Do all channels play ok with HW acceleration  off?

**Comment by koubafire** [comment]
YEES but when I want watch UHD 4K MKV I have turn on HW acceleration again. I dont want everytime change ON -> OFF -> ON Is there any solution how to repair enigma 2 plugin to working with HW accelertion?

**Comment by phunkyfish** [comment]
Anyway to get a crash log on Xbox?

**Comment by koubafire** [comment]
I dont know to get it from XBOX

**Comment by phunkyfish** [comment]
Hmmm, then I I’m not sure how to progress this. I’m not an windows developer, nor do I own an Xbox.

**Comment by tiagoqpinto** [comment]
I have this same bug on Xbox S Series. Thanks for the hardware acceleration disabling hint!

**Comment by phunkyfish** [comment]
@koubafire, does it also crash if you watch a recording? Or only streaming live TV?

**Comment by koubafire** [comment]
I do not use recording. I only use Live TV


Problem was discovered but not solved

https://github.com/xbmc/xbmc/issues/21072

**Comment by phunkyfish** [comment]
So it should be in fixed in Matrix 19.5 once it’s released. Hopefully you won’t need to wait too long for that.

**Comment by koubafire** [comment]
I dont think so . This problem was from the first version on XBOX SERIES X . I think it was KODI 18.9

**Comment by phunkyfish** [comment]
It is fixed here: https://github.com/xbmc/xbmc/pull/21233

**Comment by phunkyfish** [comment]
And there is a backport for Matrix
