### ISSUE TITLE
Recording length and end time don't get updated for running recordings

### ISSUE THREAD

**Issue by goldelehr** [kodi-pvr/pvr.vuplus#395]
When playing a currently running recording the length of the video is set once and not updated anymore although the video length permanently increases. This leads to issues when reaching the "end" of the video. It either stops the video and one has to restart and skip forward to last seen position, or it continues playing but moving forward and backward in the video is broken (often times it just jumps to the preliminary end of the video or just stays where it was).

**Comment by phunkyfish** [comment]
This should have been fixed a long time ago. What version of the addon/kodi/OpenWebIf are you running?

**Comment by goldelehr** [comment]
I have this behaviour on two different systems:

The one i'm testing this on is a Windows PC running Kodi 19.4 and pvr.vuplus in version 19.0.0
The other one is running CoreELEC 19.5-rc2 and pvr.vuplus version 19.0.1 

Both connect to the same Enigma2 Receiver running OpenATV 6.5 + OpenWebIf 1.4.6

**Comment by goldelehr** [comment]
After upgrading OpenATV from 6.5 to 7.0 the problems are gone. OpenWebIf Version is now 1.52 . Thanks for offering your help @phunkyfish
