### ISSUE TITLE
Problem deleting recordings

### ISSUE THREAD

**Issue by bservet** [kodi-pvr/pvr.vuplus#403]
Deleting a recording often fails the first time that I execute the command. And this only seems seems to happen when the option "group items" has been turned on and the item is part of a group. I use autotimer a lot so this goes for most of my recordings.

The included debug log has a first (failed) attempt to delete a recording at 8:25 and the second one (successful) is done at 8:33
. So most of the time, the first deletion attempt fails and the second one succeeds. Deleting a whole group of recordings is also problematic.

[Debug log](https://paste.kodi.tv/ijanirelal.kodi)

**Comment by phunkyfish** [comment]
Strange, do you get an error on screen in kodi? I don't see an error in the logs. What image are you running, device, version of OpenWebIf etc.?

Deleting groups in the addon is simply many single deletes, so it's makes sense that also has issues.

**Comment by bservet** [comment]
I just tried to reproduce the problem from my PC and I could successfully delete over 10 files without any error so the platform on which kodi is running seems to be relevant here.

My "normal" Kodi system is running OSMC which has been updated to the latest version. The hardware is a Vero4K unit.

Most of the time, the delete fails and after a short pause, the selector just jumps to the top of the list. On the second attempt, most of the time the delete succeeds. I also wasn't able to reproduce any difference between group mode being enabled or not so I guess that it was just a coincidence. 

The enigma unit is a VU+ uno running OpenPLi 8.3 and openwebif 1.5.2

The problem started when I had to replace my old unit with the VU+ Uno and at the same time I also upgraded from OpenPli 8.0 to 8.1. In the beginning I thought that the new OpenPLi version was causing the problem but now I'm inclined to think that it's some kind of timing issue. But still, what could go wrong here by just submitting a delete request via openwebif?

**Comment by bservet** [comment]
I just tested deleting some recordings on my other Vero4K+ unit (slightly faster version) and on this unit I was able to delete recordings without any problems. Please note that the Vero4K (where deletion fails) was re-installed a couple of weeks ago.

**Comment by phunkyfish** [comment]
Very strange, so one Vero4k and the doesn’t? Any difference in versions between the two units?

**Comment by bservet** [comment]
There's a small difference in both the hardware and software. The unit with the problem is a Vero4K and the other one is a Vero4K+ which is a bit faster. I also upgraded the Vero4K+ to the latest development branch which, afaik, mostly contains a couple a video decoding related fixes which will be finalized in the upcoming oktober release. 

So although I wouldn't expect it to make any difference, I could easily upgrade the other unit to the same branch as well.

**Comment by phunkyfish** [comment]
Worth a shot. I also don’t see why that would make a difference. But if they both use the same version, and still have a problem then all we are left with is hardware.

**Comment by bservet** [comment]
I've just done the upgrade and at the moment, deletion is working from that unit as well! Maybe it's just being caused by the recent reboot so I'll do some more testing in the coming days and post an update.

**Comment by phunkyfish** [comment]
Ok, it’s possible there was a fix in PVR in kodi core between the versions that fixed the issue.

OSMC likely pulls in patchsets in some fashion.

**Comment by bservet** [comment]
The behaviour seems to be back. I'll try the other Vero4K+ unit later as well. I don't think that it's important for this case but I always put my receiver in deep sleep.

**Comment by phunkyfish** [comment]
It shouldn’t be. But to rule it out can you leave it out of deep sleep for a couple of days and see if it makes a difference?

**Comment by bservet** [comment]
Sure, no problem. I've just disabled deep standby and rebooted the Vero4K unit. I'll do some testing later and post an update.

**Comment by bservet** [comment]
Did some further testing, disabling deep standby didn't help. However, I discovered that deleting recordings with a short name like "qi" or "motogp" always seem to work fine on the first try. Longer names like "superbike gp hoogtepunten". So maybe the length or the %20 is causing this. As far as I know deleted recordings aren't easily recovered from the trash which makes reproducing the behaviour a bit more difficult.

**Comment by phunkyfish** [comment]
If it was a buffer length issue or even the `%20` you would think it would happen repeatedly. It doesn’t make sense why it only happens sometimes.

**Comment by bservet** [comment]
Finally did a total rebuild without restoring and the problem is gone. Would have loved to know what was causing the problem. I noticed that group items isn't working anymore just as on the two other units but I can't see how that could be related.
