### ISSUE TITLE
EPGs disappear several senconds after Kodi v20 RC1 startups

### ISSUE THREAD

**Issue by kokikoku** [kodi-pvr/pvr.vuplus#412]
KODI updated from Microsoft Store automatically these days. 
EPGs disappear several senconds after Kodi startups, and not appear anymore watch or not watch any channel.

Starting Kodi (20.0-RC1 (19.90.901) Git:20221210-911ad268d0). Platform: Windows NT x86 64-bit
Running on Windows 10 21H2, kernel: Windows NT x86 64-bit version 10.0.19044.2251
Enigma2 Client V20.4.0

https://paste.kodi.tv/nanatapuhu

**Comment by ksooo** [comment]
Nothing the add-on can fix. Known issue, that will be fixed in Kodi, for Nexus final. See https://github.com/xbmc/xbmc/issues/22208
