### ISSUE TITLE
Kodi 21 on Pi4 - TV-Stream from Dreambox stutters - Recordings smooth

### ISSUE THREAD

**Issue by egabosh** [kodi-pvr/pvr.vuplus#454]
Moin,

## Setup:

- Raspberry Pi 4 with RaspberryPiOS Debian 12
- X11 (no wayland)
- Kodi 21 installed via flatpak runs on a Raspberry Pi 4B
- pvr.vuplus installed via Kodi-Repoo/GUI
- Dreambox 920 UHD with Stock Enigma
 
##  What works:

- Videos (h265) run smoothly locally or via network drive (SFTP/NFS)
- unmodified recordings of the Dreambox can be played in kodi without problems - also over the network.

## Problem:

- Videos/TV streamed via the Dreambox are jerky and the entire Kodi can hardly be operated

I assume that it is not a codec problem or a problem with the X11 interface because Kodi plays recordings from the Dreambox without any problems.
Unfortunately I have no idea what the problem could be. I suspect maybe a bug/problem with the way the stream is addressed?

### Log attached
[kodi.log](https://github.com/kodi-pvr/pvr.vuplus/files/15001993/kodi.log)

### Debug Log attached
[kodi.log](https://github.com/kodi-pvr/pvr.vuplus/files/15011537/kodi.log)

Hope someone here can help. :-)

**Comment by egabosh** [comment]
Here the kodi log with debug enabled.
[kodi.log](https://github.com/kodi-pvr/pvr.vuplus/files/15011492/kodi.log)

**Comment by egabosh** [comment]
sorry, wrong button

**Comment by egabosh** [comment]
Found the reason:
Some expired timers have accumulated on the Dreambox.
This also caused the loading/initializing of the pvr.vuplus addon to take a few minutes before starting  the live TV stream was possible. Seems it downloads all the data from the Dreambox on startup. See debug log.
After deleting these expired timers, everything suddenly ran smoothly.
I still wonder why this has such an impact on the video stream itself?
Maybe the pvr.vuplus addon can be improved?

**Comment by phunkyfish** [comment]
The addon can’t really do anything about this. Sometimes E2 device timers get messed up (like yours) and this problem happens. I never found out why but it’s a E2 device problem.

**Comment by phunkyfish** [comment]
That being said if we can find out the charteristics of these problem timers we can probably detect them. But the last time it happened for me and I couldn’t find anything that distinguished them from other timers.

but there is an option to cleanup expired timers in the addon settings. Maybe try that?

**Comment by egabosh** [comment]
Thank you. I will try soon. 
Maybe there can pop up a kind of warning if there are a lot of old timers? It took many, many hours to find the reason. I think others can save a lot of time with a warning.

**Comment by phunkyfish** [comment]
This is something that should be fixed on the E2 device, doesn’t make sense to do it on Kodi. How many is too many timers? It really depends on the device you have it’s its limitations. Plus I reckon the problem is with certain images and not others.

The timers cleanup feature is the most we can do in the add-on.

**Comment by egabosh** [comment]
OK, thank you am lot for these informations and your point of view.
