### ISSUE TITLE
Frozen VU+ when using the plugin.

### ISSUE THREAD

**Issue by FloydKulis** [kodi-pvr/pvr.vuplus#469]
I have two problems with connecting to Kodi and the Enigma2 plugin.
The first is that from time to time enigma2 hangs and the entire decoder does not respond. The only thing that shows me is the time on the screen on the front of the decoder at which the decoder hung up.
I have to unplug the decoder and turn it back on. I'm guessing it's a plugin problem because it most often happens when I launch Kodi. But this is not always the case and it only stops working after some time.

The second problem is that every hour I receive a message about the lack of connection to the decoder in Kodi, which causes Kodi to turn off. After restarting Kodi, everything works.

**Comment by phunkyfish** [comment]
Please supply a full debug log

**Comment by FloydKulis** [comment]
I think the topic can be closed. The problem is in the software on the decoder. I changed to Egami from ATV and it works for now.


ATV gave an error every hour:
`20:00:53.9386 [singleRead] error: Function not implemented
20:00:53.9387 [eDVBServiceStream] stop streaming m_state 2
20:00:53.9399 [eFilePushThreadRecorder] stopping thread.
20:00:53.9401 [eDVBRecordStreamThread] cancelling aio
20:00:53.9402 [eDVBRecordStreamThread] all done
20:00:53.9402 [eDVBRecordFileThread] waiting for aio to complete
20:00:53.9402 [eDVBRecordFileThread] wait: aio_return returned failure: Function not implemented
20:00:53.9403 [eDVBRecordFileThread] buffer usage histogram (40 buffers of 192 kB)
20:00:53.9403 [eDVBRecordFileThread]   0:     53
20:00:53.9403 [eDVBRecordFileThread]   1:  10067
20:00:53.9403 [eDVBRecordFileThread]   2:   9486
20:00:53.9404 [eDVBRecordFileThread]   3:      5
20:00:53.9404 [eFilePushThreadRecorder] THREAD STOP
20:00:53.9406 [eDVBServiceStream] stop streaming m_state 0
20:00:53.9421 [eDVBCAService] free slot 1 demux 1 for service 1:0:1:70F:32C8:13E:820000:0:0:0:
20:00:53.9421 [eDVBCAService] free service 1:0:1:70F:32C8:13E:820000:0:0:0:
20:00:53.9430 [eDVBLocalTimerHandler] Remove channel 0x162caa0.
20:00:53.9431 [eEPGTransponderDataReader] remove channel 0x162caa0
20:00:56.9460 [eDVBFrontend] try to close frontend 2
20:00:56.9461 [eDVBSatelliteEquipmentControl] takeover_sec 0
20:00:56.9461 [eDVBSatelliteEquipmentControl] waittakeover_sec 2
20:00:56.9461 [eDVBFrontend] [turnOffSatCR] running mainloop top_tuner 0
20:00:56.9462 [eDVBFrontend] [turnOffSatCR] running mainloop this_tuner 0
20:00:56.9464 [SEC-Slave] tuner 0 start takeover frontend
20:00:56.9464 [SEC-Master] tuner 2 WAIT_TAKEOVER
20:00:56.9467 [eDVBFrontend] [SEC] tuner 2 setVoltage 1
20:00:56.9467 [eDVBFrontend0] setVoltage FE_ENABLE_HIGH_LNB_VOLTAGE 0 FE_SET_VOLTAGE 0
20:00:56.9617 [eDVBFrontend] [SEC] tuner 2 sleep 1000ms
20:00:57.1348 [eDVBFrontend] (0)fe event: status 1f, inversion off, m_tuning 0
20:00:57.9434 [SEC-Slave] tuner 0 timeout takeover frontend
20:00:57.9436 [SEC-Slave] tuner 0 end takeover frontend
20:00:57.9446 [SEC] tuner 0 newTunertype 0
20:00:57.9618 [eDVBFrontend] [SEC] tuner 2 setVoltage 4
20:00:57.9618 [eDVBFrontend0] setVoltage FE_ENABLE_HIGH_LNB_VOLTAGE 1 FE_SET_VOLTAGE 1
20:00:57.9709 [SEC] tuner 2 setTone 0
20:00:57.9821 [eDVBFrontend] [SEC] tuner 2 sleep 75ms
20:00:58.1150 [SEC] tuner 2 sendDiseqc: 7008000020:00:58.1178 [eDVBFrontend] [SEC] diseqc ioctl duration: 57 ms -> extra guard delay 9 ms20:00:58.1275 [eDVBFrontend] [SEC] tuner 2 sleep 100ms
20:00:58.1498 [eDVBFrontend] (0)fe event: status 1f, inversion off, m_tuning 0
20:00:58.2276 [eDVBFrontend] [SEC] tuner 2 setVoltage 1
20:00:58.2277 [eDVBFrontend0] setVoltage FE_ENABLE_HIGH_LNB_VOLTAGE 0 FE_SET_VOLTAGE 0
20:00:58.2365 [SEC] tuner 2 delayed close frontend
20:00:58.2366 [eDVBFrontend] try to close frontend 2
20:00:58.2368 [eDVBFrontend2] setVoltage FE_ENABLE_HIGH_LNB_VOLTAGE 0 FE_SET_VOLTAGE 2
20:00:58.2371 [SEC-Master] tuner 2 RELEASE
20:00:58.2371 [SEC-Master] tuner 2 release frontend
20:00:59.1287 [eDVBFrontend] (0)fe event: status 1f, inversion off, m_tuning 0`
