### ISSUE TITLE
After Channel zap, buffering for 5 seconds

### ISSUE THREAD

**Issue by Cosmicbase** [kodi-pvr/pvr.vuplus#71]
Hello there, I use the #0722 milhouse 9 for for rpi3 because the the versions after #0722 have problems with channel switching. After you switch from a  channel to the other there ist always buffering for 5 seconds. I'm very unhappy for this situation. The issue is also present with all versions from #0723 -  #0822. There was many api changes. 

Please help.

**Comment by M2k80** [comment]
hopefully someone will fix this

**Comment by phunkyfish** [comment]
@Cosmicbase is this still an issue?

**Comment by M2k80** [comment]
No, its fixed since stream is used as livestream

phunkyfish <notifications@github.com> schrieb am Mo., 1. Okt. 2018, 15:52:
