### ISSUE TITLE
& and " displayed wrong

### ISSUE THREAD

**Issue by nilleiz** [kodi-pvr/pvr.vuplus#78]
Hi,

& character is displayed as `&amp;` and " is displayed as `&quot; `.

I am on vti 11 and have got a Uno 4k VU+ receiver.
If you more information are needed just tell me.

Hope this can be fixed.

**Comment by spathi85** [comment]
Same here. Already opened an issue at E2OpenPlugins/e2openplugin-OpenWebif (https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/772) but I was told that this has to be fixed within the 3rd party applications.

**Comment by zehnerGIT** [comment]
I have checked the output of OpenWebIf and the output is wrong an has to be fixed there. Some characters are not allowed in XML and must be replaced. " needs to be converted to &quot; and & must be converted to &amp;
But OpenWebIf converts the already escaped character &quot; once more to &amp;quot; and that's not correct.

**Comment by zehnerGIT** [comment]
imo issue is fixed.
OpenWebIf still delivers wrong xml (now it doesn't escape &quot;), but less wrong than before... 
Other xml parsers could have problems with the epg, but TinyXML (at least the currently used version) has no problems reading the xml

**Comment by phunkyfish** [comment]
Thanks
