### ISSUE TITLE
[FEATURE] HbbTV support

### ISSUE THREAD

**Issue by AndreasA** [kodi-pvr/pvr.vuplus#85]
Hi,

the plugin works great and supports nearly everything. 
However, one small detail is missing and that is support HbbTV when e.g. using the latest VTi image with VU+ STB.
Would be nice if support for HbbTV could be added too.

Although I think that this might currently be a kodi limitation?

**Comment by zehnerGIT** [comment]
The VuPlus client has no active maintainer, so I would not expect new features in the near future and with all the scrapers and addons from KODI, HbbTV is not a very important feature.

HbbTV is based on HTML, so first of all, KODI must integrate a HTML rendering engine. Only initial work is done (https://github.com/AlwinEsch/web.browser.chromium , https://forum.kodi.tv/showthread.php?tid=304598 ), so don't expect the integration in the next KODI versions. 
If KODI has integrated the engine, then a developer can integrate it in the client, but without a maintainer, that would be the next problem...

**Comment by phunkyfish** [comment]
Closing as this is unlikely unless support is added to kodi.
