### ISSUE TITLE
GetInitialEPGForGroup called for each CHANNEL while initial EPG Update

### ISSUE THREAD

**Issue by alorbach** [kodi-pvr/pvr.vuplus#86]
It seems like that the plugin is not working properly, when using all Bouqutes, it calls "GetInitialEPGForGroup" each time a single Channel is updated. 

The result is that old enigma based devices are slow as hell for half an hour, while new devices have more power and the user doesn't relize that this is a problem.

I can provide debug logs. 
Found this because single bouquet was working pretty fast and I digged into the code a little more.

**Comment by ksooo** [comment]
> are channels called for by kodi pvr one at a time or in parallel?

 one at a time

**Comment by phunkyfish** [comment]
Ok, as the channels are done one at a time this must be a logic error of some sort. Let me dig in a bit more and put together some tests for for multiple bouquets and see what I can find.

**Comment by phunkyfish** [comment]
I've solved this one. Also take a look at #101 , this should bring another 50% improvement assuming that you have an all channels bouquet as well as smaller groups.
