### ISSUE TITLE
Internal group list not holding "All Channels" group after being populated by vu addon

### ISSUE THREAD

**Issue by mcaptur** [kodi-pvr/pvr.vuplus#9]
see http://trac.kodi.tv/ticket/16073

"synchronise channel groups with backend(s)" is broken with vu addon in latest build after pr7300. If unselected all works fine, but if i select it and delete tv and epg databases, groups are created and populated, but no epg is loaded and i cannot playback channels. this only happens with vu addon hts and filmon work fine..

**Comment by mcaptur** [comment]
issue caused due to empty favourites group.. xhaggi will push fix to kodi.

**Comment by xhaggi** [comment]
fixed by https://github.com/xbmc/xbmc/pull/7356
